version: 2
updates:
  - package-ecosystem: gomod
    directory: /
    schedule:
      interval: weekly
    groups:
      go:
        patterns: ["*"]

  - package-ecosystem: npm
    directory: /apps/web
    schedule:
      interval: weekly
    groups:
      npm:
        patterns: ["*"]

  - package-ecosystem: npm
    directory: /packages/api-client
    schedule:
      interval: weekly
    groups:
      npm:
        patterns: ["*"]

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly

  - package-ecosystem: docker
    directory: /deploy
    schedule:
      interval: weekly
