#!/usr/bin/env bash
# Relay quick install — self-hosted server via Docker Compose.
#
#   curl -fsSL https://raw.githubusercontent.com/Dvorinka/relay/main/install.sh | bash
#
# Prompts for install dir, public URL/domain and port, generates secrets,
# writes .env + docker-compose.yml, pulls images and starts the stack.
#
# Non-interactive use (CI / automation) — set env vars, prompts are skipped:
#   RELAY_DIR=~/relay RELAY_PUBLIC_URL=https://relay.example.com \
#   RELAY_PORT=8080 RELAY_IMAGE=ghcr.io/dvorinka/relay:latest RELAY_YES=1 \
#     bash install.sh
set -euo pipefail

say()  { printf '\033[36mrelay\033[0m %s\n' "$*"; }
warn() { printf '\033[33mrelay\033[0m %s\n' "$*" >&2; }
die()  { printf '\033[31mrelay\033[0m %s\n' "$*" >&2; exit 1; }

# Ask on /dev/tty so prompts still work under `curl | bash`. Returns the
# default when stdin has no terminal or RELAY_YES=1.
ask() {
  local var="$1" prompt="$2" default="$3" reply
  if [[ "${RELAY_YES:-0}" == "1" ]]; then
    printf -v "$var" '%s' "${!var:-$default}"; return
  fi
  printf '\033[36mrelay\033[0m %s [%s]: ' "$prompt" "$default" > /dev/tty
  if ! read -r reply < /dev/tty; then
    printf -v "$var" '%s' "${!var:-$default}"; return
  fi
  printf -v "$var" '%s' "${reply:-${!var:-$default}}"
}

# --- Preflight ---------------------------------------------------------------

command -v docker >/dev/null || die "docker not found — install Docker first: https://docs.docker.com/get-docker/"
docker compose version >/dev/null 2>&1 || die "'docker compose' plugin missing — install Docker Compose v2."
docker info >/dev/null 2>&1 || die "docker daemon not reachable — start Docker or check permissions (try: sudo usermod -aG docker $USER)."

# --- Answers -----------------------------------------------------------------

ask RELAY_DIR "Install directory" "${RELAY_DIR:-$HOME/relay}"
RELAY_DIR="${RELAY_DIR/#\~/$HOME}"

ask RELAY_PUBLIC_URL "Public URL — domain or http://localhost:PORT" "${RELAY_PUBLIC_URL:-http://localhost:8080}"
# Bare domain gets https:// — Relay sets Secure cookies on https URLs.
[[ "$RELAY_PUBLIC_URL" =~ ^https?:// ]] || RELAY_PUBLIC_URL="https://$RELAY_PUBLIC_URL"
RELAY_PUBLIC_URL="${RELAY_PUBLIC_URL%/}"

default_port="${RELAY_PORT:-8080}"
if [[ "$RELAY_PUBLIC_URL" =~ :([0-9]+)$ ]]; then default_port="${BASH_REMATCH[1]}"; fi
ask RELAY_PORT "Port to listen on" "$default_port"
[[ "$RELAY_PORT" =~ ^[0-9]+$ ]] || die "port must be a number, got '$RELAY_PORT'"

RELAY_IMAGE="${RELAY_IMAGE:-ghcr.io/dvorinka/relay:latest}"

if [[ "$RELAY_PUBLIC_URL" == https://* ]]; then
  insecure="false"
else
  insecure="true"
  warn "http URL — session cookies will not be Secure. Use https (e.g. behind Caddy/Traefik/nginx) for anything public-facing."
fi

say "Install dir : $RELAY_DIR"
say "Public URL  : $RELAY_PUBLIC_URL"
say "Port        : $RELAY_PORT"
say "Image       : $RELAY_IMAGE"

# --- Files -------------------------------------------------------------------

mkdir -p "$RELAY_DIR"
gen() { openssl rand -hex 32 2>/dev/null || od -An -N32 -tx1 /dev/urandom | tr -d ' \n'; }
AUTH_SECRET="${AUTH_SECRET:-$(gen)}"
S3_AK="$(openssl rand -hex 10 2>/dev/null || od -An -N10 -tx1 /dev/urandom | tr -d ' \n')"
S3_SK="$(gen)"

umask 077
{
  printf '# Generated by install.sh — %s\n' "$(date -u +%Y-%m-%dT%H:%M:%SZ)"
  printf 'RELAY_PUBLIC_URL=%s\n' "$RELAY_PUBLIC_URL"
  printf 'AUTH_SECRET=%s\n' "$AUTH_SECRET"
  printf 'AUTH_INSECURE_DEV=%s\n' "$insecure"
  printf 'RELAY_LISTEN_ADDR=:8080\n'
} > "$RELAY_DIR/.env"
umask 022

cat > "$RELAY_DIR/docker-compose.yml" <<EOF
# Generated by install.sh — image-based stack (no source checkout needed).
# For a source build instead, clone the repo and use ./docker-compose.yml.
services:
  relay:
    image: $RELAY_IMAGE
    env_file: .env
    environment:
      DATABASE_URL: postgres://relay:relay@postgres:5432/relay?sslmode=disable
      STORAGE_ENDPOINT: http://storage:9000
      STORAGE_PUBLIC_ENDPOINT: $RELAY_PUBLIC_URL
      STORAGE_ACCESS_KEY: $S3_AK
      STORAGE_SECRET_KEY: $S3_SK
      STORAGE_BUCKET: relay
    ports:
      - "$RELAY_PORT:8080"
    depends_on:
      postgres:
        condition: service_healthy
      storage:
        condition: service_started
      storage-init:
        condition: service_completed_successfully
    restart: unless-stopped

  postgres:
    image: postgres:17-alpine
    environment:
      POSTGRES_USER: relay
      POSTGRES_PASSWORD: relay
      POSTGRES_DB: relay
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U relay -d relay"]
      interval: 5s
      timeout: 3s
      retries: 12
    restart: unless-stopped

  storage:
    image: rustfs/rustfs:latest
    command: /data
    environment:
      RUSTFS_ACCESS_KEY: $S3_AK
      RUSTFS_SECRET_KEY: $S3_SK
    volumes:
      - s3data:/data
    restart: unless-stopped

  storage-init:
    image: amazon/aws-cli:latest
    depends_on:
      - storage
    environment:
      AWS_ACCESS_KEY_ID: $S3_AK
      AWS_SECRET_ACCESS_KEY: $S3_SK
      AWS_REGION: us-east-1
    entrypoint: >
      /bin/sh -c "sleep 3;
      aws --endpoint-url http://storage:9000 s3 mb s3://relay || true"
    restart: "no"

volumes:
  pgdata:
  s3data:
EOF

# --- Up ----------------------------------------------------------------------

cd "$RELAY_DIR"
say "Pulling images..."
docker compose pull
docker compose up -d

say "Waiting for Relay on port $RELAY_PORT..."
up=""
for _ in $(seq 1 60); do
  if curl -fsS "http://localhost:$RELAY_PORT/api/health" >/dev/null 2>&1; then
    up=1; break
  fi
  sleep 2
done
[[ -n "$up" ]] || die "Relay did not come up — check 'cd $RELAY_DIR && docker compose logs relay'."

cat <<DONE

  Relay is running.

    App       $RELAY_PUBLIC_URL   (first registered account becomes the owner)
    Local     http://localhost:$RELAY_PORT
    Config    $RELAY_DIR/.env
    Compose   $RELAY_DIR/docker-compose.yml

  Desktop app: install Relay-Setup-<ver>.exe (Windows) or relay-desktop
  (Linux) from the GitHub release and enter $RELAY_PUBLIC_URL on the
  connect screen — or pick "Work offline" to skip the server entirely.

  Useful commands (run inside $RELAY_DIR):
    docker compose logs -f relay     # follow logs
    docker compose pull && docker compose up -d   # upgrade to latest
    docker compose down              # stop (data in pgdata/s3data volumes)
DONE
