// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: activity.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const listGrantedOpenIssues = `-- name: ListGrantedOpenIssues :many
select i.id, i.project_id, cast(p.key || '-' || i.number as text) as key,
       i.title, i.status, i.priority, i.github_kind, i.updated_at,
       p.key as project_key, p.name as project_name
from issues i
join projects p on p.id = i.project_id
join agents a on a.id = $1
left join agent_project_permissions g
       on g.agent_id = a.id and g.project_id = p.id
where i.status not in ('done','cancelled')
  and ('project:read' = any(g.scopes)
       or (a.grant_all and 'project:read' = any(a.grant_scopes)))
order by i.updated_at desc
limit 40
`

type ListGrantedOpenIssuesRow struct {
	ID          pgtype.UUID        `json:"id"`
	ProjectID   pgtype.UUID        `json:"project_id"`
	Key         string             `json:"key"`
	Title       string             `json:"title"`
	Status      string             `json:"status"`
	Priority    string             `json:"priority"`
	GithubKind  string             `json:"github_kind"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
	ProjectKey  string             `json:"project_key"`
	ProjectName string             `json:"project_name"`
}

// same feed as ListMyOpenIssues but scoped to the calling agent's project
// grants: explicit rows win, grant_all + project:read covers the workspace
func (q *Queries) ListGrantedOpenIssues(ctx context.Context, agentID pgtype.UUID) ([]ListGrantedOpenIssuesRow, error) {
	rows, err := q.db.Query(ctx, listGrantedOpenIssues, agentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListGrantedOpenIssuesRow{}
	for rows.Next() {
		var i ListGrantedOpenIssuesRow
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.Key,
			&i.Title,
			&i.Status,
			&i.Priority,
			&i.GithubKind,
			&i.UpdatedAt,
			&i.ProjectKey,
			&i.ProjectName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listGrantedRecentMessages = `-- name: ListGrantedRecentMessages :many
select m.id, m.conversation_id, m.body, m.created_at,
       case when m.deleted_at is null
            then coalesce(u.name, a2.name, nullif(m.author_name_snapshot, ''), '')
            else 'Deleted' end as author_name,
       case when m.author_agent_id is not null then 'agent' else 'user' end as author_kind,
       c.project_id, p.key as project_key, p.name as project_name,
       c.kind as conversation_kind
from messages m
join conversations c on c.id = m.conversation_id
join projects p on p.id = c.project_id
join agents a on a.id = $1
left join agent_project_permissions g
       on g.agent_id = a.id and g.project_id = p.id
left join users u on u.id = m.author_user_id
left join agents a2 on a2.id = m.author_agent_id
where m.deleted_at is null
  and ('project:read' = any(g.scopes)
       or (a.grant_all and 'project:read' = any(a.grant_scopes)))
order by m.created_at desc
limit 15
`

type ListGrantedRecentMessagesRow struct {
	ID               pgtype.UUID        `json:"id"`
	ConversationID   pgtype.UUID        `json:"conversation_id"`
	Body             string             `json:"body"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	AuthorName       string             `json:"author_name"`
	AuthorKind       string             `json:"author_kind"`
	ProjectID        pgtype.UUID        `json:"project_id"`
	ProjectKey       string             `json:"project_key"`
	ProjectName      string             `json:"project_name"`
	ConversationKind string             `json:"conversation_kind"`
}

// latest messages across an agent's granted projects — the agent-side
// activity feed behind the MCP `activity` tool
func (q *Queries) ListGrantedRecentMessages(ctx context.Context, agentID pgtype.UUID) ([]ListGrantedRecentMessagesRow, error) {
	rows, err := q.db.Query(ctx, listGrantedRecentMessages, agentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListGrantedRecentMessagesRow{}
	for rows.Next() {
		var i ListGrantedRecentMessagesRow
		if err := rows.Scan(
			&i.ID,
			&i.ConversationID,
			&i.Body,
			&i.CreatedAt,
			&i.AuthorName,
			&i.AuthorKind,
			&i.ProjectID,
			&i.ProjectKey,
			&i.ProjectName,
			&i.ConversationKind,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMyOpenIssues = `-- name: ListMyOpenIssues :many
select i.id, i.project_id, cast(p.key || '-' || i.number as text) as key,
       i.title, i.status, i.priority, i.github_kind, i.updated_at,
       p.key as project_key, p.name as project_name
from issues i
join projects p on p.id = i.project_id
join workspace_members wm on wm.workspace_id = p.workspace_id
where wm.user_id = $1
  and i.status not in ('done','cancelled')
order by i.updated_at desc
limit 40
`

type ListMyOpenIssuesRow struct {
	ID          pgtype.UUID        `json:"id"`
	ProjectID   pgtype.UUID        `json:"project_id"`
	Key         string             `json:"key"`
	Title       string             `json:"title"`
	Status      string             `json:"status"`
	Priority    string             `json:"priority"`
	GithubKind  string             `json:"github_kind"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
	ProjectKey  string             `json:"project_key"`
	ProjectName string             `json:"project_name"`
}

// open issues and GitHub-linked PRs across every project the user can see,
// most recently touched first. The /api/me/activity handler splits issue vs
// pr on github_kind.
func (q *Queries) ListMyOpenIssues(ctx context.Context, userID pgtype.UUID) ([]ListMyOpenIssuesRow, error) {
	rows, err := q.db.Query(ctx, listMyOpenIssues, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListMyOpenIssuesRow{}
	for rows.Next() {
		var i ListMyOpenIssuesRow
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.Key,
			&i.Title,
			&i.Status,
			&i.Priority,
			&i.GithubKind,
			&i.UpdatedAt,
			&i.ProjectKey,
			&i.ProjectName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMyRecentMessages = `-- name: ListMyRecentMessages :many
select m.id, m.conversation_id, m.body, m.created_at,
       case when m.deleted_at is null
            then coalesce(u.name, a.name, nullif(m.author_name_snapshot, ''), '')
            else 'Deleted' end as author_name,
       case when m.author_agent_id is not null then 'agent' else 'user' end as author_kind,
       c.project_id, p.key as project_key, p.name as project_name,
       c.kind as conversation_kind
from messages m
join conversations c on c.id = m.conversation_id
join projects p on p.id = c.project_id
join workspace_members wm on wm.workspace_id = p.workspace_id
left join users u on u.id = m.author_user_id
left join agents a on a.id = m.author_agent_id
where wm.user_id = $1
  and m.deleted_at is null
order by m.created_at desc
limit 12
`

type ListMyRecentMessagesRow struct {
	ID               pgtype.UUID        `json:"id"`
	ConversationID   pgtype.UUID        `json:"conversation_id"`
	Body             string             `json:"body"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	AuthorName       string             `json:"author_name"`
	AuthorKind       string             `json:"author_kind"`
	ProjectID        pgtype.UUID        `json:"project_id"`
	ProjectKey       string             `json:"project_key"`
	ProjectName      string             `json:"project_name"`
	ConversationKind string             `json:"conversation_kind"`
}

// latest messages across all visible projects for the dashboard feed
func (q *Queries) ListMyRecentMessages(ctx context.Context, userID pgtype.UUID) ([]ListMyRecentMessagesRow, error) {
	rows, err := q.db.Query(ctx, listMyRecentMessages, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListMyRecentMessagesRow{}
	for rows.Next() {
		var i ListMyRecentMessagesRow
		if err := rows.Scan(
			&i.ID,
			&i.ConversationID,
			&i.Body,
			&i.CreatedAt,
			&i.AuthorName,
			&i.AuthorKind,
			&i.ProjectID,
			&i.ProjectKey,
			&i.ProjectName,
			&i.ConversationKind,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
