// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: agents.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const agentLastSeen = `-- name: AgentLastSeen :one
select cast(max(last_used_at) as timestamptz) as last_seen_at from mcp_tokens where agent_id = $1
`

func (q *Queries) AgentLastSeen(ctx context.Context, agentID pgtype.UUID) (pgtype.Timestamptz, error) {
	row := q.db.QueryRow(ctx, agentLastSeen, agentID)
	var last_seen_at pgtype.Timestamptz
	err := row.Scan(&last_seen_at)
	return last_seen_at, err
}

const agentScopeForProject = `-- name: AgentScopeForProject :one
select coalesce(g.scopes, '{}'::text[]) as scopes
from agents a
left join agent_project_permissions g
       on g.agent_id = a.id and g.project_id = $1
where a.id = $2
`

type AgentScopeForProjectParams struct {
	ProjectID pgtype.UUID `json:"project_id"`
	AgentID   pgtype.UUID `json:"agent_id"`
}

// scopes the agent holds on a project; empty set when ungranted
func (q *Queries) AgentScopeForProject(ctx context.Context, arg AgentScopeForProjectParams) ([]string, error) {
	row := q.db.QueryRow(ctx, agentScopeForProject, arg.ProjectID, arg.AgentID)
	var scopes []string
	err := row.Scan(&scopes)
	return scopes, err
}

const agentSlugExists = `-- name: AgentSlugExists :one
select exists (select 1 from agents where workspace_id = $1 and slug = $2)
`

type AgentSlugExistsParams struct {
	WorkspaceID pgtype.UUID `json:"workspace_id"`
	Slug        string      `json:"slug"`
}

func (q *Queries) AgentSlugExists(ctx context.Context, arg AgentSlugExistsParams) (bool, error) {
	row := q.db.QueryRow(ctx, agentSlugExists, arg.WorkspaceID, arg.Slug)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const agentWorkspaceRole = `-- name: AgentWorkspaceRole :one
select cast(coalesce((
    select wm.role from agents a
    join workspace_members wm on wm.workspace_id = a.workspace_id
    where a.id = $1 and wm.user_id = $2
), '') as text) as role
`

type AgentWorkspaceRoleParams struct {
	ID     pgtype.UUID `json:"id"`
	UserID pgtype.UUID `json:"user_id"`
}

// caller's role in the agent's workspace, ” when not a member
func (q *Queries) AgentWorkspaceRole(ctx context.Context, arg AgentWorkspaceRoleParams) (string, error) {
	row := q.db.QueryRow(ctx, agentWorkspaceRole, arg.ID, arg.UserID)
	var role string
	err := row.Scan(&role)
	return role, err
}

const createAgent = `-- name: CreateAgent :one
insert into agents (workspace_id, name, slug, description, review_mode, created_by)
values ($1, $2, $3, $4, $5, $6)
returning id, workspace_id, name, slug, description, avatar_key, created_by, created_at, updated_at, review_mode
`

type CreateAgentParams struct {
	WorkspaceID pgtype.UUID `json:"workspace_id"`
	Name        string      `json:"name"`
	Slug        string      `json:"slug"`
	Description string      `json:"description"`
	ReviewMode  string      `json:"review_mode"`
	CreatedBy   pgtype.UUID `json:"created_by"`
}

func (q *Queries) CreateAgent(ctx context.Context, arg CreateAgentParams) (Agent, error) {
	row := q.db.QueryRow(ctx, createAgent,
		arg.WorkspaceID,
		arg.Name,
		arg.Slug,
		arg.Description,
		arg.ReviewMode,
		arg.CreatedBy,
	)
	var i Agent
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Name,
		&i.Slug,
		&i.Description,
		&i.AvatarKey,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ReviewMode,
	)
	return i, err
}

const createAgentInvite = `-- name: CreateAgentInvite :one
insert into agent_invites (workspace_id, token_hash, project_ids, scopes, expires_at, created_by)
values ($1, $2, $3::uuid[],
        $4::text[], $5, $6)
returning id, workspace_id, token_hash, project_ids, scopes, expires_at, used_by, created_by, created_at
`

type CreateAgentInviteParams struct {
	WorkspaceID pgtype.UUID        `json:"workspace_id"`
	TokenHash   []byte             `json:"token_hash"`
	ProjectIds  []pgtype.UUID      `json:"project_ids"`
	Scopes      []string           `json:"scopes"`
	ExpiresAt   pgtype.Timestamptz `json:"expires_at"`
	CreatedBy   pgtype.UUID        `json:"created_by"`
}

func (q *Queries) CreateAgentInvite(ctx context.Context, arg CreateAgentInviteParams) (AgentInvite, error) {
	row := q.db.QueryRow(ctx, createAgentInvite,
		arg.WorkspaceID,
		arg.TokenHash,
		arg.ProjectIds,
		arg.Scopes,
		arg.ExpiresAt,
		arg.CreatedBy,
	)
	var i AgentInvite
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.TokenHash,
		&i.ProjectIds,
		&i.Scopes,
		&i.ExpiresAt,
		&i.UsedBy,
		&i.CreatedBy,
		&i.CreatedAt,
	)
	return i, err
}

const createMcpToken = `-- name: CreateMcpToken :one
insert into mcp_tokens (agent_id, token_hash, name, expires_at)
values ($1, $2, $3, $4)
returning id, agent_id, token_hash, name, last_used_at, expires_at, revoked_at, created_at
`

type CreateMcpTokenParams struct {
	AgentID   pgtype.UUID        `json:"agent_id"`
	TokenHash []byte             `json:"token_hash"`
	Name      string             `json:"name"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
}

func (q *Queries) CreateMcpToken(ctx context.Context, arg CreateMcpTokenParams) (McpToken, error) {
	row := q.db.QueryRow(ctx, createMcpToken,
		arg.AgentID,
		arg.TokenHash,
		arg.Name,
		arg.ExpiresAt,
	)
	var i McpToken
	err := row.Scan(
		&i.ID,
		&i.AgentID,
		&i.TokenHash,
		&i.Name,
		&i.LastUsedAt,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.CreatedAt,
	)
	return i, err
}

const deleteAgent = `-- name: DeleteAgent :exec
delete from agents where id = $1
`

func (q *Queries) DeleteAgent(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteAgent, id)
	return err
}

const deleteAgentGrant = `-- name: DeleteAgentGrant :exec
delete from agent_project_permissions
where agent_id = $1 and project_id = $2
`

type DeleteAgentGrantParams struct {
	AgentID   pgtype.UUID `json:"agent_id"`
	ProjectID pgtype.UUID `json:"project_id"`
}

func (q *Queries) DeleteAgentGrant(ctx context.Context, arg DeleteAgentGrantParams) error {
	_, err := q.db.Exec(ctx, deleteAgentGrant, arg.AgentID, arg.ProjectID)
	return err
}

const deleteAgentInvite = `-- name: DeleteAgentInvite :exec
delete from agent_invites where id = $1
`

func (q *Queries) DeleteAgentInvite(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteAgentInvite, id)
	return err
}

const getAgentByID = `-- name: GetAgentByID :one
select id, workspace_id, name, slug, description, avatar_key, created_by, created_at, updated_at, review_mode from agents where id = $1
`

func (q *Queries) GetAgentByID(ctx context.Context, id pgtype.UUID) (Agent, error) {
	row := q.db.QueryRow(ctx, getAgentByID, id)
	var i Agent
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Name,
		&i.Slug,
		&i.Description,
		&i.AvatarKey,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ReviewMode,
	)
	return i, err
}

const getAgentForUser = `-- name: GetAgentForUser :one
select a.id, a.workspace_id, a.name, a.slug, a.description, a.avatar_key, a.created_by, a.created_at, a.updated_at, a.review_mode from agents a
join workspace_members wm on wm.workspace_id = a.workspace_id and wm.user_id = $1
where a.id = $2
`

type GetAgentForUserParams struct {
	UserID pgtype.UUID `json:"user_id"`
	ID     pgtype.UUID `json:"id"`
}

// agent row only when the caller belongs to its workspace
func (q *Queries) GetAgentForUser(ctx context.Context, arg GetAgentForUserParams) (Agent, error) {
	row := q.db.QueryRow(ctx, getAgentForUser, arg.UserID, arg.ID)
	var i Agent
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Name,
		&i.Slug,
		&i.Description,
		&i.AvatarKey,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ReviewMode,
	)
	return i, err
}

const getAgentInviteByHash = `-- name: GetAgentInviteByHash :one
select id, workspace_id, token_hash, project_ids, scopes, expires_at, used_by, created_by, created_at from agent_invites
where token_hash = $1
  and used_by is null
  and expires_at > now()
`

func (q *Queries) GetAgentInviteByHash(ctx context.Context, tokenHash []byte) (AgentInvite, error) {
	row := q.db.QueryRow(ctx, getAgentInviteByHash, tokenHash)
	var i AgentInvite
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.TokenHash,
		&i.ProjectIds,
		&i.Scopes,
		&i.ExpiresAt,
		&i.UsedBy,
		&i.CreatedBy,
		&i.CreatedAt,
	)
	return i, err
}

const getTokenAgent = `-- name: GetTokenAgent :one
select t.id as token_id, a.id, a.workspace_id, a.name, a.slug, a.description, a.avatar_key, a.created_by, a.created_at, a.updated_at, a.review_mode from mcp_tokens t
join agents a on a.id = t.agent_id
where t.token_hash = $1
  and t.revoked_at is null
  and (t.expires_at is null or t.expires_at > now())
`

type GetTokenAgentRow struct {
	TokenID     pgtype.UUID        `json:"token_id"`
	ID          pgtype.UUID        `json:"id"`
	WorkspaceID pgtype.UUID        `json:"workspace_id"`
	Name        string             `json:"name"`
	Slug        string             `json:"slug"`
	Description string             `json:"description"`
	AvatarKey   pgtype.Text        `json:"avatar_key"`
	CreatedBy   pgtype.UUID        `json:"created_by"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
	ReviewMode  string             `json:"review_mode"`
}

// resolve a presented bearer token to its agent when usable
func (q *Queries) GetTokenAgent(ctx context.Context, tokenHash []byte) (GetTokenAgentRow, error) {
	row := q.db.QueryRow(ctx, getTokenAgent, tokenHash)
	var i GetTokenAgentRow
	err := row.Scan(
		&i.TokenID,
		&i.ID,
		&i.WorkspaceID,
		&i.Name,
		&i.Slug,
		&i.Description,
		&i.AvatarKey,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ReviewMode,
	)
	return i, err
}

const listAgentGrants = `-- name: ListAgentGrants :many
select g.agent_id, g.project_id, g.scopes, g.created_at, p.key as project_key, p.name as project_name
from agent_project_permissions g
join projects p on p.id = g.project_id
where g.agent_id = $1
order by p.name
`

type ListAgentGrantsRow struct {
	AgentID     pgtype.UUID        `json:"agent_id"`
	ProjectID   pgtype.UUID        `json:"project_id"`
	Scopes      []string           `json:"scopes"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	ProjectKey  string             `json:"project_key"`
	ProjectName string             `json:"project_name"`
}

func (q *Queries) ListAgentGrants(ctx context.Context, agentID pgtype.UUID) ([]ListAgentGrantsRow, error) {
	rows, err := q.db.Query(ctx, listAgentGrants, agentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAgentGrantsRow{}
	for rows.Next() {
		var i ListAgentGrantsRow
		if err := rows.Scan(
			&i.AgentID,
			&i.ProjectID,
			&i.Scopes,
			&i.CreatedAt,
			&i.ProjectKey,
			&i.ProjectName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAgentInvites = `-- name: ListAgentInvites :many
select i.id, i.workspace_id, i.token_hash, i.project_ids, i.scopes, i.expires_at, i.used_by, i.created_by, i.created_at, a.name as used_by_name from agent_invites i
left join agents a on a.id = i.used_by
where i.workspace_id = $1
order by i.created_at desc
`

type ListAgentInvitesRow struct {
	ID          pgtype.UUID        `json:"id"`
	WorkspaceID pgtype.UUID        `json:"workspace_id"`
	TokenHash   []byte             `json:"token_hash"`
	ProjectIds  []pgtype.UUID      `json:"project_ids"`
	Scopes      []string           `json:"scopes"`
	ExpiresAt   pgtype.Timestamptz `json:"expires_at"`
	UsedBy      pgtype.UUID        `json:"used_by"`
	CreatedBy   pgtype.UUID        `json:"created_by"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UsedByName  pgtype.Text        `json:"used_by_name"`
}

func (q *Queries) ListAgentInvites(ctx context.Context, workspaceID pgtype.UUID) ([]ListAgentInvitesRow, error) {
	rows, err := q.db.Query(ctx, listAgentInvites, workspaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAgentInvitesRow{}
	for rows.Next() {
		var i ListAgentInvitesRow
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.TokenHash,
			&i.ProjectIds,
			&i.Scopes,
			&i.ExpiresAt,
			&i.UsedBy,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UsedByName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAgentsForWorkspace = `-- name: ListAgentsForWorkspace :many
select a.id, a.workspace_id, a.name, a.slug, a.description, a.avatar_key, a.created_by, a.created_at, a.updated_at, a.review_mode, cast((
    select max(t.last_used_at) from mcp_tokens t where t.agent_id = a.id
) as timestamptz) as last_seen_at
from agents a
where a.workspace_id = $1
order by a.name
`

type ListAgentsForWorkspaceRow struct {
	ID          pgtype.UUID        `json:"id"`
	WorkspaceID pgtype.UUID        `json:"workspace_id"`
	Name        string             `json:"name"`
	Slug        string             `json:"slug"`
	Description string             `json:"description"`
	AvatarKey   pgtype.Text        `json:"avatar_key"`
	CreatedBy   pgtype.UUID        `json:"created_by"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
	ReviewMode  string             `json:"review_mode"`
	LastSeenAt  pgtype.Timestamptz `json:"last_seen_at"`
}

func (q *Queries) ListAgentsForWorkspace(ctx context.Context, workspaceID pgtype.UUID) ([]ListAgentsForWorkspaceRow, error) {
	rows, err := q.db.Query(ctx, listAgentsForWorkspace, workspaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAgentsForWorkspaceRow{}
	for rows.Next() {
		var i ListAgentsForWorkspaceRow
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.Name,
			&i.Slug,
			&i.Description,
			&i.AvatarKey,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ReviewMode,
			&i.LastSeenAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listGrantedProjects = `-- name: ListGrantedProjects :many
select p.id, p.workspace_id, p.key, p.name, p.description, p.icon, p.color, p.created_by, p.created_at, p.updated_at, p.statuses, p.local_path, p.brief_policy, p.avatar_key from agent_project_permissions g
join projects p on p.id = g.project_id
where g.agent_id = $1 and 'project:read' = any(g.scopes)
order by p.name
`

func (q *Queries) ListGrantedProjects(ctx context.Context, agentID pgtype.UUID) ([]Project, error) {
	rows, err := q.db.Query(ctx, listGrantedProjects, agentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Project{}
	for rows.Next() {
		var i Project
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.Key,
			&i.Name,
			&i.Description,
			&i.Icon,
			&i.Color,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Statuses,
			&i.LocalPath,
			&i.BriefPolicy,
			&i.AvatarKey,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMcpTokens = `-- name: ListMcpTokens :many
select id, agent_id, name, last_used_at, expires_at, revoked_at, created_at
from mcp_tokens
where agent_id = $1 and revoked_at is null
order by created_at desc
`

type ListMcpTokensRow struct {
	ID         pgtype.UUID        `json:"id"`
	AgentID    pgtype.UUID        `json:"agent_id"`
	Name       string             `json:"name"`
	LastUsedAt pgtype.Timestamptz `json:"last_used_at"`
	ExpiresAt  pgtype.Timestamptz `json:"expires_at"`
	RevokedAt  pgtype.Timestamptz `json:"revoked_at"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) ListMcpTokens(ctx context.Context, agentID pgtype.UUID) ([]ListMcpTokensRow, error) {
	rows, err := q.db.Query(ctx, listMcpTokens, agentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListMcpTokensRow{}
	for rows.Next() {
		var i ListMcpTokensRow
		if err := rows.Scan(
			&i.ID,
			&i.AgentID,
			&i.Name,
			&i.LastUsedAt,
			&i.ExpiresAt,
			&i.RevokedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProjectAgents = `-- name: ListProjectAgents :many
select a.id, a.workspace_id, a.name, a.slug, a.description, a.avatar_key, a.created_by, a.created_at, a.updated_at, a.review_mode, g.scopes as grant_scopes
from agents a
join agent_project_permissions g on g.agent_id = a.id
where g.project_id = $1
order by a.name
`

type ListProjectAgentsRow struct {
	ID          pgtype.UUID        `json:"id"`
	WorkspaceID pgtype.UUID        `json:"workspace_id"`
	Name        string             `json:"name"`
	Slug        string             `json:"slug"`
	Description string             `json:"description"`
	AvatarKey   pgtype.Text        `json:"avatar_key"`
	CreatedBy   pgtype.UUID        `json:"created_by"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
	ReviewMode  string             `json:"review_mode"`
	GrantScopes []string           `json:"grant_scopes"`
}

// agents holding a grant on a project; surfaced in the project's member list
func (q *Queries) ListProjectAgents(ctx context.Context, projectID pgtype.UUID) ([]ListProjectAgentsRow, error) {
	rows, err := q.db.Query(ctx, listProjectAgents, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListProjectAgentsRow{}
	for rows.Next() {
		var i ListProjectAgentsRow
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.Name,
			&i.Slug,
			&i.Description,
			&i.AvatarKey,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ReviewMode,
			&i.GrantScopes,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWorkspaceProjectIDs = `-- name: ListWorkspaceProjectIDs :many
select id from projects where workspace_id = $1
`

func (q *Queries) ListWorkspaceProjectIDs(ctx context.Context, workspaceID pgtype.UUID) ([]pgtype.UUID, error) {
	rows, err := q.db.Query(ctx, listWorkspaceProjectIDs, workspaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []pgtype.UUID{}
	for rows.Next() {
		var id pgtype.UUID
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const projectInAgentWorkspace = `-- name: ProjectInAgentWorkspace :one
select exists (
    select 1 from projects p join agents a on a.workspace_id = p.workspace_id
    where p.id = $1 and a.id = $2
)
`

type ProjectInAgentWorkspaceParams struct {
	ProjectID pgtype.UUID `json:"project_id"`
	AgentID   pgtype.UUID `json:"agent_id"`
}

// project must live in the agent's own workspace for a grant to be valid
func (q *Queries) ProjectInAgentWorkspace(ctx context.Context, arg ProjectInAgentWorkspaceParams) (bool, error) {
	row := q.db.QueryRow(ctx, projectInAgentWorkspace, arg.ProjectID, arg.AgentID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const redeemAgentInvite = `-- name: RedeemAgentInvite :one
update agent_invites set used_by = $1
where id = $2 and used_by is null
returning id, workspace_id, token_hash, project_ids, scopes, expires_at, used_by, created_by, created_at
`

type RedeemAgentInviteParams struct {
	UsedBy pgtype.UUID `json:"used_by"`
	ID     pgtype.UUID `json:"id"`
}

func (q *Queries) RedeemAgentInvite(ctx context.Context, arg RedeemAgentInviteParams) (AgentInvite, error) {
	row := q.db.QueryRow(ctx, redeemAgentInvite, arg.UsedBy, arg.ID)
	var i AgentInvite
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.TokenHash,
		&i.ProjectIds,
		&i.Scopes,
		&i.ExpiresAt,
		&i.UsedBy,
		&i.CreatedBy,
		&i.CreatedAt,
	)
	return i, err
}

const revokeAgentTokens = `-- name: RevokeAgentTokens :exec
update mcp_tokens set revoked_at = now()
where agent_id = $1 and revoked_at is null
`

func (q *Queries) RevokeAgentTokens(ctx context.Context, agentID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, revokeAgentTokens, agentID)
	return err
}

const revokeMcpToken = `-- name: RevokeMcpToken :exec
update mcp_tokens set revoked_at = now()
where id = $1 and agent_id = $2 and revoked_at is null
`

type RevokeMcpTokenParams struct {
	ID      pgtype.UUID `json:"id"`
	AgentID pgtype.UUID `json:"agent_id"`
}

func (q *Queries) RevokeMcpToken(ctx context.Context, arg RevokeMcpTokenParams) error {
	_, err := q.db.Exec(ctx, revokeMcpToken, arg.ID, arg.AgentID)
	return err
}

const touchMcpToken = `-- name: TouchMcpToken :exec
update mcp_tokens set last_used_at = now() where id = $1
`

func (q *Queries) TouchMcpToken(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, touchMcpToken, id)
	return err
}

const updateAgent = `-- name: UpdateAgent :one
update agents set
    name = coalesce($1, name),
    description = coalesce($2, description),
    review_mode = coalesce($3, review_mode),
    updated_at = now()
where id = $4
returning id, workspace_id, name, slug, description, avatar_key, created_by, created_at, updated_at, review_mode
`

type UpdateAgentParams struct {
	Name        pgtype.Text `json:"name"`
	Description pgtype.Text `json:"description"`
	ReviewMode  pgtype.Text `json:"review_mode"`
	ID          pgtype.UUID `json:"id"`
}

func (q *Queries) UpdateAgent(ctx context.Context, arg UpdateAgentParams) (Agent, error) {
	row := q.db.QueryRow(ctx, updateAgent,
		arg.Name,
		arg.Description,
		arg.ReviewMode,
		arg.ID,
	)
	var i Agent
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Name,
		&i.Slug,
		&i.Description,
		&i.AvatarKey,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ReviewMode,
	)
	return i, err
}

const updateAgentAvatar = `-- name: UpdateAgentAvatar :one
update agents set avatar_key = $1, updated_at = now() where id = $2
returning id, workspace_id, name, slug, description, avatar_key, created_by, created_at, updated_at, review_mode
`

type UpdateAgentAvatarParams struct {
	AvatarKey pgtype.Text `json:"avatar_key"`
	ID        pgtype.UUID `json:"id"`
}

func (q *Queries) UpdateAgentAvatar(ctx context.Context, arg UpdateAgentAvatarParams) (Agent, error) {
	row := q.db.QueryRow(ctx, updateAgentAvatar, arg.AvatarKey, arg.ID)
	var i Agent
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Name,
		&i.Slug,
		&i.Description,
		&i.AvatarKey,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ReviewMode,
	)
	return i, err
}

const upsertAgentGrant = `-- name: UpsertAgentGrant :one
with g as (
    insert into agent_project_permissions (agent_id, project_id, scopes)
    values ($1, $2, $3::text[])
    on conflict (agent_id, project_id) do update set scopes = excluded.scopes
    returning agent_id, project_id, scopes, created_at
)
select g.agent_id, g.project_id, g.scopes, g.created_at, p.key as project_key, p.name as project_name
from g join projects p on p.id = g.project_id
`

type UpsertAgentGrantParams struct {
	AgentID   pgtype.UUID `json:"agent_id"`
	ProjectID pgtype.UUID `json:"project_id"`
	Scopes    []string    `json:"scopes"`
}

type UpsertAgentGrantRow struct {
	AgentID     pgtype.UUID        `json:"agent_id"`
	ProjectID   pgtype.UUID        `json:"project_id"`
	Scopes      []string           `json:"scopes"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	ProjectKey  string             `json:"project_key"`
	ProjectName string             `json:"project_name"`
}

func (q *Queries) UpsertAgentGrant(ctx context.Context, arg UpsertAgentGrantParams) (UpsertAgentGrantRow, error) {
	row := q.db.QueryRow(ctx, upsertAgentGrant, arg.AgentID, arg.ProjectID, arg.Scopes)
	var i UpsertAgentGrantRow
	err := row.Scan(
		&i.AgentID,
		&i.ProjectID,
		&i.Scopes,
		&i.CreatedAt,
		&i.ProjectKey,
		&i.ProjectName,
	)
	return i, err
}
