// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: attachments.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countMessageAttachments = `-- name: CountMessageAttachments :one
select count(*) from message_attachments where message_id = $1
`

func (q *Queries) CountMessageAttachments(ctx context.Context, messageID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countMessageAttachments, messageID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countUsableAttachmentsInProject = `-- name: CountUsableAttachmentsInProject :one
select count(*) from attachments
where project_id = $1 and status = 'ready'
  and id = any($2::uuid[])
`

type CountUsableAttachmentsInProjectParams struct {
	ProjectID pgtype.UUID   `json:"project_id"`
	Ids       []pgtype.UUID `json:"ids"`
}

// how many of the given ids are ready attachments inside this project
func (q *Queries) CountUsableAttachmentsInProject(ctx context.Context, arg CountUsableAttachmentsInProjectParams) (int64, error) {
	row := q.db.QueryRow(ctx, countUsableAttachmentsInProject, arg.ProjectID, arg.Ids)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createAgentAttachment = `-- name: CreateAgentAttachment :one
insert into attachments (id, project_id, uploader_agent_id, storage_key, filename, content_type, size_bytes)
values ($1, $2, $3, $4,
        $5, $6, $7)
returning id, project_id, uploader_id, storage_key, filename, content_type, size_bytes, status, created_at, uploader_agent_id
`

type CreateAgentAttachmentParams struct {
	ID              pgtype.UUID `json:"id"`
	ProjectID       pgtype.UUID `json:"project_id"`
	UploaderAgentID pgtype.UUID `json:"uploader_agent_id"`
	StorageKey      string      `json:"storage_key"`
	Filename        string      `json:"filename"`
	ContentType     string      `json:"content_type"`
	SizeBytes       int64       `json:"size_bytes"`
}

func (q *Queries) CreateAgentAttachment(ctx context.Context, arg CreateAgentAttachmentParams) (Attachment, error) {
	row := q.db.QueryRow(ctx, createAgentAttachment,
		arg.ID,
		arg.ProjectID,
		arg.UploaderAgentID,
		arg.StorageKey,
		arg.Filename,
		arg.ContentType,
		arg.SizeBytes,
	)
	var i Attachment
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.UploaderID,
		&i.StorageKey,
		&i.Filename,
		&i.ContentType,
		&i.SizeBytes,
		&i.Status,
		&i.CreatedAt,
		&i.UploaderAgentID,
	)
	return i, err
}

const createAttachment = `-- name: CreateAttachment :one
insert into attachments (id, project_id, uploader_id, storage_key, filename, content_type, size_bytes)
values ($1, $2, $3, $4,
        $5, $6, $7)
returning id, project_id, uploader_id, storage_key, filename, content_type, size_bytes, status, created_at, uploader_agent_id
`

type CreateAttachmentParams struct {
	ID          pgtype.UUID `json:"id"`
	ProjectID   pgtype.UUID `json:"project_id"`
	UploaderID  pgtype.UUID `json:"uploader_id"`
	StorageKey  string      `json:"storage_key"`
	Filename    string      `json:"filename"`
	ContentType string      `json:"content_type"`
	SizeBytes   int64       `json:"size_bytes"`
}

func (q *Queries) CreateAttachment(ctx context.Context, arg CreateAttachmentParams) (Attachment, error) {
	row := q.db.QueryRow(ctx, createAttachment,
		arg.ID,
		arg.ProjectID,
		arg.UploaderID,
		arg.StorageKey,
		arg.Filename,
		arg.ContentType,
		arg.SizeBytes,
	)
	var i Attachment
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.UploaderID,
		&i.StorageKey,
		&i.Filename,
		&i.ContentType,
		&i.SizeBytes,
		&i.Status,
		&i.CreatedAt,
		&i.UploaderAgentID,
	)
	return i, err
}

const deleteAttachment = `-- name: DeleteAttachment :exec
delete from attachments where id = $1
`

func (q *Queries) DeleteAttachment(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteAttachment, id)
	return err
}

const getAttachmentInProjectForUser = `-- name: GetAttachmentInProjectForUser :one
select a.id, a.project_id, a.uploader_id, a.storage_key, a.filename, a.content_type, a.size_bytes, a.status, a.created_at, a.uploader_agent_id from attachments a
join projects p on p.id = a.project_id
join workspace_members wm on wm.workspace_id = p.workspace_id and wm.user_id = $1
where a.id = $2 and a.project_id = $3
`

type GetAttachmentInProjectForUserParams struct {
	UserID    pgtype.UUID `json:"user_id"`
	ID        pgtype.UUID `json:"id"`
	ProjectID pgtype.UUID `json:"project_id"`
}

// one row only when the attachment exists, sits in the given project, and
// the caller belongs to the project's workspace
func (q *Queries) GetAttachmentInProjectForUser(ctx context.Context, arg GetAttachmentInProjectForUserParams) (Attachment, error) {
	row := q.db.QueryRow(ctx, getAttachmentInProjectForUser, arg.UserID, arg.ID, arg.ProjectID)
	var i Attachment
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.UploaderID,
		&i.StorageKey,
		&i.Filename,
		&i.ContentType,
		&i.SizeBytes,
		&i.Status,
		&i.CreatedAt,
		&i.UploaderAgentID,
	)
	return i, err
}

const linkMessageAttachment = `-- name: LinkMessageAttachment :exec
insert into message_attachments (message_id, attachment_id, position)
values ($1, $2, $3)
`

type LinkMessageAttachmentParams struct {
	MessageID    pgtype.UUID `json:"message_id"`
	AttachmentID pgtype.UUID `json:"attachment_id"`
	Position     int32       `json:"position"`
}

func (q *Queries) LinkMessageAttachment(ctx context.Context, arg LinkMessageAttachmentParams) error {
	_, err := q.db.Exec(ctx, linkMessageAttachment, arg.MessageID, arg.AttachmentID, arg.Position)
	return err
}

const listAttachmentsForMessages = `-- name: ListAttachmentsForMessages :many
select a.id, a.project_id, a.uploader_id, a.storage_key, a.filename, a.content_type, a.size_bytes, a.status, a.created_at, a.uploader_agent_id, ma.message_id
from message_attachments ma
join attachments a on a.id = ma.attachment_id
where ma.message_id = any($1::uuid[])
order by ma.position
`

type ListAttachmentsForMessagesRow struct {
	ID              pgtype.UUID        `json:"id"`
	ProjectID       pgtype.UUID        `json:"project_id"`
	UploaderID      pgtype.UUID        `json:"uploader_id"`
	StorageKey      string             `json:"storage_key"`
	Filename        string             `json:"filename"`
	ContentType     string             `json:"content_type"`
	SizeBytes       int64              `json:"size_bytes"`
	Status          string             `json:"status"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UploaderAgentID pgtype.UUID        `json:"uploader_agent_id"`
	MessageID       pgtype.UUID        `json:"message_id"`
}

func (q *Queries) ListAttachmentsForMessages(ctx context.Context, ids []pgtype.UUID) ([]ListAttachmentsForMessagesRow, error) {
	rows, err := q.db.Query(ctx, listAttachmentsForMessages, ids)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAttachmentsForMessagesRow{}
	for rows.Next() {
		var i ListAttachmentsForMessagesRow
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.UploaderID,
			&i.StorageKey,
			&i.Filename,
			&i.ContentType,
			&i.SizeBytes,
			&i.Status,
			&i.CreatedAt,
			&i.UploaderAgentID,
			&i.MessageID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOrphanAttachments = `-- name: ListOrphanAttachments :many
select a.id, a.storage_key from attachments a
where a.created_at < now() - interval '24 hours'
  and not exists (select 1 from message_attachments ma where ma.attachment_id = a.id)
`

type ListOrphanAttachmentsRow struct {
	ID         pgtype.UUID `json:"id"`
	StorageKey string      `json:"storage_key"`
}

// staged uploads that never linked to a message — abandoned drafts
func (q *Queries) ListOrphanAttachments(ctx context.Context) ([]ListOrphanAttachmentsRow, error) {
	rows, err := q.db.Query(ctx, listOrphanAttachments)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListOrphanAttachmentsRow{}
	for rows.Next() {
		var i ListOrphanAttachmentsRow
		if err := rows.Scan(&i.ID, &i.StorageKey); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markAttachmentReady = `-- name: MarkAttachmentReady :one
update attachments set status = 'ready' where id = $1
returning id, project_id, uploader_id, storage_key, filename, content_type, size_bytes, status, created_at, uploader_agent_id
`

func (q *Queries) MarkAttachmentReady(ctx context.Context, id pgtype.UUID) (Attachment, error) {
	row := q.db.QueryRow(ctx, markAttachmentReady, id)
	var i Attachment
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.UploaderID,
		&i.StorageKey,
		&i.Filename,
		&i.ContentType,
		&i.SizeBytes,
		&i.Status,
		&i.CreatedAt,
		&i.UploaderAgentID,
	)
	return i, err
}
