// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: auth.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createPasswordResetToken = `-- name: CreatePasswordResetToken :exec
insert into password_reset_tokens (user_id, token_hash, expires_at)
values ($1, $2, now() + interval '1 hour')
`

type CreatePasswordResetTokenParams struct {
	UserID    pgtype.UUID `json:"user_id"`
	TokenHash string      `json:"token_hash"`
}

func (q *Queries) CreatePasswordResetToken(ctx context.Context, arg CreatePasswordResetTokenParams) error {
	_, err := q.db.Exec(ctx, createPasswordResetToken, arg.UserID, arg.TokenHash)
	return err
}

const deleteAllSessions = `-- name: DeleteAllSessions :exec
delete from sessions where user_id = $1
`

func (q *Queries) DeleteAllSessions(ctx context.Context, userID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteAllSessions, userID)
	return err
}

const getPasswordResetUser = `-- name: GetPasswordResetUser :one
select t.id as token_id, u.id, u.email, u.name
from password_reset_tokens t
join users u on u.id = t.user_id
where t.token_hash = $1 and t.used_at is null and t.expires_at > now()
`

type GetPasswordResetUserRow struct {
	TokenID pgtype.UUID `json:"token_id"`
	ID      pgtype.UUID `json:"id"`
	Email   string      `json:"email"`
	Name    string      `json:"name"`
}

func (q *Queries) GetPasswordResetUser(ctx context.Context, tokenHash string) (GetPasswordResetUserRow, error) {
	row := q.db.QueryRow(ctx, getPasswordResetUser, tokenHash)
	var i GetPasswordResetUserRow
	err := row.Scan(
		&i.TokenID,
		&i.ID,
		&i.Email,
		&i.Name,
	)
	return i, err
}

const rateLimitHit = `-- name: RateLimitHit :one
insert into rate_limits (key, window_start, count)
values ($1, now(), 1)
on conflict (key) do update
set count = case
    when rate_limits.window_start + make_interval(secs => $2::int) < now()
        then 1
    else rate_limits.count + 1
  end,
  window_start = case
    when rate_limits.window_start + make_interval(secs => $2::int) < now()
        then now()
    else rate_limits.window_start
  end
returning count
`

type RateLimitHitParams struct {
	Key        string `json:"key"`
	WindowSecs int32  `json:"window_secs"`
}

func (q *Queries) RateLimitHit(ctx context.Context, arg RateLimitHitParams) (int32, error) {
	row := q.db.QueryRow(ctx, rateLimitHit, arg.Key, arg.WindowSecs)
	var count int32
	err := row.Scan(&count)
	return count, err
}

const updateUserPassword = `-- name: UpdateUserPassword :exec
update users set password_hash = $2, updated_at = now() where id = $1
`

type UpdateUserPasswordParams struct {
	ID           pgtype.UUID `json:"id"`
	PasswordHash string      `json:"password_hash"`
}

func (q *Queries) UpdateUserPassword(ctx context.Context, arg UpdateUserPasswordParams) error {
	_, err := q.db.Exec(ctx, updateUserPassword, arg.ID, arg.PasswordHash)
	return err
}

const usePasswordResetToken = `-- name: UsePasswordResetToken :exec
update password_reset_tokens set used_at = now() where id = $1
`

func (q *Queries) UsePasswordResetToken(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, usePasswordResetToken, id)
	return err
}
