// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: briefs.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const briefSetConversation = `-- name: BriefSetConversation :exec
update briefs set conversation_id = $1 where id = $2
`

type BriefSetConversationParams struct {
	ConversationID pgtype.UUID `json:"conversation_id"`
	ID             pgtype.UUID `json:"id"`
}

func (q *Queries) BriefSetConversation(ctx context.Context, arg BriefSetConversationParams) error {
	_, err := q.db.Exec(ctx, briefSetConversation, arg.ConversationID, arg.ID)
	return err
}

const createBrief = `-- name: CreateBrief :one
insert into briefs (project_id, issue_id, title, summary, scene,
                    created_by_user, created_by_agent)
values ($1, $2, $3,
        $4, $5,
        $6, $7)
returning id, project_id, issue_id, conversation_id, title, summary, scene, status, created_by_user, created_by_agent, created_at, updated_at, creator_name_snapshot
`

type CreateBriefParams struct {
	ProjectID      pgtype.UUID `json:"project_id"`
	IssueID        pgtype.UUID `json:"issue_id"`
	Title          string      `json:"title"`
	Summary        string      `json:"summary"`
	Scene          []byte      `json:"scene"`
	CreatedByUser  pgtype.UUID `json:"created_by_user"`
	CreatedByAgent pgtype.UUID `json:"created_by_agent"`
}

func (q *Queries) CreateBrief(ctx context.Context, arg CreateBriefParams) (Brief, error) {
	row := q.db.QueryRow(ctx, createBrief,
		arg.ProjectID,
		arg.IssueID,
		arg.Title,
		arg.Summary,
		arg.Scene,
		arg.CreatedByUser,
		arg.CreatedByAgent,
	)
	var i Brief
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.IssueID,
		&i.ConversationID,
		&i.Title,
		&i.Summary,
		&i.Scene,
		&i.Status,
		&i.CreatedByUser,
		&i.CreatedByAgent,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CreatorNameSnapshot,
	)
	return i, err
}

const createBriefConversation = `-- name: CreateBriefConversation :one
insert into conversations (project_id, kind, brief_id)
values ($1, 'brief', $2)
returning id, project_id, kind, issue_id, created_at, brief_id, parent_message_id, title, created_by_user, created_by_agent, creator_name_snapshot
`

type CreateBriefConversationParams struct {
	ProjectID pgtype.UUID `json:"project_id"`
	BriefID   pgtype.UUID `json:"brief_id"`
}

func (q *Queries) CreateBriefConversation(ctx context.Context, arg CreateBriefConversationParams) (Conversation, error) {
	row := q.db.QueryRow(ctx, createBriefConversation, arg.ProjectID, arg.BriefID)
	var i Conversation
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Kind,
		&i.IssueID,
		&i.CreatedAt,
		&i.BriefID,
		&i.ParentMessageID,
		&i.Title,
		&i.CreatedByUser,
		&i.CreatedByAgent,
		&i.CreatorNameSnapshot,
	)
	return i, err
}

const getBrief = `-- name: GetBrief :one
select b.id, b.project_id, b.issue_id, b.conversation_id, b.title, b.summary, b.scene, b.status, b.created_by_user, b.created_by_agent, b.created_at, b.updated_at, b.creator_name_snapshot,
       coalesce(u.name, a.name, nullif(b.creator_name_snapshot, ''), '') as author_name,
       coalesce(u.id is not null, false) as author_is_user,
       coalesce(p.key, ''::text) as issue_project_key,
       i.number as issue_number
from briefs b
left join users u on u.id = b.created_by_user
left join agents a on a.id = b.created_by_agent
left join issues i on i.id = b.issue_id
left join projects p on p.id = i.project_id
where b.id = $1
`

type GetBriefRow struct {
	ID                  pgtype.UUID        `json:"id"`
	ProjectID           pgtype.UUID        `json:"project_id"`
	IssueID             pgtype.UUID        `json:"issue_id"`
	ConversationID      pgtype.UUID        `json:"conversation_id"`
	Title               string             `json:"title"`
	Summary             string             `json:"summary"`
	Scene               []byte             `json:"scene"`
	Status              string             `json:"status"`
	CreatedByUser       pgtype.UUID        `json:"created_by_user"`
	CreatedByAgent      pgtype.UUID        `json:"created_by_agent"`
	CreatedAt           pgtype.Timestamptz `json:"created_at"`
	UpdatedAt           pgtype.Timestamptz `json:"updated_at"`
	CreatorNameSnapshot string             `json:"creator_name_snapshot"`
	AuthorName          string             `json:"author_name"`
	AuthorIsUser        interface{}        `json:"author_is_user"`
	IssueProjectKey     string             `json:"issue_project_key"`
	IssueNumber         pgtype.Int4        `json:"issue_number"`
}

func (q *Queries) GetBrief(ctx context.Context, id pgtype.UUID) (GetBriefRow, error) {
	row := q.db.QueryRow(ctx, getBrief, id)
	var i GetBriefRow
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.IssueID,
		&i.ConversationID,
		&i.Title,
		&i.Summary,
		&i.Scene,
		&i.Status,
		&i.CreatedByUser,
		&i.CreatedByAgent,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CreatorNameSnapshot,
		&i.AuthorName,
		&i.AuthorIsUser,
		&i.IssueProjectKey,
		&i.IssueNumber,
	)
	return i, err
}

const listBriefs = `-- name: ListBriefs :many
select b.id, b.project_id, b.issue_id, b.conversation_id, b.title, b.summary, b.scene, b.status, b.created_by_user, b.created_by_agent, b.created_at, b.updated_at, b.creator_name_snapshot,
       coalesce(u.name, a.name, nullif(b.creator_name_snapshot, ''), '') as author_name,
       coalesce(p.key, ''::text) as issue_project_key,
       i.number as issue_number
from briefs b
left join users u on u.id = b.created_by_user
left join agents a on a.id = b.created_by_agent
left join issues i on i.id = b.issue_id
left join projects p on p.id = i.project_id
where b.project_id = $1
  and ($2::uuid is null or b.issue_id = $2)
order by b.created_at desc
`

type ListBriefsParams struct {
	ProjectID pgtype.UUID `json:"project_id"`
	IssueID   pgtype.UUID `json:"issue_id"`
}

type ListBriefsRow struct {
	ID                  pgtype.UUID        `json:"id"`
	ProjectID           pgtype.UUID        `json:"project_id"`
	IssueID             pgtype.UUID        `json:"issue_id"`
	ConversationID      pgtype.UUID        `json:"conversation_id"`
	Title               string             `json:"title"`
	Summary             string             `json:"summary"`
	Scene               []byte             `json:"scene"`
	Status              string             `json:"status"`
	CreatedByUser       pgtype.UUID        `json:"created_by_user"`
	CreatedByAgent      pgtype.UUID        `json:"created_by_agent"`
	CreatedAt           pgtype.Timestamptz `json:"created_at"`
	UpdatedAt           pgtype.Timestamptz `json:"updated_at"`
	CreatorNameSnapshot string             `json:"creator_name_snapshot"`
	AuthorName          string             `json:"author_name"`
	IssueProjectKey     string             `json:"issue_project_key"`
	IssueNumber         pgtype.Int4        `json:"issue_number"`
}

func (q *Queries) ListBriefs(ctx context.Context, arg ListBriefsParams) ([]ListBriefsRow, error) {
	rows, err := q.db.Query(ctx, listBriefs, arg.ProjectID, arg.IssueID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListBriefsRow{}
	for rows.Next() {
		var i ListBriefsRow
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.IssueID,
			&i.ConversationID,
			&i.Title,
			&i.Summary,
			&i.Scene,
			&i.Status,
			&i.CreatedByUser,
			&i.CreatedByAgent,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CreatorNameSnapshot,
			&i.AuthorName,
			&i.IssueProjectKey,
			&i.IssueNumber,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setBriefPolicy = `-- name: SetBriefPolicy :one
update projects set brief_policy = $1
where id = $2
returning brief_policy
`

type SetBriefPolicyParams struct {
	Policy    string      `json:"policy"`
	ProjectID pgtype.UUID `json:"project_id"`
}

func (q *Queries) SetBriefPolicy(ctx context.Context, arg SetBriefPolicyParams) (string, error) {
	row := q.db.QueryRow(ctx, setBriefPolicy, arg.Policy, arg.ProjectID)
	var brief_policy string
	err := row.Scan(&brief_policy)
	return brief_policy, err
}

const updateBrief = `-- name: UpdateBrief :one
update briefs set
  title   = coalesce($1, title),
  summary = coalesce($2, summary),
  scene   = coalesce($3, scene),
  status  = coalesce($4, status),
  updated_at = now()
where id = $5
returning id, project_id, issue_id, conversation_id, title, summary, scene, status, created_by_user, created_by_agent, created_at, updated_at, creator_name_snapshot
`

type UpdateBriefParams struct {
	Title   pgtype.Text `json:"title"`
	Summary pgtype.Text `json:"summary"`
	Scene   []byte      `json:"scene"`
	Status  pgtype.Text `json:"status"`
	ID      pgtype.UUID `json:"id"`
}

func (q *Queries) UpdateBrief(ctx context.Context, arg UpdateBriefParams) (Brief, error) {
	row := q.db.QueryRow(ctx, updateBrief,
		arg.Title,
		arg.Summary,
		arg.Scene,
		arg.Status,
		arg.ID,
	)
	var i Brief
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.IssueID,
		&i.ConversationID,
		&i.Title,
		&i.Summary,
		&i.Scene,
		&i.Status,
		&i.CreatedByUser,
		&i.CreatedByAgent,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CreatorNameSnapshot,
	)
	return i, err
}
