// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: conversations.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createMessage = `-- name: CreateMessage :one
insert into messages (conversation_id, author_user_id, body)
values ($1, $2, $3)
returning id
`

type CreateMessageParams struct {
	ConversationID pgtype.UUID `json:"conversation_id"`
	AuthorUserID   pgtype.UUID `json:"author_user_id"`
	Body           string      `json:"body"`
}

func (q *Queries) CreateMessage(ctx context.Context, arg CreateMessageParams) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, createMessage, arg.ConversationID, arg.AuthorUserID, arg.Body)
	var id pgtype.UUID
	err := row.Scan(&id)
	return id, err
}

const createProjectConversation = `-- name: CreateProjectConversation :one
insert into conversations (project_id, kind)
values ($1, 'project')
on conflict do nothing
returning id, project_id, kind, issue_id, created_at
`

func (q *Queries) CreateProjectConversation(ctx context.Context, projectID pgtype.UUID) (Conversation, error) {
	row := q.db.QueryRow(ctx, createProjectConversation, projectID)
	var i Conversation
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Kind,
		&i.IssueID,
		&i.CreatedAt,
	)
	return i, err
}

const getConversationByID = `-- name: GetConversationByID :one
select id, project_id, kind, issue_id, created_at
from conversations
where id = $1
`

func (q *Queries) GetConversationByID(ctx context.Context, id pgtype.UUID) (Conversation, error) {
	row := q.db.QueryRow(ctx, getConversationByID, id)
	var i Conversation
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Kind,
		&i.IssueID,
		&i.CreatedAt,
	)
	return i, err
}

const getConversationForUser = `-- name: GetConversationForUser :one
select c.id, c.project_id, c.kind, c.issue_id, c.created_at
from conversations c
join projects p on p.id = c.project_id
join workspace_members wm on wm.workspace_id = p.workspace_id
where c.id = $1 and wm.user_id = $2
`

type GetConversationForUserParams struct {
	ID     pgtype.UUID `json:"id"`
	UserID pgtype.UUID `json:"user_id"`
}

// resolves the conversation only when the user belongs to its workspace
func (q *Queries) GetConversationForUser(ctx context.Context, arg GetConversationForUserParams) (Conversation, error) {
	row := q.db.QueryRow(ctx, getConversationForUser, arg.ID, arg.UserID)
	var i Conversation
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Kind,
		&i.IssueID,
		&i.CreatedAt,
	)
	return i, err
}

const getMessageByID = `-- name: GetMessageByID :one
select m.id, m.conversation_id, m.body, m.created_at, m.edited_at,
       m.author_user_id, m.author_agent_id,
       coalesce(u.name, a.name, '') as author_name,
       coalesce(u.avatar_key, a.avatar_key) as author_avatar
from messages m
left join users u on u.id = m.author_user_id
left join agents a on a.id = m.author_agent_id
where m.id = $1
`

type GetMessageByIDRow struct {
	ID             pgtype.UUID        `json:"id"`
	ConversationID pgtype.UUID        `json:"conversation_id"`
	Body           string             `json:"body"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	EditedAt       pgtype.Timestamptz `json:"edited_at"`
	AuthorUserID   pgtype.UUID        `json:"author_user_id"`
	AuthorAgentID  pgtype.UUID        `json:"author_agent_id"`
	AuthorName     string             `json:"author_name"`
	AuthorAvatar   pgtype.Text        `json:"author_avatar"`
}

func (q *Queries) GetMessageByID(ctx context.Context, id pgtype.UUID) (GetMessageByIDRow, error) {
	row := q.db.QueryRow(ctx, getMessageByID, id)
	var i GetMessageByIDRow
	err := row.Scan(
		&i.ID,
		&i.ConversationID,
		&i.Body,
		&i.CreatedAt,
		&i.EditedAt,
		&i.AuthorUserID,
		&i.AuthorAgentID,
		&i.AuthorName,
		&i.AuthorAvatar,
	)
	return i, err
}

const getMessageForUser = `-- name: GetMessageForUser :one
select m.id
from messages m
join conversations c on c.id = m.conversation_id
join projects p on p.id = c.project_id
join workspace_members wm on wm.workspace_id = p.workspace_id
where m.id = $1 and wm.user_id = $2
`

type GetMessageForUserParams struct {
	ID     pgtype.UUID `json:"id"`
	UserID pgtype.UUID `json:"user_id"`
}

// message id only when the user may see its workspace
func (q *Queries) GetMessageForUser(ctx context.Context, arg GetMessageForUserParams) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, getMessageForUser, arg.ID, arg.UserID)
	var id pgtype.UUID
	err := row.Scan(&id)
	return id, err
}

const getProjectConversation = `-- name: GetProjectConversation :one
select id, project_id, kind, issue_id, created_at
from conversations
where project_id = $1 and kind = 'project'
`

func (q *Queries) GetProjectConversation(ctx context.Context, projectID pgtype.UUID) (Conversation, error) {
	row := q.db.QueryRow(ctx, getProjectConversation, projectID)
	var i Conversation
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Kind,
		&i.IssueID,
		&i.CreatedAt,
	)
	return i, err
}

const getProjectForUser = `-- name: GetProjectForUser :one
select p.id, p.workspace_id, p.key, p.name, p.description, p.icon, p.color, p.created_at
from projects p
join workspace_members wm on wm.workspace_id = p.workspace_id
where p.id = $1 and wm.user_id = $2
`

type GetProjectForUserParams struct {
	ID     pgtype.UUID `json:"id"`
	UserID pgtype.UUID `json:"user_id"`
}

type GetProjectForUserRow struct {
	ID          pgtype.UUID        `json:"id"`
	WorkspaceID pgtype.UUID        `json:"workspace_id"`
	Key         string             `json:"key"`
	Name        string             `json:"name"`
	Description string             `json:"description"`
	Icon        pgtype.Text        `json:"icon"`
	Color       pgtype.Text        `json:"color"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

// project row only when the caller is a member of its workspace
func (q *Queries) GetProjectForUser(ctx context.Context, arg GetProjectForUserParams) (GetProjectForUserRow, error) {
	row := q.db.QueryRow(ctx, getProjectForUser, arg.ID, arg.UserID)
	var i GetProjectForUserRow
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Key,
		&i.Name,
		&i.Description,
		&i.Icon,
		&i.Color,
		&i.CreatedAt,
	)
	return i, err
}

const listMessages = `-- name: ListMessages :many
select m.id, m.conversation_id, m.body, m.created_at, m.edited_at,
       m.author_user_id, m.author_agent_id,
       coalesce(u.name, a.name, '') as author_name,
       coalesce(u.avatar_key, a.avatar_key) as author_avatar
from messages m
left join users u on u.id = m.author_user_id
left join agents a on a.id = m.author_agent_id
where m.conversation_id = $1
  and m.deleted_at is null
  and ($2::uuid is null or
       (m.created_at, m.id) < (select m2.created_at, m2.id from messages m2 where m2.id = $2::uuid))
order by m.created_at desc, m.id desc
limit $3::int
`

type ListMessagesParams struct {
	ConversationID pgtype.UUID `json:"conversation_id"`
	Before         pgtype.UUID `json:"before"`
	Lim            int32       `json:"lim"`
}

type ListMessagesRow struct {
	ID             pgtype.UUID        `json:"id"`
	ConversationID pgtype.UUID        `json:"conversation_id"`
	Body           string             `json:"body"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	EditedAt       pgtype.Timestamptz `json:"edited_at"`
	AuthorUserID   pgtype.UUID        `json:"author_user_id"`
	AuthorAgentID  pgtype.UUID        `json:"author_agent_id"`
	AuthorName     string             `json:"author_name"`
	AuthorAvatar   pgtype.Text        `json:"author_avatar"`
}

// newest-first page; $2 is an optional "older than message id" cursor
func (q *Queries) ListMessages(ctx context.Context, arg ListMessagesParams) ([]ListMessagesRow, error) {
	rows, err := q.db.Query(ctx, listMessages, arg.ConversationID, arg.Before, arg.Lim)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListMessagesRow{}
	for rows.Next() {
		var i ListMessagesRow
		if err := rows.Scan(
			&i.ID,
			&i.ConversationID,
			&i.Body,
			&i.CreatedAt,
			&i.EditedAt,
			&i.AuthorUserID,
			&i.AuthorAgentID,
			&i.AuthorName,
			&i.AuthorAvatar,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markMessageRead = `-- name: MarkMessageRead :exec
insert into message_reads (message_id, user_id)
values ($1, $2)
on conflict (message_id, user_id) where user_id is not null do nothing
`

type MarkMessageReadParams struct {
	MessageID pgtype.UUID `json:"message_id"`
	UserID    pgtype.UUID `json:"user_id"`
}

func (q *Queries) MarkMessageRead(ctx context.Context, arg MarkMessageReadParams) error {
	_, err := q.db.Exec(ctx, markMessageRead, arg.MessageID, arg.UserID)
	return err
}

const mentionsForUser = `-- name: MentionsForUser :many
select m.id, m.conversation_id, m.body, m.created_at, m.edited_at,
       m.author_user_id, m.author_agent_id,
       coalesce(u.name, a.name, '') as author_name,
       coalesce(u.avatar_key, a.avatar_key) as author_avatar,
       c.project_id,
       (r.message_id is not null) as is_read
from messages m
join conversations c on c.id = m.conversation_id
join projects p on p.id = c.project_id
join workspace_members wm on wm.workspace_id = p.workspace_id
  and wm.user_id = $1
join users me on me.id = $1
left join users u on u.id = m.author_user_id
left join agents a on a.id = m.author_agent_id
left join message_reads r on r.message_id = m.id and r.user_id = $1
where m.deleted_at is null
  and (m.author_user_id is null or m.author_user_id <> $1)
  and position(lower('@' || me.name) in lower(m.body)) > 0
order by m.created_at desc, m.id desc
limit 50
`

type MentionsForUserRow struct {
	ID             pgtype.UUID        `json:"id"`
	ConversationID pgtype.UUID        `json:"conversation_id"`
	Body           string             `json:"body"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	EditedAt       pgtype.Timestamptz `json:"edited_at"`
	AuthorUserID   pgtype.UUID        `json:"author_user_id"`
	AuthorAgentID  pgtype.UUID        `json:"author_agent_id"`
	AuthorName     string             `json:"author_name"`
	AuthorAvatar   pgtype.Text        `json:"author_avatar"`
	ProjectID      pgtype.UUID        `json:"project_id"`
	IsRead         interface{}        `json:"is_read"`
}

// messages mentioning the user (@<name>), newest first
func (q *Queries) MentionsForUser(ctx context.Context, userID pgtype.UUID) ([]MentionsForUserRow, error) {
	rows, err := q.db.Query(ctx, mentionsForUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []MentionsForUserRow{}
	for rows.Next() {
		var i MentionsForUserRow
		if err := rows.Scan(
			&i.ID,
			&i.ConversationID,
			&i.Body,
			&i.CreatedAt,
			&i.EditedAt,
			&i.AuthorUserID,
			&i.AuthorAgentID,
			&i.AuthorName,
			&i.AuthorAvatar,
			&i.ProjectID,
			&i.IsRead,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const recentProjectMessages = `-- name: RecentProjectMessages :many
select m.id, m.conversation_id, m.body, m.created_at, m.edited_at,
       m.author_user_id, m.author_agent_id,
       coalesce(u.name, a.name, '') as author_name,
       coalesce(u.avatar_key, a.avatar_key) as author_avatar
from messages m
join conversations c on c.id = m.conversation_id
left join users u on u.id = m.author_user_id
left join agents a on a.id = m.author_agent_id
where c.project_id = $1 and m.deleted_at is null
order by m.created_at desc, m.id desc
limit 10
`

type RecentProjectMessagesRow struct {
	ID             pgtype.UUID        `json:"id"`
	ConversationID pgtype.UUID        `json:"conversation_id"`
	Body           string             `json:"body"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	EditedAt       pgtype.Timestamptz `json:"edited_at"`
	AuthorUserID   pgtype.UUID        `json:"author_user_id"`
	AuthorAgentID  pgtype.UUID        `json:"author_agent_id"`
	AuthorName     string             `json:"author_name"`
	AuthorAvatar   pgtype.Text        `json:"author_avatar"`
}

func (q *Queries) RecentProjectMessages(ctx context.Context, projectID pgtype.UUID) ([]RecentProjectMessagesRow, error) {
	rows, err := q.db.Query(ctx, recentProjectMessages, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []RecentProjectMessagesRow{}
	for rows.Next() {
		var i RecentProjectMessagesRow
		if err := rows.Scan(
			&i.ID,
			&i.ConversationID,
			&i.Body,
			&i.CreatedAt,
			&i.EditedAt,
			&i.AuthorUserID,
			&i.AuthorAgentID,
			&i.AuthorName,
			&i.AuthorAvatar,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const unreadCounts = `-- name: UnreadCounts :many
select p.id as project_id, count(m.id)::int as unread
from projects p
join workspace_members wm on wm.workspace_id = p.workspace_id
  and wm.user_id = $1
join conversations c on c.project_id = p.id
join messages m on m.conversation_id = c.id and m.deleted_at is null
where (m.author_user_id is null or m.author_user_id <> $1)
  and not exists (
    select 1 from message_reads r
    where r.message_id = m.id and r.user_id = $1)
group by p.id
`

type UnreadCountsRow struct {
	ProjectID pgtype.UUID `json:"project_id"`
	Unread    int32       `json:"unread"`
}

// per-project count of messages the user hasn't read, excluding their own
func (q *Queries) UnreadCounts(ctx context.Context, userID pgtype.UUID) ([]UnreadCountsRow, error) {
	rows, err := q.db.Query(ctx, unreadCounts, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []UnreadCountsRow{}
	for rows.Next() {
		var i UnreadCountsRow
		if err := rows.Scan(&i.ProjectID, &i.Unread); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
