// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: conversations.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const addReactionUser = `-- name: AddReactionUser :exec
insert into message_reactions (message_id, user_id, emoji)
values ($1, $2, $3)
on conflict (message_id, user_id, emoji) where user_id is not null do nothing
`

type AddReactionUserParams struct {
	MessageID pgtype.UUID `json:"message_id"`
	UserID    pgtype.UUID `json:"user_id"`
	Emoji     string      `json:"emoji"`
}

func (q *Queries) AddReactionUser(ctx context.Context, arg AddReactionUserParams) error {
	_, err := q.db.Exec(ctx, addReactionUser, arg.MessageID, arg.UserID, arg.Emoji)
	return err
}

const agentReadMessageIDs = `-- name: AgentReadMessageIDs :many
select r.message_id from message_reads r
join messages m on m.id = r.message_id
where r.agent_id is not null
  and (m.author_agent_id is null or r.agent_id <> m.author_agent_id)
  and r.message_id = any($1::uuid[])
group by r.message_id
`

// subset of the given ids that at least one other agent has read
func (q *Queries) AgentReadMessageIDs(ctx context.Context, ids []pgtype.UUID) ([]pgtype.UUID, error) {
	rows, err := q.db.Query(ctx, agentReadMessageIDs, ids)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []pgtype.UUID{}
	for rows.Next() {
		var message_id pgtype.UUID
		if err := rows.Scan(&message_id); err != nil {
			return nil, err
		}
		items = append(items, message_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const clearConversation = `-- name: ClearConversation :execrows
update messages set deleted_at = now()
where conversation_id = $1 and deleted_at is null
`

// /clear — soft-delete every message in the conversation at once
func (q *Queries) ClearConversation(ctx context.Context, conversationID pgtype.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, clearConversation, conversationID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const copyMessageAttachments = `-- name: CopyMessageAttachments :exec
insert into message_attachments (message_id, attachment_id, position)
select $1::uuid, attachment_id, position
from message_attachments
where message_id = $2::uuid
`

type CopyMessageAttachmentsParams struct {
	MessageID pgtype.UUID `json:"message_id"`
	SourceID  pgtype.UUID `json:"source_id"`
}

// a forward reuses the same attachment objects behind the new message
func (q *Queries) CopyMessageAttachments(ctx context.Context, arg CopyMessageAttachmentsParams) error {
	_, err := q.db.Exec(ctx, copyMessageAttachments, arg.MessageID, arg.SourceID)
	return err
}

const createMessage = `-- name: CreateMessage :one
insert into messages (conversation_id, author_user_id, body, parent_id, mentions, forwarded_from, tags)
values ($1, $2, $3, $4, coalesce($5, '[]'::jsonb), $6, coalesce($7, '{}'::text[]))
returning id
`

type CreateMessageParams struct {
	ConversationID pgtype.UUID `json:"conversation_id"`
	AuthorUserID   pgtype.UUID `json:"author_user_id"`
	Body           string      `json:"body"`
	ParentID       pgtype.UUID `json:"parent_id"`
	Mentions       interface{} `json:"mentions"`
	ForwardedFrom  pgtype.UUID `json:"forwarded_from"`
	Tags           interface{} `json:"tags"`
}

func (q *Queries) CreateMessage(ctx context.Context, arg CreateMessageParams) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, createMessage,
		arg.ConversationID,
		arg.AuthorUserID,
		arg.Body,
		arg.ParentID,
		arg.Mentions,
		arg.ForwardedFrom,
		arg.Tags,
	)
	var id pgtype.UUID
	err := row.Scan(&id)
	return id, err
}

const createProjectConversation = `-- name: CreateProjectConversation :one
insert into conversations (project_id, kind)
values ($1, 'project')
on conflict do nothing
returning id, project_id, kind, issue_id, created_at, brief_id, parent_message_id, title, created_by_user, created_by_agent, creator_name_snapshot
`

func (q *Queries) CreateProjectConversation(ctx context.Context, projectID pgtype.UUID) (Conversation, error) {
	row := q.db.QueryRow(ctx, createProjectConversation, projectID)
	var i Conversation
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Kind,
		&i.IssueID,
		&i.CreatedAt,
		&i.BriefID,
		&i.ParentMessageID,
		&i.Title,
		&i.CreatedByUser,
		&i.CreatedByAgent,
		&i.CreatorNameSnapshot,
	)
	return i, err
}

const createThread = `-- name: CreateThread :one
insert into conversations (project_id, kind, parent_message_id, title, created_by_user)
values ($1, 'thread', $2,
        $3, $4)
on conflict (parent_message_id) where kind = 'thread' do nothing
returning id, project_id, kind, issue_id, created_at, brief_id, parent_message_id, title, created_by_user, created_by_agent, creator_name_snapshot
`

type CreateThreadParams struct {
	ProjectID       pgtype.UUID `json:"project_id"`
	ParentMessageID pgtype.UUID `json:"parent_message_id"`
	Title           pgtype.Text `json:"title"`
	CreatedByUser   pgtype.UUID `json:"created_by_user"`
}

// one thread per message; the unique index makes this race-safe
func (q *Queries) CreateThread(ctx context.Context, arg CreateThreadParams) (Conversation, error) {
	row := q.db.QueryRow(ctx, createThread,
		arg.ProjectID,
		arg.ParentMessageID,
		arg.Title,
		arg.CreatedByUser,
	)
	var i Conversation
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Kind,
		&i.IssueID,
		&i.CreatedAt,
		&i.BriefID,
		&i.ParentMessageID,
		&i.Title,
		&i.CreatedByUser,
		&i.CreatedByAgent,
		&i.CreatorNameSnapshot,
	)
	return i, err
}

const createThreadAgent = `-- name: CreateThreadAgent :one
insert into conversations (project_id, kind, parent_message_id, title, created_by_agent)
values ($1, 'thread', $2,
        $3, $4)
on conflict (parent_message_id) where kind = 'thread' do nothing
returning id, project_id, kind, issue_id, created_at, brief_id, parent_message_id, title, created_by_user, created_by_agent, creator_name_snapshot
`

type CreateThreadAgentParams struct {
	ProjectID       pgtype.UUID `json:"project_id"`
	ParentMessageID pgtype.UUID `json:"parent_message_id"`
	Title           pgtype.Text `json:"title"`
	CreatedByAgent  pgtype.UUID `json:"created_by_agent"`
}

func (q *Queries) CreateThreadAgent(ctx context.Context, arg CreateThreadAgentParams) (Conversation, error) {
	row := q.db.QueryRow(ctx, createThreadAgent,
		arg.ProjectID,
		arg.ParentMessageID,
		arg.Title,
		arg.CreatedByAgent,
	)
	var i Conversation
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Kind,
		&i.IssueID,
		&i.CreatedAt,
		&i.BriefID,
		&i.ParentMessageID,
		&i.Title,
		&i.CreatedByUser,
		&i.CreatedByAgent,
		&i.CreatorNameSnapshot,
	)
	return i, err
}

const getConversationByID = `-- name: GetConversationByID :one
select id, project_id, kind, issue_id, created_at, brief_id, parent_message_id, title, created_by_user, created_by_agent, creator_name_snapshot
from conversations
where id = $1
`

func (q *Queries) GetConversationByID(ctx context.Context, id pgtype.UUID) (Conversation, error) {
	row := q.db.QueryRow(ctx, getConversationByID, id)
	var i Conversation
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Kind,
		&i.IssueID,
		&i.CreatedAt,
		&i.BriefID,
		&i.ParentMessageID,
		&i.Title,
		&i.CreatedByUser,
		&i.CreatedByAgent,
		&i.CreatorNameSnapshot,
	)
	return i, err
}

const getConversationForUser = `-- name: GetConversationForUser :one
select c.id, c.project_id, c.kind, c.issue_id, c.created_at, c.brief_id, c.parent_message_id, c.title, c.created_by_user, c.created_by_agent, c.creator_name_snapshot
from conversations c
join projects p on p.id = c.project_id
join workspace_members wm on wm.workspace_id = p.workspace_id
where c.id = $1 and wm.user_id = $2
`

type GetConversationForUserParams struct {
	ID     pgtype.UUID `json:"id"`
	UserID pgtype.UUID `json:"user_id"`
}

// resolves the conversation only when the user belongs to its workspace
func (q *Queries) GetConversationForUser(ctx context.Context, arg GetConversationForUserParams) (Conversation, error) {
	row := q.db.QueryRow(ctx, getConversationForUser, arg.ID, arg.UserID)
	var i Conversation
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Kind,
		&i.IssueID,
		&i.CreatedAt,
		&i.BriefID,
		&i.ParentMessageID,
		&i.Title,
		&i.CreatedByUser,
		&i.CreatedByAgent,
		&i.CreatorNameSnapshot,
	)
	return i, err
}

const getMessageByID = `-- name: GetMessageByID :one
select m.id, m.conversation_id, m.body, m.mentions, m.tags, m.created_at, m.edited_at, m.deleted_at, m.parent_id,
       m.author_user_id, m.author_agent_id, m.author_kind_snapshot,
       coalesce(u.name, a.name, nullif(m.author_name_snapshot, ''), '') as author_name,
       coalesce(u.avatar_key, a.avatar_key) as author_avatar,
       coalesce(pu.name, pa.name, nullif(pm.author_name_snapshot, ''), '') as parent_author_name,
       pm.body as parent_body,
       (pm.id is not null and pm.deleted_at is not null) as parent_deleted,
       t.id as thread_id, t.title as thread_title,
       (select count(*)::int from messages tm
         where tm.conversation_id = t.id and tm.deleted_at is null) as thread_reply_count,
       m.pinned_at, m.forwarded_from,
       f.conversation_id as fwd_conversation_id,
       fcp.project_id as fwd_project_id,
       coalesce(fu.name, fa.name, nullif(f.author_name_snapshot, ''), '') as fwd_author_name
from messages m
left join users u on u.id = m.author_user_id
left join agents a on a.id = m.author_agent_id
left join messages pm on pm.id = m.parent_id
left join users pu on pu.id = pm.author_user_id
left join agents pa on pa.id = pm.author_agent_id
left join conversations t on t.parent_message_id = m.id and t.kind = 'thread'
left join messages f on f.id = m.forwarded_from
left join conversations fcp on fcp.id = f.conversation_id
left join users fu on fu.id = f.author_user_id
left join agents fa on fa.id = f.author_agent_id
where m.id = $1
`

type GetMessageByIDRow struct {
	ID                 pgtype.UUID        `json:"id"`
	ConversationID     pgtype.UUID        `json:"conversation_id"`
	Body               string             `json:"body"`
	Mentions           []byte             `json:"mentions"`
	Tags               []string           `json:"tags"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
	EditedAt           pgtype.Timestamptz `json:"edited_at"`
	DeletedAt          pgtype.Timestamptz `json:"deleted_at"`
	ParentID           pgtype.UUID        `json:"parent_id"`
	AuthorUserID       pgtype.UUID        `json:"author_user_id"`
	AuthorAgentID      pgtype.UUID        `json:"author_agent_id"`
	AuthorKindSnapshot string             `json:"author_kind_snapshot"`
	AuthorName         string             `json:"author_name"`
	AuthorAvatar       pgtype.Text        `json:"author_avatar"`
	ParentAuthorName   string             `json:"parent_author_name"`
	ParentBody         pgtype.Text        `json:"parent_body"`
	ParentDeleted      pgtype.Bool        `json:"parent_deleted"`
	ThreadID           pgtype.UUID        `json:"thread_id"`
	ThreadTitle        pgtype.Text        `json:"thread_title"`
	ThreadReplyCount   int32              `json:"thread_reply_count"`
	PinnedAt           pgtype.Timestamptz `json:"pinned_at"`
	ForwardedFrom      pgtype.UUID        `json:"forwarded_from"`
	FwdConversationID  pgtype.UUID        `json:"fwd_conversation_id"`
	FwdProjectID       pgtype.UUID        `json:"fwd_project_id"`
	FwdAuthorName      string             `json:"fwd_author_name"`
}

func (q *Queries) GetMessageByID(ctx context.Context, id pgtype.UUID) (GetMessageByIDRow, error) {
	row := q.db.QueryRow(ctx, getMessageByID, id)
	var i GetMessageByIDRow
	err := row.Scan(
		&i.ID,
		&i.ConversationID,
		&i.Body,
		&i.Mentions,
		&i.Tags,
		&i.CreatedAt,
		&i.EditedAt,
		&i.DeletedAt,
		&i.ParentID,
		&i.AuthorUserID,
		&i.AuthorAgentID,
		&i.AuthorKindSnapshot,
		&i.AuthorName,
		&i.AuthorAvatar,
		&i.ParentAuthorName,
		&i.ParentBody,
		&i.ParentDeleted,
		&i.ThreadID,
		&i.ThreadTitle,
		&i.ThreadReplyCount,
		&i.PinnedAt,
		&i.ForwardedFrom,
		&i.FwdConversationID,
		&i.FwdProjectID,
		&i.FwdAuthorName,
	)
	return i, err
}

const getMessageConversation = `-- name: GetMessageConversation :one
select conversation_id
from messages
where id = $1
`

// conversation a message lives in - used to forbid nested threads
func (q *Queries) GetMessageConversation(ctx context.Context, id pgtype.UUID) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, getMessageConversation, id)
	var conversation_id pgtype.UUID
	err := row.Scan(&conversation_id)
	return conversation_id, err
}

const getMessageForUser = `-- name: GetMessageForUser :one
select m.id
from messages m
join conversations c on c.id = m.conversation_id
join projects p on p.id = c.project_id
join workspace_members wm on wm.workspace_id = p.workspace_id
where m.id = $1 and wm.user_id = $2 and m.deleted_at is null
`

type GetMessageForUserParams struct {
	ID     pgtype.UUID `json:"id"`
	UserID pgtype.UUID `json:"user_id"`
}

// message id only when the user may see its workspace
func (q *Queries) GetMessageForUser(ctx context.Context, arg GetMessageForUserParams) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, getMessageForUser, arg.ID, arg.UserID)
	var id pgtype.UUID
	err := row.Scan(&id)
	return id, err
}

const getProjectConversation = `-- name: GetProjectConversation :one
select id, project_id, kind, issue_id, created_at, brief_id, parent_message_id, title, created_by_user, created_by_agent, creator_name_snapshot
from conversations
where project_id = $1 and kind = 'project'
`

func (q *Queries) GetProjectConversation(ctx context.Context, projectID pgtype.UUID) (Conversation, error) {
	row := q.db.QueryRow(ctx, getProjectConversation, projectID)
	var i Conversation
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Kind,
		&i.IssueID,
		&i.CreatedAt,
		&i.BriefID,
		&i.ParentMessageID,
		&i.Title,
		&i.CreatedByUser,
		&i.CreatedByAgent,
		&i.CreatorNameSnapshot,
	)
	return i, err
}

const getProjectForUser = `-- name: GetProjectForUser :one
select p.id, p.workspace_id, p.key, p.name, p.description, p.icon, p.color,
       p.statuses, p.local_path, p.brief_policy, p.created_at
from projects p
join workspace_members wm on wm.workspace_id = p.workspace_id
where p.id = $1 and wm.user_id = $2
`

type GetProjectForUserParams struct {
	ID     pgtype.UUID `json:"id"`
	UserID pgtype.UUID `json:"user_id"`
}

type GetProjectForUserRow struct {
	ID          pgtype.UUID        `json:"id"`
	WorkspaceID pgtype.UUID        `json:"workspace_id"`
	Key         string             `json:"key"`
	Name        string             `json:"name"`
	Description string             `json:"description"`
	Icon        pgtype.Text        `json:"icon"`
	Color       pgtype.Text        `json:"color"`
	Statuses    []byte             `json:"statuses"`
	LocalPath   pgtype.Text        `json:"local_path"`
	BriefPolicy string             `json:"brief_policy"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

// project row only when the caller is a member of its workspace
func (q *Queries) GetProjectForUser(ctx context.Context, arg GetProjectForUserParams) (GetProjectForUserRow, error) {
	row := q.db.QueryRow(ctx, getProjectForUser, arg.ID, arg.UserID)
	var i GetProjectForUserRow
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Key,
		&i.Name,
		&i.Description,
		&i.Icon,
		&i.Color,
		&i.Statuses,
		&i.LocalPath,
		&i.BriefPolicy,
		&i.CreatedAt,
	)
	return i, err
}

const getThread = `-- name: GetThread :one
select c.id, c.project_id, c.parent_message_id, c.title, c.created_at,
       pm.conversation_id as parent_conversation_id,
       coalesce(u.name, a.name, nullif(c.creator_name_snapshot, ''), '') as creator_name,
       case when pm.deleted_at is null then coalesce(pu.name, pa.name, nullif(pm.author_name_snapshot, ''), '')
            else 'Deleted' end as parent_author_name,
       case when pm.deleted_at is null then left(pm.body, 160)
            else 'Original message was deleted' end as parent_preview,
       (select count(*)::int from messages tm
         where tm.conversation_id = c.id and tm.deleted_at is null) as reply_count
from conversations c
join messages pm on pm.id = c.parent_message_id
left join users u on u.id = c.created_by_user
left join agents a on a.id = c.created_by_agent
left join users pu on pu.id = pm.author_user_id
left join agents pa on pa.id = pm.author_agent_id
where c.id = $1
`

type GetThreadRow struct {
	ID                   pgtype.UUID        `json:"id"`
	ProjectID            pgtype.UUID        `json:"project_id"`
	ParentMessageID      pgtype.UUID        `json:"parent_message_id"`
	Title                pgtype.Text        `json:"title"`
	CreatedAt            pgtype.Timestamptz `json:"created_at"`
	ParentConversationID pgtype.UUID        `json:"parent_conversation_id"`
	CreatorName          string             `json:"creator_name"`
	ParentAuthorName     string             `json:"parent_author_name"`
	ParentPreview        string             `json:"parent_preview"`
	ReplyCount           int32              `json:"reply_count"`
}

func (q *Queries) GetThread(ctx context.Context, id pgtype.UUID) (GetThreadRow, error) {
	row := q.db.QueryRow(ctx, getThread, id)
	var i GetThreadRow
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.ParentMessageID,
		&i.Title,
		&i.CreatedAt,
		&i.ParentConversationID,
		&i.CreatorName,
		&i.ParentAuthorName,
		&i.ParentPreview,
		&i.ReplyCount,
	)
	return i, err
}

const getThreadByParentMessage = `-- name: GetThreadByParentMessage :one
select id, project_id, kind, issue_id, created_at, brief_id, parent_message_id, title, created_by_user, created_by_agent, creator_name_snapshot
from conversations
where parent_message_id = $1 and kind = 'thread'
`

func (q *Queries) GetThreadByParentMessage(ctx context.Context, parentMessageID pgtype.UUID) (Conversation, error) {
	row := q.db.QueryRow(ctx, getThreadByParentMessage, parentMessageID)
	var i Conversation
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Kind,
		&i.IssueID,
		&i.CreatedAt,
		&i.BriefID,
		&i.ParentMessageID,
		&i.Title,
		&i.CreatedByUser,
		&i.CreatedByAgent,
		&i.CreatorNameSnapshot,
	)
	return i, err
}

const listMessages = `-- name: ListMessages :many
select m.id, m.conversation_id, m.body, m.mentions, m.tags, m.created_at, m.edited_at, m.deleted_at, m.parent_id,
       m.author_user_id, m.author_agent_id, m.author_kind_snapshot,
       coalesce(u.name, a.name, nullif(m.author_name_snapshot, ''), '') as author_name,
       coalesce(u.avatar_key, a.avatar_key) as author_avatar,
       coalesce(pu.name, pa.name, nullif(pm.author_name_snapshot, ''), '') as parent_author_name,
       pm.body as parent_body,
       (pm.id is not null and pm.deleted_at is not null) as parent_deleted,
       t.id as thread_id, t.title as thread_title,
       (select count(*)::int from messages tm
         where tm.conversation_id = t.id and tm.deleted_at is null) as thread_reply_count,
       m.pinned_at, m.forwarded_from,
       f.conversation_id as fwd_conversation_id,
       fcp.project_id as fwd_project_id,
       coalesce(fu.name, fa.name, nullif(f.author_name_snapshot, ''), '') as fwd_author_name
from messages m
left join users u on u.id = m.author_user_id
left join agents a on a.id = m.author_agent_id
left join messages pm on pm.id = m.parent_id
left join users pu on pu.id = pm.author_user_id
left join agents pa on pa.id = pm.author_agent_id
left join conversations t on t.parent_message_id = m.id and t.kind = 'thread'
left join messages f on f.id = m.forwarded_from
left join conversations fcp on fcp.id = f.conversation_id
left join users fu on fu.id = f.author_user_id
left join agents fa on fa.id = f.author_agent_id
where m.conversation_id = $1
  and m.deleted_at is null
  and ($2::text is null or $2::text = any(m.tags))
  and ($3::uuid is null or
       (m.created_at, m.id) < (select m2.created_at, m2.id from messages m2 where m2.id = $3::uuid))
order by m.created_at desc, m.id desc
limit $4::int
`

type ListMessagesParams struct {
	ConversationID pgtype.UUID `json:"conversation_id"`
	Tag            pgtype.Text `json:"tag"`
	Before         pgtype.UUID `json:"before"`
	Lim            int32       `json:"lim"`
}

type ListMessagesRow struct {
	ID                 pgtype.UUID        `json:"id"`
	ConversationID     pgtype.UUID        `json:"conversation_id"`
	Body               string             `json:"body"`
	Mentions           []byte             `json:"mentions"`
	Tags               []string           `json:"tags"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
	EditedAt           pgtype.Timestamptz `json:"edited_at"`
	DeletedAt          pgtype.Timestamptz `json:"deleted_at"`
	ParentID           pgtype.UUID        `json:"parent_id"`
	AuthorUserID       pgtype.UUID        `json:"author_user_id"`
	AuthorAgentID      pgtype.UUID        `json:"author_agent_id"`
	AuthorKindSnapshot string             `json:"author_kind_snapshot"`
	AuthorName         string             `json:"author_name"`
	AuthorAvatar       pgtype.Text        `json:"author_avatar"`
	ParentAuthorName   string             `json:"parent_author_name"`
	ParentBody         pgtype.Text        `json:"parent_body"`
	ParentDeleted      pgtype.Bool        `json:"parent_deleted"`
	ThreadID           pgtype.UUID        `json:"thread_id"`
	ThreadTitle        pgtype.Text        `json:"thread_title"`
	ThreadReplyCount   int32              `json:"thread_reply_count"`
	PinnedAt           pgtype.Timestamptz `json:"pinned_at"`
	ForwardedFrom      pgtype.UUID        `json:"forwarded_from"`
	FwdConversationID  pgtype.UUID        `json:"fwd_conversation_id"`
	FwdProjectID       pgtype.UUID        `json:"fwd_project_id"`
	FwdAuthorName      string             `json:"fwd_author_name"`
}

// newest-first page; $2 is an optional "older than message id" cursor,
// narg(tag) filters to messages carrying that tag
func (q *Queries) ListMessages(ctx context.Context, arg ListMessagesParams) ([]ListMessagesRow, error) {
	rows, err := q.db.Query(ctx, listMessages,
		arg.ConversationID,
		arg.Tag,
		arg.Before,
		arg.Lim,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListMessagesRow{}
	for rows.Next() {
		var i ListMessagesRow
		if err := rows.Scan(
			&i.ID,
			&i.ConversationID,
			&i.Body,
			&i.Mentions,
			&i.Tags,
			&i.CreatedAt,
			&i.EditedAt,
			&i.DeletedAt,
			&i.ParentID,
			&i.AuthorUserID,
			&i.AuthorAgentID,
			&i.AuthorKindSnapshot,
			&i.AuthorName,
			&i.AuthorAvatar,
			&i.ParentAuthorName,
			&i.ParentBody,
			&i.ParentDeleted,
			&i.ThreadID,
			&i.ThreadTitle,
			&i.ThreadReplyCount,
			&i.PinnedAt,
			&i.ForwardedFrom,
			&i.FwdConversationID,
			&i.FwdProjectID,
			&i.FwdAuthorName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPinnedMessages = `-- name: ListPinnedMessages :many
select m.id, m.conversation_id, m.body, m.mentions, m.tags, m.created_at, m.edited_at, m.deleted_at, m.parent_id,
       m.author_user_id, m.author_agent_id, m.author_kind_snapshot,
       coalesce(u.name, a.name, nullif(m.author_name_snapshot, ''), '') as author_name,
       coalesce(u.avatar_key, a.avatar_key) as author_avatar,
       coalesce(pu.name, pa.name, nullif(pm.author_name_snapshot, ''), '') as parent_author_name,
       pm.body as parent_body,
       (pm.id is not null and pm.deleted_at is not null) as parent_deleted,
       t.id as thread_id, t.title as thread_title,
       (select count(*)::int from messages tm
         where tm.conversation_id = t.id and tm.deleted_at is null) as thread_reply_count,
       m.pinned_at, m.forwarded_from,
       f.conversation_id as fwd_conversation_id,
       fcp.project_id as fwd_project_id,
       coalesce(fu.name, fa.name, nullif(f.author_name_snapshot, ''), '') as fwd_author_name
from messages m
left join users u on u.id = m.author_user_id
left join agents a on a.id = m.author_agent_id
left join messages pm on pm.id = m.parent_id
left join users pu on pu.id = pm.author_user_id
left join agents pa on pa.id = pm.author_agent_id
left join conversations t on t.parent_message_id = m.id and t.kind = 'thread'
left join messages f on f.id = m.forwarded_from
left join conversations fcp on fcp.id = f.conversation_id
left join users fu on fu.id = f.author_user_id
left join agents fa on fa.id = f.author_agent_id
where m.conversation_id = $1
  and m.deleted_at is null
  and m.pinned_at is not null
order by m.pinned_at desc
`

type ListPinnedMessagesRow struct {
	ID                 pgtype.UUID        `json:"id"`
	ConversationID     pgtype.UUID        `json:"conversation_id"`
	Body               string             `json:"body"`
	Mentions           []byte             `json:"mentions"`
	Tags               []string           `json:"tags"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
	EditedAt           pgtype.Timestamptz `json:"edited_at"`
	DeletedAt          pgtype.Timestamptz `json:"deleted_at"`
	ParentID           pgtype.UUID        `json:"parent_id"`
	AuthorUserID       pgtype.UUID        `json:"author_user_id"`
	AuthorAgentID      pgtype.UUID        `json:"author_agent_id"`
	AuthorKindSnapshot string             `json:"author_kind_snapshot"`
	AuthorName         string             `json:"author_name"`
	AuthorAvatar       pgtype.Text        `json:"author_avatar"`
	ParentAuthorName   string             `json:"parent_author_name"`
	ParentBody         pgtype.Text        `json:"parent_body"`
	ParentDeleted      pgtype.Bool        `json:"parent_deleted"`
	ThreadID           pgtype.UUID        `json:"thread_id"`
	ThreadTitle        pgtype.Text        `json:"thread_title"`
	ThreadReplyCount   int32              `json:"thread_reply_count"`
	PinnedAt           pgtype.Timestamptz `json:"pinned_at"`
	ForwardedFrom      pgtype.UUID        `json:"forwarded_from"`
	FwdConversationID  pgtype.UUID        `json:"fwd_conversation_id"`
	FwdProjectID       pgtype.UUID        `json:"fwd_project_id"`
	FwdAuthorName      string             `json:"fwd_author_name"`
}

// pinned messages in one conversation, most recently pinned first
func (q *Queries) ListPinnedMessages(ctx context.Context, conversationID pgtype.UUID) ([]ListPinnedMessagesRow, error) {
	rows, err := q.db.Query(ctx, listPinnedMessages, conversationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListPinnedMessagesRow{}
	for rows.Next() {
		var i ListPinnedMessagesRow
		if err := rows.Scan(
			&i.ID,
			&i.ConversationID,
			&i.Body,
			&i.Mentions,
			&i.Tags,
			&i.CreatedAt,
			&i.EditedAt,
			&i.DeletedAt,
			&i.ParentID,
			&i.AuthorUserID,
			&i.AuthorAgentID,
			&i.AuthorKindSnapshot,
			&i.AuthorName,
			&i.AuthorAvatar,
			&i.ParentAuthorName,
			&i.ParentBody,
			&i.ParentDeleted,
			&i.ThreadID,
			&i.ThreadTitle,
			&i.ThreadReplyCount,
			&i.PinnedAt,
			&i.ForwardedFrom,
			&i.FwdConversationID,
			&i.FwdProjectID,
			&i.FwdAuthorName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProjectThreads = `-- name: ListProjectThreads :many
select c.id, c.parent_message_id, c.title, c.created_at,
       pm.conversation_id as parent_conversation_id,
       coalesce(u.name, a.name, nullif(c.creator_name_snapshot, ''), '') as creator_name,
       case when pm.deleted_at is null then coalesce(pu.name, pa.name, nullif(pm.author_name_snapshot, ''), '')
            else 'Deleted' end as parent_author_name,
       case when pm.deleted_at is null then left(pm.body, 160)
            else 'Original message was deleted' end as parent_preview,
       (select count(*)::int from messages tm
         where tm.conversation_id = c.id and tm.deleted_at is null) as reply_count,
       (select max(tm.created_at)::timestamptz from messages tm
         where tm.conversation_id = c.id and tm.deleted_at is null) as last_reply_at
from conversations c
join messages pm on pm.id = c.parent_message_id
left join users u on u.id = c.created_by_user
left join agents a on a.id = c.created_by_agent
left join users pu on pu.id = pm.author_user_id
left join agents pa on pa.id = pm.author_agent_id
where c.project_id = $1 and c.kind = 'thread'
order by last_reply_at desc nulls last, c.created_at desc
limit 100
`

type ListProjectThreadsRow struct {
	ID                   pgtype.UUID        `json:"id"`
	ParentMessageID      pgtype.UUID        `json:"parent_message_id"`
	Title                pgtype.Text        `json:"title"`
	CreatedAt            pgtype.Timestamptz `json:"created_at"`
	ParentConversationID pgtype.UUID        `json:"parent_conversation_id"`
	CreatorName          string             `json:"creator_name"`
	ParentAuthorName     string             `json:"parent_author_name"`
	ParentPreview        string             `json:"parent_preview"`
	ReplyCount           int32              `json:"reply_count"`
	LastReplyAt          pgtype.Timestamptz `json:"last_reply_at"`
}

// thread index for a project, most recently active first
func (q *Queries) ListProjectThreads(ctx context.Context, projectID pgtype.UUID) ([]ListProjectThreadsRow, error) {
	rows, err := q.db.Query(ctx, listProjectThreads, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListProjectThreadsRow{}
	for rows.Next() {
		var i ListProjectThreadsRow
		if err := rows.Scan(
			&i.ID,
			&i.ParentMessageID,
			&i.Title,
			&i.CreatedAt,
			&i.ParentConversationID,
			&i.CreatorName,
			&i.ParentAuthorName,
			&i.ParentPreview,
			&i.ReplyCount,
			&i.LastReplyAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listReactionsForMessages = `-- name: ListReactionsForMessages :many
select mr.message_id, mr.emoji, mr.user_id, mr.agent_id,
       coalesce(u.name, a.name, '') as reactor_name
from message_reactions mr
left join users u on u.id = mr.user_id
left join agents a on a.id = mr.agent_id
where mr.message_id = any($1::uuid[])
order by mr.created_at
`

type ListReactionsForMessagesRow struct {
	MessageID   pgtype.UUID `json:"message_id"`
	Emoji       string      `json:"emoji"`
	UserID      pgtype.UUID `json:"user_id"`
	AgentID     pgtype.UUID `json:"agent_id"`
	ReactorName string      `json:"reactor_name"`
}

func (q *Queries) ListReactionsForMessages(ctx context.Context, ids []pgtype.UUID) ([]ListReactionsForMessagesRow, error) {
	rows, err := q.db.Query(ctx, listReactionsForMessages, ids)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListReactionsForMessagesRow{}
	for rows.Next() {
		var i ListReactionsForMessagesRow
		if err := rows.Scan(
			&i.MessageID,
			&i.Emoji,
			&i.UserID,
			&i.AgentID,
			&i.ReactorName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markConversationRead = `-- name: MarkConversationRead :exec
insert into message_reads (message_id, user_id)
select m.id, $2
from messages m
where m.conversation_id = $1
  and m.deleted_at is null
on conflict (message_id, user_id) where user_id is not null do nothing
`

type MarkConversationReadParams struct {
	ConversationID pgtype.UUID `json:"conversation_id"`
	UserID         pgtype.UUID `json:"user_id"`
}

// mark every message in the conversation read for the user (bulk, on view)
func (q *Queries) MarkConversationRead(ctx context.Context, arg MarkConversationReadParams) error {
	_, err := q.db.Exec(ctx, markConversationRead, arg.ConversationID, arg.UserID)
	return err
}

const markMessageRead = `-- name: MarkMessageRead :exec
insert into message_reads (message_id, user_id)
values ($1, $2)
on conflict (message_id, user_id) where user_id is not null do nothing
`

type MarkMessageReadParams struct {
	MessageID pgtype.UUID `json:"message_id"`
	UserID    pgtype.UUID `json:"user_id"`
}

func (q *Queries) MarkMessageRead(ctx context.Context, arg MarkMessageReadParams) error {
	_, err := q.db.Exec(ctx, markMessageRead, arg.MessageID, arg.UserID)
	return err
}

const mentionsForUser = `-- name: MentionsForUser :many
select m.id, m.conversation_id, m.body, m.created_at, m.edited_at,
       m.author_user_id, m.author_agent_id, m.author_kind_snapshot,
       coalesce(u.name, a.name, nullif(m.author_name_snapshot, ''), '') as author_name,
       coalesce(u.avatar_key, a.avatar_key) as author_avatar,
       c.project_id,
       (r.message_id is not null) as is_read
from messages m
join conversations c on c.id = m.conversation_id
join projects p on p.id = c.project_id
join workspace_members wm on wm.workspace_id = p.workspace_id
  and wm.user_id = $1
join users me on me.id = $1
left join users u on u.id = m.author_user_id
left join agents a on a.id = m.author_agent_id
left join message_reads r on r.message_id = m.id and r.user_id = $1
where m.deleted_at is null
  and (m.author_user_id is null or m.author_user_id <> $1)
  and position(lower('@' || me.name) in lower(m.body)) > 0
order by m.created_at desc, m.id desc
limit 50
`

type MentionsForUserRow struct {
	ID                 pgtype.UUID        `json:"id"`
	ConversationID     pgtype.UUID        `json:"conversation_id"`
	Body               string             `json:"body"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
	EditedAt           pgtype.Timestamptz `json:"edited_at"`
	AuthorUserID       pgtype.UUID        `json:"author_user_id"`
	AuthorAgentID      pgtype.UUID        `json:"author_agent_id"`
	AuthorKindSnapshot string             `json:"author_kind_snapshot"`
	AuthorName         string             `json:"author_name"`
	AuthorAvatar       pgtype.Text        `json:"author_avatar"`
	ProjectID          pgtype.UUID        `json:"project_id"`
	IsRead             interface{}        `json:"is_read"`
}

// messages mentioning the user (@<name>), newest first
func (q *Queries) MentionsForUser(ctx context.Context, userID pgtype.UUID) ([]MentionsForUserRow, error) {
	rows, err := q.db.Query(ctx, mentionsForUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []MentionsForUserRow{}
	for rows.Next() {
		var i MentionsForUserRow
		if err := rows.Scan(
			&i.ID,
			&i.ConversationID,
			&i.Body,
			&i.CreatedAt,
			&i.EditedAt,
			&i.AuthorUserID,
			&i.AuthorAgentID,
			&i.AuthorKindSnapshot,
			&i.AuthorName,
			&i.AuthorAvatar,
			&i.ProjectID,
			&i.IsRead,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const messageParentInConversation = `-- name: MessageParentInConversation :one
select m.id
from messages m
where m.id = $1
  and m.conversation_id = $2
  and m.deleted_at is null
`

type MessageParentInConversationParams struct {
	ID             pgtype.UUID `json:"id"`
	ConversationID pgtype.UUID `json:"conversation_id"`
}

// reply target must live in the same conversation and be undeleted
func (q *Queries) MessageParentInConversation(ctx context.Context, arg MessageParentInConversationParams) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, messageParentInConversation, arg.ID, arg.ConversationID)
	var id pgtype.UUID
	err := row.Scan(&id)
	return id, err
}

const messageReadByAgent = `-- name: MessageReadByAgent :one
select exists (
    select 1 from message_reads r
    join messages m on m.id = r.message_id
    where r.message_id = $1
      and r.agent_id is not null
      and (m.author_agent_id is null or r.agent_id <> m.author_agent_id))
`

// true once an agent other than the author has read the message; edits lock
// from that point (an agent's own read receipt must not lock its own message)
func (q *Queries) MessageReadByAgent(ctx context.Context, messageID pgtype.UUID) (bool, error) {
	row := q.db.QueryRow(ctx, messageReadByAgent, messageID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const parentAuthorID = `-- name: ParentAuthorID :one
select m2.author_user_id
from messages m
join messages m2 on m2.id = m.parent_id
where m.id = $1
`

// user who wrote a message's parent; null when the parent is an agent's
func (q *Queries) ParentAuthorID(ctx context.Context, id pgtype.UUID) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, parentAuthorID, id)
	var author_user_id pgtype.UUID
	err := row.Scan(&author_user_id)
	return author_user_id, err
}

const pinMessage = `-- name: PinMessage :one
update messages set pinned_at = now()
where id = $1 and deleted_at is null
returning id, conversation_id
`

type PinMessageRow struct {
	ID             pgtype.UUID `json:"id"`
	ConversationID pgtype.UUID `json:"conversation_id"`
}

// any project member may pin; conversation id comes back for the SSE frame
func (q *Queries) PinMessage(ctx context.Context, id pgtype.UUID) (PinMessageRow, error) {
	row := q.db.QueryRow(ctx, pinMessage, id)
	var i PinMessageRow
	err := row.Scan(&i.ID, &i.ConversationID)
	return i, err
}

const recentProjectMessages = `-- name: RecentProjectMessages :many
select m.id, m.conversation_id, m.body, m.mentions, m.tags, m.created_at, m.edited_at, m.deleted_at, m.parent_id,
       m.author_user_id, m.author_agent_id, m.author_kind_snapshot,
       coalesce(u.name, a.name, nullif(m.author_name_snapshot, ''), '') as author_name,
       coalesce(u.avatar_key, a.avatar_key) as author_avatar,
       coalesce(pu.name, pa.name, nullif(pm.author_name_snapshot, ''), '') as parent_author_name,
       pm.body as parent_body,
       (pm.id is not null and pm.deleted_at is not null) as parent_deleted
from messages m
join conversations c on c.id = m.conversation_id
left join users u on u.id = m.author_user_id
left join agents a on a.id = m.author_agent_id
left join messages pm on pm.id = m.parent_id
left join users pu on pu.id = pm.author_user_id
left join agents pa on pa.id = pm.author_agent_id
where c.project_id = $1 and m.deleted_at is null
order by m.created_at desc, m.id desc
limit 10
`

type RecentProjectMessagesRow struct {
	ID                 pgtype.UUID        `json:"id"`
	ConversationID     pgtype.UUID        `json:"conversation_id"`
	Body               string             `json:"body"`
	Mentions           []byte             `json:"mentions"`
	Tags               []string           `json:"tags"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
	EditedAt           pgtype.Timestamptz `json:"edited_at"`
	DeletedAt          pgtype.Timestamptz `json:"deleted_at"`
	ParentID           pgtype.UUID        `json:"parent_id"`
	AuthorUserID       pgtype.UUID        `json:"author_user_id"`
	AuthorAgentID      pgtype.UUID        `json:"author_agent_id"`
	AuthorKindSnapshot string             `json:"author_kind_snapshot"`
	AuthorName         string             `json:"author_name"`
	AuthorAvatar       pgtype.Text        `json:"author_avatar"`
	ParentAuthorName   string             `json:"parent_author_name"`
	ParentBody         pgtype.Text        `json:"parent_body"`
	ParentDeleted      pgtype.Bool        `json:"parent_deleted"`
}

func (q *Queries) RecentProjectMessages(ctx context.Context, projectID pgtype.UUID) ([]RecentProjectMessagesRow, error) {
	rows, err := q.db.Query(ctx, recentProjectMessages, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []RecentProjectMessagesRow{}
	for rows.Next() {
		var i RecentProjectMessagesRow
		if err := rows.Scan(
			&i.ID,
			&i.ConversationID,
			&i.Body,
			&i.Mentions,
			&i.Tags,
			&i.CreatedAt,
			&i.EditedAt,
			&i.DeletedAt,
			&i.ParentID,
			&i.AuthorUserID,
			&i.AuthorAgentID,
			&i.AuthorKindSnapshot,
			&i.AuthorName,
			&i.AuthorAvatar,
			&i.ParentAuthorName,
			&i.ParentBody,
			&i.ParentDeleted,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeReactionUser = `-- name: RemoveReactionUser :execrows
delete from message_reactions
where message_id = $1 and user_id = $2 and emoji = $3
`

type RemoveReactionUserParams struct {
	MessageID pgtype.UUID `json:"message_id"`
	UserID    pgtype.UUID `json:"user_id"`
	Emoji     string      `json:"emoji"`
}

func (q *Queries) RemoveReactionUser(ctx context.Context, arg RemoveReactionUserParams) (int64, error) {
	result, err := q.db.Exec(ctx, removeReactionUser, arg.MessageID, arg.UserID, arg.Emoji)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const softDeleteMessage = `-- name: SoftDeleteMessage :one
update messages set deleted_at = now()
where id = $1
  and author_user_id = $2
  and deleted_at is null
returning id, conversation_id
`

type SoftDeleteMessageParams struct {
	ID           pgtype.UUID `json:"id"`
	AuthorUserID pgtype.UUID `json:"author_user_id"`
}

type SoftDeleteMessageRow struct {
	ID             pgtype.UUID `json:"id"`
	ConversationID pgtype.UUID `json:"conversation_id"`
}

// author-only soft delete; conversation id comes back for the SSE frame
func (q *Queries) SoftDeleteMessage(ctx context.Context, arg SoftDeleteMessageParams) (SoftDeleteMessageRow, error) {
	row := q.db.QueryRow(ctx, softDeleteMessage, arg.ID, arg.AuthorUserID)
	var i SoftDeleteMessageRow
	err := row.Scan(&i.ID, &i.ConversationID)
	return i, err
}

const softDeleteMessageAgent = `-- name: SoftDeleteMessageAgent :one
update messages set deleted_at = now()
where id = $1
  and author_agent_id = $2
  and deleted_at is null
returning id, conversation_id
`

type SoftDeleteMessageAgentParams struct {
	ID            pgtype.UUID `json:"id"`
	AuthorAgentID pgtype.UUID `json:"author_agent_id"`
}

type SoftDeleteMessageAgentRow struct {
	ID             pgtype.UUID `json:"id"`
	ConversationID pgtype.UUID `json:"conversation_id"`
}

// agent-author counterpart; the MCP delete_message tool uses this
func (q *Queries) SoftDeleteMessageAgent(ctx context.Context, arg SoftDeleteMessageAgentParams) (SoftDeleteMessageAgentRow, error) {
	row := q.db.QueryRow(ctx, softDeleteMessageAgent, arg.ID, arg.AuthorAgentID)
	var i SoftDeleteMessageAgentRow
	err := row.Scan(&i.ID, &i.ConversationID)
	return i, err
}

const unpinMessage = `-- name: UnpinMessage :one
update messages set pinned_at = null
where id = $1 and deleted_at is null
returning id, conversation_id
`

type UnpinMessageRow struct {
	ID             pgtype.UUID `json:"id"`
	ConversationID pgtype.UUID `json:"conversation_id"`
}

func (q *Queries) UnpinMessage(ctx context.Context, id pgtype.UUID) (UnpinMessageRow, error) {
	row := q.db.QueryRow(ctx, unpinMessage, id)
	var i UnpinMessageRow
	err := row.Scan(&i.ID, &i.ConversationID)
	return i, err
}

const unreadCounts = `-- name: UnreadCounts :many
select p.id as project_id, count(m.id)::int as unread
from projects p
join workspace_members wm on wm.workspace_id = p.workspace_id
  and wm.user_id = $1
join conversations c on c.project_id = p.id
join messages m on m.conversation_id = c.id and m.deleted_at is null
where (m.author_user_id is null or m.author_user_id <> $1)
  and not exists (
    select 1 from message_reads r
    where r.message_id = m.id and r.user_id = $1)
group by p.id
`

type UnreadCountsRow struct {
	ProjectID pgtype.UUID `json:"project_id"`
	Unread    int32       `json:"unread"`
}

// per-project count of messages the user hasn't read, excluding their own
func (q *Queries) UnreadCounts(ctx context.Context, userID pgtype.UUID) ([]UnreadCountsRow, error) {
	rows, err := q.db.Query(ctx, unreadCounts, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []UnreadCountsRow{}
	for rows.Next() {
		var i UnreadCountsRow
		if err := rows.Scan(&i.ProjectID, &i.Unread); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateMessageBody = `-- name: UpdateMessageBody :one
update messages set body = $1, edited_at = now()
where id = $2
  and author_user_id = $3
  and deleted_at is null
returning id
`

type UpdateMessageBodyParams struct {
	Body         string      `json:"body"`
	ID           pgtype.UUID `json:"id"`
	AuthorUserID pgtype.UUID `json:"author_user_id"`
}

// author-only edit; conversation id is resolved off the row afterwards
func (q *Queries) UpdateMessageBody(ctx context.Context, arg UpdateMessageBodyParams) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, updateMessageBody, arg.Body, arg.ID, arg.AuthorUserID)
	var id pgtype.UUID
	err := row.Scan(&id)
	return id, err
}
