// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: digest.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createPushDigest = `-- name: CreatePushDigest :exec
insert into push_digests (user_id, title, body, url)
values ($1, $2, $3, $4)
`

type CreatePushDigestParams struct {
	UserID pgtype.UUID `json:"user_id"`
	Title  string      `json:"title"`
	Body   string      `json:"body"`
	Url    string      `json:"url"`
}

func (q *Queries) CreatePushDigest(ctx context.Context, arg CreatePushDigestParams) error {
	_, err := q.db.Exec(ctx, createPushDigest,
		arg.UserID,
		arg.Title,
		arg.Body,
		arg.Url,
	)
	return err
}

const listPendingDigests = `-- name: ListPendingDigests :many
select id, user_id, title, body, url, created_at, flushed_at from push_digests
where flushed_at is null
order by created_at asc
`

// sweep input: every unflushed digest, grouped client-side by user
func (q *Queries) ListPendingDigests(ctx context.Context) ([]PushDigest, error) {
	rows, err := q.db.Query(ctx, listPendingDigests)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PushDigest{}
	for rows.Next() {
		var i PushDigest
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Title,
			&i.Body,
			&i.Url,
			&i.CreatedAt,
			&i.FlushedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markDigestsFlushed = `-- name: MarkDigestsFlushed :exec
update push_digests set flushed_at = now()
where user_id = $1 and flushed_at is null
`

func (q *Queries) MarkDigestsFlushed(ctx context.Context, userID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, markDigestsFlushed, userID)
	return err
}

const setUserDigest = `-- name: SetUserDigest :one
update users set digest_enabled = $1, updated_at = now()
where id = $2
returning id
`

type SetUserDigestParams struct {
	DigestEnabled bool        `json:"digest_enabled"`
	ID            pgtype.UUID `json:"id"`
}

func (q *Queries) SetUserDigest(ctx context.Context, arg SetUserDigestParams) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, setUserDigest, arg.DigestEnabled, arg.ID)
	var id pgtype.UUID
	err := row.Scan(&id)
	return id, err
}

const userDigestEnabled = `-- name: UserDigestEnabled :one
select digest_enabled from users where id = $1
`

func (q *Queries) UserDigestEnabled(ctx context.Context, id pgtype.UUID) (bool, error) {
	row := q.db.QueryRow(ctx, userDigestEnabled, id)
	var digest_enabled bool
	err := row.Scan(&digest_enabled)
	return digest_enabled, err
}
