// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: edits.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createMessageEdit = `-- name: CreateMessageEdit :exec
insert into message_edits (message_id, body, edited_by)
values ($1, $2, $3)
`

type CreateMessageEditParams struct {
	MessageID pgtype.UUID `json:"message_id"`
	Body      string      `json:"body"`
	EditedBy  pgtype.UUID `json:"edited_by"`
}

// snapshot of the pre-edit body; taken in handleEditMessage before the
// update lands so the history view can show every prior version.
func (q *Queries) CreateMessageEdit(ctx context.Context, arg CreateMessageEditParams) error {
	_, err := q.db.Exec(ctx, createMessageEdit, arg.MessageID, arg.Body, arg.EditedBy)
	return err
}

const listMessageEdits = `-- name: ListMessageEdits :many
select e.id, e.message_id, e.body, e.edited_by, e.edited_at, u.name as editor_name
from message_edits e
left join users u on u.id = e.edited_by
where e.message_id = $1
order by e.edited_at asc
`

type ListMessageEditsRow struct {
	ID         pgtype.UUID        `json:"id"`
	MessageID  pgtype.UUID        `json:"message_id"`
	Body       string             `json:"body"`
	EditedBy   pgtype.UUID        `json:"edited_by"`
	EditedAt   pgtype.Timestamptz `json:"edited_at"`
	EditorName pgtype.Text        `json:"editor_name"`
}

// oldest first — the UI renders a timeline
func (q *Queries) ListMessageEdits(ctx context.Context, messageID pgtype.UUID) ([]ListMessageEditsRow, error) {
	rows, err := q.db.Query(ctx, listMessageEdits, messageID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListMessageEditsRow{}
	for rows.Next() {
		var i ListMessageEditsRow
		if err := rows.Scan(
			&i.ID,
			&i.MessageID,
			&i.Body,
			&i.EditedBy,
			&i.EditedAt,
			&i.EditorName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
