// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: github.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createGitHubIssue = `-- name: CreateGitHubIssue :one
insert into issues (project_id, number, title, description, status, priority,
                    github_node_id, github_repo_id, github_number, origin,
                    github_kind, github_state, github_url)
values ($1, $2, $3, $4,
        $5, 'none', $6, $7, $8, 'github',
        $9, $10, $11)
returning id, project_id, number, title, description, status, priority, assignee_id, agent_id, created_by, created_at, updated_at, github_node_id, github_repo_id, github_number, origin, github_kind, github_state, github_url
`

type CreateGitHubIssueParams struct {
	ProjectID   pgtype.UUID `json:"project_id"`
	Number      int32       `json:"number"`
	Title       string      `json:"title"`
	Description string      `json:"description"`
	Status      string      `json:"status"`
	NodeID      pgtype.Text `json:"node_id"`
	RepoID      pgtype.UUID `json:"repo_id"`
	GhNumber    pgtype.Int4 `json:"gh_number"`
	Kind        string      `json:"kind"`
	GhState     pgtype.Text `json:"gh_state"`
	GhUrl       pgtype.Text `json:"gh_url"`
}

func (q *Queries) CreateGitHubIssue(ctx context.Context, arg CreateGitHubIssueParams) (Issue, error) {
	row := q.db.QueryRow(ctx, createGitHubIssue,
		arg.ProjectID,
		arg.Number,
		arg.Title,
		arg.Description,
		arg.Status,
		arg.NodeID,
		arg.RepoID,
		arg.GhNumber,
		arg.Kind,
		arg.GhState,
		arg.GhUrl,
	)
	var i Issue
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Number,
		&i.Title,
		&i.Description,
		&i.Status,
		&i.Priority,
		&i.AssigneeID,
		&i.AgentID,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.GithubNodeID,
		&i.GithubRepoID,
		&i.GithubNumber,
		&i.Origin,
		&i.GithubKind,
		&i.GithubState,
		&i.GithubUrl,
	)
	return i, err
}

const deleteGitHubApp = `-- name: DeleteGitHubApp :exec
delete from github_app
`

func (q *Queries) DeleteGitHubApp(ctx context.Context) error {
	_, err := q.db.Exec(ctx, deleteGitHubApp)
	return err
}

const deleteInstallation = `-- name: DeleteInstallation :exec
delete from github_installations where installation_id = $1
`

func (q *Queries) DeleteInstallation(ctx context.Context, installationID int64) error {
	_, err := q.db.Exec(ctx, deleteInstallation, installationID)
	return err
}

const deleteRepoLink = `-- name: DeleteRepoLink :exec
delete from repositories where id = $1
`

func (q *Queries) DeleteRepoLink(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteRepoLink, id)
	return err
}

const findIssueByGitHub = `-- name: FindIssueByGitHub :one
select id, project_id, number, title, description, status, priority, assignee_id, agent_id, created_by, created_at, updated_at, github_node_id, github_repo_id, github_number, origin, github_kind, github_state, github_url from issues
where github_repo_id = $1 and github_number = $2
`

type FindIssueByGitHubParams struct {
	RepoID pgtype.UUID `json:"repo_id"`
	Number pgtype.Int4 `json:"number"`
}

func (q *Queries) FindIssueByGitHub(ctx context.Context, arg FindIssueByGitHubParams) (Issue, error) {
	row := q.db.QueryRow(ctx, findIssueByGitHub, arg.RepoID, arg.Number)
	var i Issue
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Number,
		&i.Title,
		&i.Description,
		&i.Status,
		&i.Priority,
		&i.AssigneeID,
		&i.AgentID,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.GithubNodeID,
		&i.GithubRepoID,
		&i.GithubNumber,
		&i.Origin,
		&i.GithubKind,
		&i.GithubState,
		&i.GithubUrl,
	)
	return i, err
}

const getGitHubApp = `-- name: GetGitHubApp :one
select id, app_id, slug, name, client_id, client_secret_enc, private_key_enc, webhook_secret_enc, created_at from github_app where id = true
`

func (q *Queries) GetGitHubApp(ctx context.Context) (GithubApp, error) {
	row := q.db.QueryRow(ctx, getGitHubApp)
	var i GithubApp
	err := row.Scan(
		&i.ID,
		&i.AppID,
		&i.Slug,
		&i.Name,
		&i.ClientID,
		&i.ClientSecretEnc,
		&i.PrivateKeyEnc,
		&i.WebhookSecretEnc,
		&i.CreatedAt,
	)
	return i, err
}

const getInstallationByInstallID = `-- name: GetInstallationByInstallID :one
select id, workspace_id, installation_id, account_login, account_type, created_at from github_installations where installation_id = $1
`

func (q *Queries) GetInstallationByInstallID(ctx context.Context, installationID int64) (GithubInstallation, error) {
	row := q.db.QueryRow(ctx, getInstallationByInstallID, installationID)
	var i GithubInstallation
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.InstallationID,
		&i.AccountLogin,
		&i.AccountType,
		&i.CreatedAt,
	)
	return i, err
}

const getRepoByFullName = `-- name: GetRepoByFullName :one
select id, project_id, installation_id, owner, name, default_branch, linked_by, created_at from repositories where installation_id = $1
  and owner = $2 and name = $3
`

type GetRepoByFullNameParams struct {
	InstallationID int64  `json:"installation_id"`
	Owner          string `json:"owner"`
	Name           string `json:"name"`
}

func (q *Queries) GetRepoByFullName(ctx context.Context, arg GetRepoByFullNameParams) (Repository, error) {
	row := q.db.QueryRow(ctx, getRepoByFullName, arg.InstallationID, arg.Owner, arg.Name)
	var i Repository
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.InstallationID,
		&i.Owner,
		&i.Name,
		&i.DefaultBranch,
		&i.LinkedBy,
		&i.CreatedAt,
	)
	return i, err
}

const getRepoByID = `-- name: GetRepoByID :one
select id, project_id, installation_id, owner, name, default_branch, linked_by, created_at from repositories where id = $1
`

func (q *Queries) GetRepoByID(ctx context.Context, id pgtype.UUID) (Repository, error) {
	row := q.db.QueryRow(ctx, getRepoByID, id)
	var i Repository
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.InstallationID,
		&i.Owner,
		&i.Name,
		&i.DefaultBranch,
		&i.LinkedBy,
		&i.CreatedAt,
	)
	return i, err
}

const getRepoForIssue = `-- name: GetRepoForIssue :one
select r.id, r.project_id, r.installation_id, r.owner, r.name, r.default_branch, r.linked_by, r.created_at from repositories r
where r.installation_id = $1
  and r.owner = $2 and r.name = $3
`

type GetRepoForIssueParams struct {
	InstallationID int64  `json:"installation_id"`
	Owner          string `json:"owner"`
	Name           string `json:"name"`
}

func (q *Queries) GetRepoForIssue(ctx context.Context, arg GetRepoForIssueParams) (Repository, error) {
	row := q.db.QueryRow(ctx, getRepoForIssue, arg.InstallationID, arg.Owner, arg.Name)
	var i Repository
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.InstallationID,
		&i.Owner,
		&i.Name,
		&i.DefaultBranch,
		&i.LinkedBy,
		&i.CreatedAt,
	)
	return i, err
}

const hasGitHubEvent = `-- name: HasGitHubEvent :one
select exists(select 1 from github_events where delivery_id = $1)
`

func (q *Queries) HasGitHubEvent(ctx context.Context, deliveryID string) (bool, error) {
	row := q.db.QueryRow(ctx, hasGitHubEvent, deliveryID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const listInstallationsForWorkspace = `-- name: ListInstallationsForWorkspace :many
select id, workspace_id, installation_id, account_login, account_type, created_at from github_installations where workspace_id = $1
`

func (q *Queries) ListInstallationsForWorkspace(ctx context.Context, workspaceID pgtype.UUID) ([]GithubInstallation, error) {
	rows, err := q.db.Query(ctx, listInstallationsForWorkspace, workspaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GithubInstallation{}
	for rows.Next() {
		var i GithubInstallation
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.InstallationID,
			&i.AccountLogin,
			&i.AccountType,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProjectRepos = `-- name: ListProjectRepos :many
select id, project_id, installation_id, owner, name, default_branch, linked_by, created_at from repositories where project_id = $1 order by owner, name
`

func (q *Queries) ListProjectRepos(ctx context.Context, projectID pgtype.UUID) ([]Repository, error) {
	rows, err := q.db.Query(ctx, listProjectRepos, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Repository{}
	for rows.Next() {
		var i Repository
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.InstallationID,
			&i.Owner,
			&i.Name,
			&i.DefaultBranch,
			&i.LinkedBy,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProjectReposForWorkspace = `-- name: ListProjectReposForWorkspace :many
select r.id, r.project_id, r.installation_id, r.owner, r.name, r.default_branch, r.linked_by, r.created_at from repositories r
join projects p on p.id = r.project_id
where p.workspace_id = $1
order by r.owner, r.name
`

func (q *Queries) ListProjectReposForWorkspace(ctx context.Context, workspaceID pgtype.UUID) ([]Repository, error) {
	rows, err := q.db.Query(ctx, listProjectReposForWorkspace, workspaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Repository{}
	for rows.Next() {
		var i Repository
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.InstallationID,
			&i.Owner,
			&i.Name,
			&i.DefaultBranch,
			&i.LinkedBy,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const recordGitHubEvent = `-- name: RecordGitHubEvent :exec
insert into github_events (delivery_id, event)
values ($1, $2)
on conflict (delivery_id) do nothing
`

type RecordGitHubEventParams struct {
	DeliveryID string `json:"delivery_id"`
	Event      string `json:"event"`
}

func (q *Queries) RecordGitHubEvent(ctx context.Context, arg RecordGitHubEventParams) error {
	_, err := q.db.Exec(ctx, recordGitHubEvent, arg.DeliveryID, arg.Event)
	return err
}

const updateGitHubIssue = `-- name: UpdateGitHubIssue :one
update issues set
    title = coalesce($1::text, title),
    description = coalesce($2::text, description),
    status = coalesce($3::text, status),
    github_state = coalesce($4::text, github_state),
    github_url = coalesce($5::text, github_url),
    updated_at = now()
where id = $6
returning id, project_id, number, title, description, status, priority, assignee_id, agent_id, created_by, created_at, updated_at, github_node_id, github_repo_id, github_number, origin, github_kind, github_state, github_url
`

type UpdateGitHubIssueParams struct {
	Title       pgtype.Text `json:"title"`
	Description pgtype.Text `json:"description"`
	Status      pgtype.Text `json:"status"`
	GhState     pgtype.Text `json:"gh_state"`
	GhUrl       pgtype.Text `json:"gh_url"`
	ID          pgtype.UUID `json:"id"`
}

func (q *Queries) UpdateGitHubIssue(ctx context.Context, arg UpdateGitHubIssueParams) (Issue, error) {
	row := q.db.QueryRow(ctx, updateGitHubIssue,
		arg.Title,
		arg.Description,
		arg.Status,
		arg.GhState,
		arg.GhUrl,
		arg.ID,
	)
	var i Issue
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Number,
		&i.Title,
		&i.Description,
		&i.Status,
		&i.Priority,
		&i.AssigneeID,
		&i.AgentID,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.GithubNodeID,
		&i.GithubRepoID,
		&i.GithubNumber,
		&i.Origin,
		&i.GithubKind,
		&i.GithubState,
		&i.GithubUrl,
	)
	return i, err
}

const upsertGitHubApp = `-- name: UpsertGitHubApp :exec
insert into github_app (id, app_id, slug, name, client_id, client_secret_enc, private_key_enc, webhook_secret_enc)
values (true, $1, $2, $3, $4,
        $5, $6, $7)
on conflict (id) do update set
    app_id = excluded.app_id, slug = excluded.slug, name = excluded.name,
    client_id = excluded.client_id, client_secret_enc = excluded.client_secret_enc,
    private_key_enc = excluded.private_key_enc,
    webhook_secret_enc = excluded.webhook_secret_enc
`

type UpsertGitHubAppParams struct {
	AppID            int64  `json:"app_id"`
	Slug             string `json:"slug"`
	Name             string `json:"name"`
	ClientID         string `json:"client_id"`
	ClientSecretEnc  []byte `json:"client_secret_enc"`
	PrivateKeyEnc    []byte `json:"private_key_enc"`
	WebhookSecretEnc []byte `json:"webhook_secret_enc"`
}

func (q *Queries) UpsertGitHubApp(ctx context.Context, arg UpsertGitHubAppParams) error {
	_, err := q.db.Exec(ctx, upsertGitHubApp,
		arg.AppID,
		arg.Slug,
		arg.Name,
		arg.ClientID,
		arg.ClientSecretEnc,
		arg.PrivateKeyEnc,
		arg.WebhookSecretEnc,
	)
	return err
}

const upsertInstallation = `-- name: UpsertInstallation :one
insert into github_installations (workspace_id, installation_id, account_login, account_type)
values ($1, $2, $3, $4)
on conflict (installation_id) do update set account_login = excluded.account_login
returning id, workspace_id, installation_id, account_login, account_type, created_at
`

type UpsertInstallationParams struct {
	WorkspaceID    pgtype.UUID `json:"workspace_id"`
	InstallationID int64       `json:"installation_id"`
	AccountLogin   string      `json:"account_login"`
	AccountType    string      `json:"account_type"`
}

func (q *Queries) UpsertInstallation(ctx context.Context, arg UpsertInstallationParams) (GithubInstallation, error) {
	row := q.db.QueryRow(ctx, upsertInstallation,
		arg.WorkspaceID,
		arg.InstallationID,
		arg.AccountLogin,
		arg.AccountType,
	)
	var i GithubInstallation
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.InstallationID,
		&i.AccountLogin,
		&i.AccountType,
		&i.CreatedAt,
	)
	return i, err
}

const upsertRepoLink = `-- name: UpsertRepoLink :one
insert into repositories (project_id, installation_id, owner, name, default_branch, linked_by)
values ($1, $2, $3, $4,
        $5, $6)
on conflict (installation_id, owner, name) do update set project_id = excluded.project_id
returning id, project_id, installation_id, owner, name, default_branch, linked_by, created_at
`

type UpsertRepoLinkParams struct {
	ProjectID      pgtype.UUID `json:"project_id"`
	InstallationID int64       `json:"installation_id"`
	Owner          string      `json:"owner"`
	Name           string      `json:"name"`
	DefaultBranch  string      `json:"default_branch"`
	LinkedBy       pgtype.UUID `json:"linked_by"`
}

func (q *Queries) UpsertRepoLink(ctx context.Context, arg UpsertRepoLinkParams) (Repository, error) {
	row := q.db.QueryRow(ctx, upsertRepoLink,
		arg.ProjectID,
		arg.InstallationID,
		arg.Owner,
		arg.Name,
		arg.DefaultBranch,
		arg.LinkedBy,
	)
	var i Repository
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.InstallationID,
		&i.Owner,
		&i.Name,
		&i.DefaultBranch,
		&i.LinkedBy,
		&i.CreatedAt,
	)
	return i, err
}
