// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: ideas.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createIdea = `-- name: CreateIdea :one
insert into ideas (project_id, title, summary, scene, created_by_user, created_by_agent)
values ($1, $2, $3, $4,
        $5, $6)
returning id, project_id, title, summary, scene, status, created_by_user, created_by_agent, created_at, updated_at
`

type CreateIdeaParams struct {
	ProjectID      pgtype.UUID `json:"project_id"`
	Title          string      `json:"title"`
	Summary        string      `json:"summary"`
	Scene          []byte      `json:"scene"`
	CreatedByUser  pgtype.UUID `json:"created_by_user"`
	CreatedByAgent pgtype.UUID `json:"created_by_agent"`
}

func (q *Queries) CreateIdea(ctx context.Context, arg CreateIdeaParams) (Idea, error) {
	row := q.db.QueryRow(ctx, createIdea,
		arg.ProjectID,
		arg.Title,
		arg.Summary,
		arg.Scene,
		arg.CreatedByUser,
		arg.CreatedByAgent,
	)
	var i Idea
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Title,
		&i.Summary,
		&i.Scene,
		&i.Status,
		&i.CreatedByUser,
		&i.CreatedByAgent,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteIdea = `-- name: DeleteIdea :exec
delete from ideas where id = $1
`

func (q *Queries) DeleteIdea(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteIdea, id)
	return err
}

const getIdea = `-- name: GetIdea :one
select i.id, i.project_id, i.title, i.summary, i.scene, i.status, i.created_by_user, i.created_by_agent, i.created_at, i.updated_at, p.key as project_key, p.name as project_name,
       coalesce(u.name, a.name, '') as author_name,
       coalesce(u.id is not null, false) as author_is_user
from ideas i
join projects p on p.id = i.project_id
left join users u on u.id = i.created_by_user
left join agents a on a.id = i.created_by_agent
where i.id = $1
`

type GetIdeaRow struct {
	ID             pgtype.UUID        `json:"id"`
	ProjectID      pgtype.UUID        `json:"project_id"`
	Title          string             `json:"title"`
	Summary        string             `json:"summary"`
	Scene          []byte             `json:"scene"`
	Status         string             `json:"status"`
	CreatedByUser  pgtype.UUID        `json:"created_by_user"`
	CreatedByAgent pgtype.UUID        `json:"created_by_agent"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
	ProjectKey     string             `json:"project_key"`
	ProjectName    string             `json:"project_name"`
	AuthorName     string             `json:"author_name"`
	AuthorIsUser   interface{}        `json:"author_is_user"`
}

func (q *Queries) GetIdea(ctx context.Context, id pgtype.UUID) (GetIdeaRow, error) {
	row := q.db.QueryRow(ctx, getIdea, id)
	var i GetIdeaRow
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Title,
		&i.Summary,
		&i.Scene,
		&i.Status,
		&i.CreatedByUser,
		&i.CreatedByAgent,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ProjectKey,
		&i.ProjectName,
		&i.AuthorName,
		&i.AuthorIsUser,
	)
	return i, err
}

const listProjectIdeas = `-- name: ListProjectIdeas :many
select i.id, i.project_id, i.title, i.summary, i.scene, i.status, i.created_by_user, i.created_by_agent, i.created_at, i.updated_at, p.key as project_key, p.name as project_name,
       coalesce(u.name, a.name, '') as author_name
from ideas i
join projects p on p.id = i.project_id
left join users u on u.id = i.created_by_user
left join agents a on a.id = i.created_by_agent
where i.project_id = $1
order by i.updated_at desc
`

type ListProjectIdeasRow struct {
	ID             pgtype.UUID        `json:"id"`
	ProjectID      pgtype.UUID        `json:"project_id"`
	Title          string             `json:"title"`
	Summary        string             `json:"summary"`
	Scene          []byte             `json:"scene"`
	Status         string             `json:"status"`
	CreatedByUser  pgtype.UUID        `json:"created_by_user"`
	CreatedByAgent pgtype.UUID        `json:"created_by_agent"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
	ProjectKey     string             `json:"project_key"`
	ProjectName    string             `json:"project_name"`
	AuthorName     string             `json:"author_name"`
}

func (q *Queries) ListProjectIdeas(ctx context.Context, projectID pgtype.UUID) ([]ListProjectIdeasRow, error) {
	rows, err := q.db.Query(ctx, listProjectIdeas, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListProjectIdeasRow{}
	for rows.Next() {
		var i ListProjectIdeasRow
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.Title,
			&i.Summary,
			&i.Scene,
			&i.Status,
			&i.CreatedByUser,
			&i.CreatedByAgent,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ProjectKey,
			&i.ProjectName,
			&i.AuthorName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWorkspaceIdeas = `-- name: ListWorkspaceIdeas :many
select i.id, i.project_id, i.title, i.summary, i.scene, i.status, i.created_by_user, i.created_by_agent, i.created_at, i.updated_at, p.key as project_key, p.name as project_name,
       coalesce(u.name, a.name, '') as author_name
from ideas i
join projects p on p.id = i.project_id
left join users u on u.id = i.created_by_user
left join agents a on a.id = i.created_by_agent
where p.workspace_id = $1
order by i.updated_at desc
`

type ListWorkspaceIdeasRow struct {
	ID             pgtype.UUID        `json:"id"`
	ProjectID      pgtype.UUID        `json:"project_id"`
	Title          string             `json:"title"`
	Summary        string             `json:"summary"`
	Scene          []byte             `json:"scene"`
	Status         string             `json:"status"`
	CreatedByUser  pgtype.UUID        `json:"created_by_user"`
	CreatedByAgent pgtype.UUID        `json:"created_by_agent"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
	ProjectKey     string             `json:"project_key"`
	ProjectName    string             `json:"project_name"`
	AuthorName     string             `json:"author_name"`
}

// every idea across the projects in one workspace — the Ideas page feed.
// Membership is enforced by the route gate; the query just scopes the rows.
func (q *Queries) ListWorkspaceIdeas(ctx context.Context, workspaceID pgtype.UUID) ([]ListWorkspaceIdeasRow, error) {
	rows, err := q.db.Query(ctx, listWorkspaceIdeas, workspaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListWorkspaceIdeasRow{}
	for rows.Next() {
		var i ListWorkspaceIdeasRow
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.Title,
			&i.Summary,
			&i.Scene,
			&i.Status,
			&i.CreatedByUser,
			&i.CreatedByAgent,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ProjectKey,
			&i.ProjectName,
			&i.AuthorName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateIdea = `-- name: UpdateIdea :one
update ideas set
  title   = coalesce($1, title),
  summary = coalesce($2, summary),
  scene   = coalesce($3, scene),
  status  = coalesce($4, status),
  updated_at = now()
where id = $5
returning id, project_id, title, summary, scene, status, created_by_user, created_by_agent, created_at, updated_at
`

type UpdateIdeaParams struct {
	Title   pgtype.Text `json:"title"`
	Summary pgtype.Text `json:"summary"`
	Scene   []byte      `json:"scene"`
	Status  pgtype.Text `json:"status"`
	ID      pgtype.UUID `json:"id"`
}

func (q *Queries) UpdateIdea(ctx context.Context, arg UpdateIdeaParams) (Idea, error) {
	row := q.db.QueryRow(ctx, updateIdea,
		arg.Title,
		arg.Summary,
		arg.Scene,
		arg.Status,
		arg.ID,
	)
	var i Idea
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Title,
		&i.Summary,
		&i.Scene,
		&i.Status,
		&i.CreatedByUser,
		&i.CreatedByAgent,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
