// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: issues.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countLabelsInProject = `-- name: CountLabelsInProject :one
select count(*) from issue_labels
where project_id = $1 and id = any($2::uuid[])
`

type CountLabelsInProjectParams struct {
	ProjectID pgtype.UUID   `json:"project_id"`
	Ids       []pgtype.UUID `json:"ids"`
}

func (q *Queries) CountLabelsInProject(ctx context.Context, arg CountLabelsInProjectParams) (int64, error) {
	row := q.db.QueryRow(ctx, countLabelsInProject, arg.ProjectID, arg.Ids)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createIssue = `-- name: CreateIssue :one
insert into issues (project_id, number, title, description, status, priority, assignee_id, created_by)
values ($1, $2, $3, $4,
        $5, $6, $7, $8)
returning id, project_id, number, title, description, status, priority, assignee_id, agent_id, created_by, created_at, updated_at, github_node_id, github_repo_id, github_number, origin, github_kind, github_state, github_url
`

type CreateIssueParams struct {
	ProjectID   pgtype.UUID `json:"project_id"`
	Number      int32       `json:"number"`
	Title       string      `json:"title"`
	Description string      `json:"description"`
	Status      string      `json:"status"`
	Priority    string      `json:"priority"`
	AssigneeID  pgtype.UUID `json:"assignee_id"`
	CreatedBy   pgtype.UUID `json:"created_by"`
}

func (q *Queries) CreateIssue(ctx context.Context, arg CreateIssueParams) (Issue, error) {
	row := q.db.QueryRow(ctx, createIssue,
		arg.ProjectID,
		arg.Number,
		arg.Title,
		arg.Description,
		arg.Status,
		arg.Priority,
		arg.AssigneeID,
		arg.CreatedBy,
	)
	var i Issue
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Number,
		&i.Title,
		&i.Description,
		&i.Status,
		&i.Priority,
		&i.AssigneeID,
		&i.AgentID,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.GithubNodeID,
		&i.GithubRepoID,
		&i.GithubNumber,
		&i.Origin,
		&i.GithubKind,
		&i.GithubState,
		&i.GithubUrl,
	)
	return i, err
}

const createIssueConversation = `-- name: CreateIssueConversation :one
insert into conversations (project_id, kind, issue_id)
values ($1, 'issue', $2)
returning id, project_id, kind, issue_id, created_at, brief_id, parent_message_id, title, created_by_user, created_by_agent, creator_name_snapshot, expires_at, agents_blocked
`

type CreateIssueConversationParams struct {
	ProjectID pgtype.UUID `json:"project_id"`
	IssueID   pgtype.UUID `json:"issue_id"`
}

func (q *Queries) CreateIssueConversation(ctx context.Context, arg CreateIssueConversationParams) (Conversation, error) {
	row := q.db.QueryRow(ctx, createIssueConversation, arg.ProjectID, arg.IssueID)
	var i Conversation
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Kind,
		&i.IssueID,
		&i.CreatedAt,
		&i.BriefID,
		&i.ParentMessageID,
		&i.Title,
		&i.CreatedByUser,
		&i.CreatedByAgent,
		&i.CreatorNameSnapshot,
		&i.ExpiresAt,
		&i.AgentsBlocked,
	)
	return i, err
}

const createLabel = `-- name: CreateLabel :one
insert into issue_labels (project_id, name, color)
values ($1, $2, $3)
returning id, project_id, name, color, created_at
`

type CreateLabelParams struct {
	ProjectID pgtype.UUID `json:"project_id"`
	Name      string      `json:"name"`
	Color     string      `json:"color"`
}

func (q *Queries) CreateLabel(ctx context.Context, arg CreateLabelParams) (IssueLabel, error) {
	row := q.db.QueryRow(ctx, createLabel, arg.ProjectID, arg.Name, arg.Color)
	var i IssueLabel
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Name,
		&i.Color,
		&i.CreatedAt,
	)
	return i, err
}

const getIssueByID = `-- name: GetIssueByID :one
select i.id, i.project_id, i.number, i.title, i.description, i.status, i.priority, i.assignee_id, i.agent_id, i.created_by, i.created_at, i.updated_at, i.github_node_id, i.github_repo_id, i.github_number, i.origin, i.github_kind, i.github_state, i.github_url, u.name as assignee_name, u.avatar_key as assignee_avatar,
       gr.owner as github_repo_owner, gr.name as github_repo_name
from issues i
left join users u on u.id = i.assignee_id
left join repositories gr on gr.id = i.github_repo_id
where i.id = $1
`

type GetIssueByIDRow struct {
	ID              pgtype.UUID        `json:"id"`
	ProjectID       pgtype.UUID        `json:"project_id"`
	Number          int32              `json:"number"`
	Title           string             `json:"title"`
	Description     string             `json:"description"`
	Status          string             `json:"status"`
	Priority        string             `json:"priority"`
	AssigneeID      pgtype.UUID        `json:"assignee_id"`
	AgentID         pgtype.UUID        `json:"agent_id"`
	CreatedBy       pgtype.UUID        `json:"created_by"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
	GithubNodeID    pgtype.Text        `json:"github_node_id"`
	GithubRepoID    pgtype.UUID        `json:"github_repo_id"`
	GithubNumber    pgtype.Int4        `json:"github_number"`
	Origin          string             `json:"origin"`
	GithubKind      string             `json:"github_kind"`
	GithubState     pgtype.Text        `json:"github_state"`
	GithubUrl       pgtype.Text        `json:"github_url"`
	AssigneeName    pgtype.Text        `json:"assignee_name"`
	AssigneeAvatar  pgtype.Text        `json:"assignee_avatar"`
	GithubRepoOwner pgtype.Text        `json:"github_repo_owner"`
	GithubRepoName  pgtype.Text        `json:"github_repo_name"`
}

func (q *Queries) GetIssueByID(ctx context.Context, id pgtype.UUID) (GetIssueByIDRow, error) {
	row := q.db.QueryRow(ctx, getIssueByID, id)
	var i GetIssueByIDRow
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Number,
		&i.Title,
		&i.Description,
		&i.Status,
		&i.Priority,
		&i.AssigneeID,
		&i.AgentID,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.GithubNodeID,
		&i.GithubRepoID,
		&i.GithubNumber,
		&i.Origin,
		&i.GithubKind,
		&i.GithubState,
		&i.GithubUrl,
		&i.AssigneeName,
		&i.AssigneeAvatar,
		&i.GithubRepoOwner,
		&i.GithubRepoName,
	)
	return i, err
}

const getIssueConversation = `-- name: GetIssueConversation :one
select id, project_id, kind, issue_id, created_at, brief_id, parent_message_id, title, created_by_user, created_by_agent, creator_name_snapshot, expires_at, agents_blocked from conversations where issue_id = $1 and kind = 'issue'
`

func (q *Queries) GetIssueConversation(ctx context.Context, issueID pgtype.UUID) (Conversation, error) {
	row := q.db.QueryRow(ctx, getIssueConversation, issueID)
	var i Conversation
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Kind,
		&i.IssueID,
		&i.CreatedAt,
		&i.BriefID,
		&i.ParentMessageID,
		&i.Title,
		&i.CreatedByUser,
		&i.CreatedByAgent,
		&i.CreatorNameSnapshot,
		&i.ExpiresAt,
		&i.AgentsBlocked,
	)
	return i, err
}

const getIssueForUser = `-- name: GetIssueForUser :one
select i.id, i.project_id, i.number, i.title, i.description, i.status, i.priority, i.assignee_id, i.agent_id, i.created_by, i.created_at, i.updated_at, i.github_node_id, i.github_repo_id, i.github_number, i.origin, i.github_kind, i.github_state, i.github_url, u.name as assignee_name, u.avatar_key as assignee_avatar,
       gr.owner as github_repo_owner, gr.name as github_repo_name,
       gr.installation_id as github_installation_id
from issues i
join projects p on p.id = i.project_id
join workspace_members wm on wm.workspace_id = p.workspace_id and wm.user_id = $1
left join users u on u.id = i.assignee_id
left join repositories gr on gr.id = i.github_repo_id
where i.id = $2
`

type GetIssueForUserParams struct {
	UserID pgtype.UUID `json:"user_id"`
	ID     pgtype.UUID `json:"id"`
}

type GetIssueForUserRow struct {
	ID                   pgtype.UUID        `json:"id"`
	ProjectID            pgtype.UUID        `json:"project_id"`
	Number               int32              `json:"number"`
	Title                string             `json:"title"`
	Description          string             `json:"description"`
	Status               string             `json:"status"`
	Priority             string             `json:"priority"`
	AssigneeID           pgtype.UUID        `json:"assignee_id"`
	AgentID              pgtype.UUID        `json:"agent_id"`
	CreatedBy            pgtype.UUID        `json:"created_by"`
	CreatedAt            pgtype.Timestamptz `json:"created_at"`
	UpdatedAt            pgtype.Timestamptz `json:"updated_at"`
	GithubNodeID         pgtype.Text        `json:"github_node_id"`
	GithubRepoID         pgtype.UUID        `json:"github_repo_id"`
	GithubNumber         pgtype.Int4        `json:"github_number"`
	Origin               string             `json:"origin"`
	GithubKind           string             `json:"github_kind"`
	GithubState          pgtype.Text        `json:"github_state"`
	GithubUrl            pgtype.Text        `json:"github_url"`
	AssigneeName         pgtype.Text        `json:"assignee_name"`
	AssigneeAvatar       pgtype.Text        `json:"assignee_avatar"`
	GithubRepoOwner      pgtype.Text        `json:"github_repo_owner"`
	GithubRepoName       pgtype.Text        `json:"github_repo_name"`
	GithubInstallationID pgtype.Int8        `json:"github_installation_id"`
}

func (q *Queries) GetIssueForUser(ctx context.Context, arg GetIssueForUserParams) (GetIssueForUserRow, error) {
	row := q.db.QueryRow(ctx, getIssueForUser, arg.UserID, arg.ID)
	var i GetIssueForUserRow
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Number,
		&i.Title,
		&i.Description,
		&i.Status,
		&i.Priority,
		&i.AssigneeID,
		&i.AgentID,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.GithubNodeID,
		&i.GithubRepoID,
		&i.GithubNumber,
		&i.Origin,
		&i.GithubKind,
		&i.GithubState,
		&i.GithubUrl,
		&i.AssigneeName,
		&i.AssigneeAvatar,
		&i.GithubRepoOwner,
		&i.GithubRepoName,
		&i.GithubInstallationID,
	)
	return i, err
}

const getLabelByName = `-- name: GetLabelByName :one
select id, project_id, name, color, created_at from issue_labels
where project_id = $1 and lower(name) = lower($2)
`

type GetLabelByNameParams struct {
	ProjectID pgtype.UUID `json:"project_id"`
	Name      string      `json:"name"`
}

func (q *Queries) GetLabelByName(ctx context.Context, arg GetLabelByNameParams) (IssueLabel, error) {
	row := q.db.QueryRow(ctx, getLabelByName, arg.ProjectID, arg.Name)
	var i IssueLabel
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Name,
		&i.Color,
		&i.CreatedAt,
	)
	return i, err
}

const getMessageWithProjectForUser = `-- name: GetMessageWithProjectForUser :one
select m.id, m.body, c.project_id
from messages m
join conversations c on c.id = m.conversation_id
join projects p on p.id = c.project_id
join workspace_members wm on wm.workspace_id = p.workspace_id and wm.user_id = $1
where m.id = $2
`

type GetMessageWithProjectForUserParams struct {
	UserID pgtype.UUID `json:"user_id"`
	ID     pgtype.UUID `json:"id"`
}

type GetMessageWithProjectForUserRow struct {
	ID        pgtype.UUID `json:"id"`
	Body      string      `json:"body"`
	ProjectID pgtype.UUID `json:"project_id"`
}

// message row + owning project, only when the caller is a workspace member
func (q *Queries) GetMessageWithProjectForUser(ctx context.Context, arg GetMessageWithProjectForUserParams) (GetMessageWithProjectForUserRow, error) {
	row := q.db.QueryRow(ctx, getMessageWithProjectForUser, arg.UserID, arg.ID)
	var i GetMessageWithProjectForUserRow
	err := row.Scan(&i.ID, &i.Body, &i.ProjectID)
	return i, err
}

const insertLabelIfMissing = `-- name: InsertLabelIfMissing :exec
insert into issue_labels (project_id, name, color)
values ($1, $2, $3)
on conflict do nothing
`

type InsertLabelIfMissingParams struct {
	ProjectID pgtype.UUID `json:"project_id"`
	Name      string      `json:"name"`
	Color     string      `json:"color"`
}

// on conflict do nothing covers the (project_id, lower(name)) expression index
func (q *Queries) InsertLabelIfMissing(ctx context.Context, arg InsertLabelIfMissingParams) error {
	_, err := q.db.Exec(ctx, insertLabelIfMissing, arg.ProjectID, arg.Name, arg.Color)
	return err
}

const linkIssueLabel = `-- name: LinkIssueLabel :exec
insert into issue_label_links (issue_id, label_id)
values ($1, $2)
on conflict do nothing
`

type LinkIssueLabelParams struct {
	IssueID pgtype.UUID `json:"issue_id"`
	LabelID pgtype.UUID `json:"label_id"`
}

func (q *Queries) LinkIssueLabel(ctx context.Context, arg LinkIssueLabelParams) error {
	_, err := q.db.Exec(ctx, linkIssueLabel, arg.IssueID, arg.LabelID)
	return err
}

const listIssueActivity = `-- name: ListIssueActivity :many
select a.id, a.issue_id, a.actor_user_id, a.actor_agent_id, a.kind, a.payload, a.created_at, u.name as actor_name, u.avatar_key as actor_avatar
from issue_activity a
left join users u on u.id = a.actor_user_id
where a.issue_id = $1
order by a.created_at desc
limit 100
`

type ListIssueActivityRow struct {
	ID           pgtype.UUID        `json:"id"`
	IssueID      pgtype.UUID        `json:"issue_id"`
	ActorUserID  pgtype.UUID        `json:"actor_user_id"`
	ActorAgentID pgtype.UUID        `json:"actor_agent_id"`
	Kind         string             `json:"kind"`
	Payload      []byte             `json:"payload"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	ActorName    pgtype.Text        `json:"actor_name"`
	ActorAvatar  pgtype.Text        `json:"actor_avatar"`
}

func (q *Queries) ListIssueActivity(ctx context.Context, issueID pgtype.UUID) ([]ListIssueActivityRow, error) {
	rows, err := q.db.Query(ctx, listIssueActivity, issueID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListIssueActivityRow{}
	for rows.Next() {
		var i ListIssueActivityRow
		if err := rows.Scan(
			&i.ID,
			&i.IssueID,
			&i.ActorUserID,
			&i.ActorAgentID,
			&i.Kind,
			&i.Payload,
			&i.CreatedAt,
			&i.ActorName,
			&i.ActorAvatar,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listIssueLabels = `-- name: ListIssueLabels :many
select l.id, l.project_id, l.name, l.color, l.created_at from issue_label_links ll
join issue_labels l on l.id = ll.label_id
where ll.issue_id = $1
order by lower(l.name)
`

func (q *Queries) ListIssueLabels(ctx context.Context, issueID pgtype.UUID) ([]IssueLabel, error) {
	rows, err := q.db.Query(ctx, listIssueLabels, issueID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []IssueLabel{}
	for rows.Next() {
		var i IssueLabel
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.Name,
			&i.Color,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listIssuesForUser = `-- name: ListIssuesForUser :many
select i.id, i.project_id, i.number, i.title, i.description, i.status, i.priority, i.assignee_id, i.agent_id, i.created_by, i.created_at, i.updated_at, i.github_node_id, i.github_repo_id, i.github_number, i.origin, i.github_kind, i.github_state, i.github_url, u.name as assignee_name, u.avatar_key as assignee_avatar,
       gr.owner as github_repo_owner, gr.name as github_repo_name
from issues i
join projects p on p.id = i.project_id
join workspace_members wm on wm.workspace_id = p.workspace_id and wm.user_id = $1
left join users u on u.id = i.assignee_id
left join repositories gr on gr.id = i.github_repo_id
where i.project_id = $2
  and ($3::text is null or i.status = $3)
  and ($4::uuid is null or i.assignee_id = $4)
  and ($5::uuid is null or exists (
        select 1 from issue_label_links ll
        where ll.issue_id = i.id and ll.label_id = $5))
  and ($6::text is null or i.title ilike '%' || $6 || '%')
order by i.number desc
`

type ListIssuesForUserParams struct {
	UserID    pgtype.UUID `json:"user_id"`
	ProjectID pgtype.UUID `json:"project_id"`
	Status    pgtype.Text `json:"status"`
	Assignee  pgtype.UUID `json:"assignee"`
	Label     pgtype.UUID `json:"label"`
	Q         pgtype.Text `json:"q"`
}

type ListIssuesForUserRow struct {
	ID              pgtype.UUID        `json:"id"`
	ProjectID       pgtype.UUID        `json:"project_id"`
	Number          int32              `json:"number"`
	Title           string             `json:"title"`
	Description     string             `json:"description"`
	Status          string             `json:"status"`
	Priority        string             `json:"priority"`
	AssigneeID      pgtype.UUID        `json:"assignee_id"`
	AgentID         pgtype.UUID        `json:"agent_id"`
	CreatedBy       pgtype.UUID        `json:"created_by"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
	GithubNodeID    pgtype.Text        `json:"github_node_id"`
	GithubRepoID    pgtype.UUID        `json:"github_repo_id"`
	GithubNumber    pgtype.Int4        `json:"github_number"`
	Origin          string             `json:"origin"`
	GithubKind      string             `json:"github_kind"`
	GithubState     pgtype.Text        `json:"github_state"`
	GithubUrl       pgtype.Text        `json:"github_url"`
	AssigneeName    pgtype.Text        `json:"assignee_name"`
	AssigneeAvatar  pgtype.Text        `json:"assignee_avatar"`
	GithubRepoOwner pgtype.Text        `json:"github_repo_owner"`
	GithubRepoName  pgtype.Text        `json:"github_repo_name"`
}

func (q *Queries) ListIssuesForUser(ctx context.Context, arg ListIssuesForUserParams) ([]ListIssuesForUserRow, error) {
	rows, err := q.db.Query(ctx, listIssuesForUser,
		arg.UserID,
		arg.ProjectID,
		arg.Status,
		arg.Assignee,
		arg.Label,
		arg.Q,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListIssuesForUserRow{}
	for rows.Next() {
		var i ListIssuesForUserRow
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.Number,
			&i.Title,
			&i.Description,
			&i.Status,
			&i.Priority,
			&i.AssigneeID,
			&i.AgentID,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.GithubNodeID,
			&i.GithubRepoID,
			&i.GithubNumber,
			&i.Origin,
			&i.GithubKind,
			&i.GithubState,
			&i.GithubUrl,
			&i.AssigneeName,
			&i.AssigneeAvatar,
			&i.GithubRepoOwner,
			&i.GithubRepoName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLabelsForIssues = `-- name: ListLabelsForIssues :many
select l.id, l.project_id, l.name, l.color, l.created_at, ll.issue_id from issue_label_links ll
join issue_labels l on l.id = ll.label_id
where ll.issue_id = any($1::uuid[])
`

type ListLabelsForIssuesRow struct {
	ID        pgtype.UUID        `json:"id"`
	ProjectID pgtype.UUID        `json:"project_id"`
	Name      string             `json:"name"`
	Color     string             `json:"color"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	IssueID   pgtype.UUID        `json:"issue_id"`
}

func (q *Queries) ListLabelsForIssues(ctx context.Context, ids []pgtype.UUID) ([]ListLabelsForIssuesRow, error) {
	rows, err := q.db.Query(ctx, listLabelsForIssues, ids)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListLabelsForIssuesRow{}
	for rows.Next() {
		var i ListLabelsForIssuesRow
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.Name,
			&i.Color,
			&i.CreatedAt,
			&i.IssueID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProjectIssueActivity = `-- name: ListProjectIssueActivity :many
select a.id, a.issue_id, a.kind, a.payload, a.created_at,
       i.number as issue_number, i.title as issue_title,
       u.name as actor_name
from issue_activity a
join issues i on i.id = a.issue_id
left join users u on u.id = a.actor_user_id
where i.project_id = $1
order by a.created_at desc
limit 20
`

type ListProjectIssueActivityRow struct {
	ID          pgtype.UUID        `json:"id"`
	IssueID     pgtype.UUID        `json:"issue_id"`
	Kind        string             `json:"kind"`
	Payload     []byte             `json:"payload"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	IssueNumber int32              `json:"issue_number"`
	IssueTitle  string             `json:"issue_title"`
	ActorName   pgtype.Text        `json:"actor_name"`
}

// project-wide feed: latest issue events for the overview page
func (q *Queries) ListProjectIssueActivity(ctx context.Context, projectID pgtype.UUID) ([]ListProjectIssueActivityRow, error) {
	rows, err := q.db.Query(ctx, listProjectIssueActivity, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListProjectIssueActivityRow{}
	for rows.Next() {
		var i ListProjectIssueActivityRow
		if err := rows.Scan(
			&i.ID,
			&i.IssueID,
			&i.Kind,
			&i.Payload,
			&i.CreatedAt,
			&i.IssueNumber,
			&i.IssueTitle,
			&i.ActorName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProjectLabels = `-- name: ListProjectLabels :many
select id, project_id, name, color, created_at from issue_labels where project_id = $1 order by lower(name)
`

func (q *Queries) ListProjectLabels(ctx context.Context, projectID pgtype.UUID) ([]IssueLabel, error) {
	rows, err := q.db.Query(ctx, listProjectLabels, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []IssueLabel{}
	for rows.Next() {
		var i IssueLabel
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.Name,
			&i.Color,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const nextIssueNumber = `-- name: NextIssueNumber :one
insert into project_counters (project_id, next_issue_number)
values ($1, 2)
on conflict (project_id) do update
    set next_issue_number = project_counters.next_issue_number + 1
returning next_issue_number - 1 as number
`

// atomic per-project counter; safe under concurrent creates
func (q *Queries) NextIssueNumber(ctx context.Context, projectID pgtype.UUID) (int32, error) {
	row := q.db.QueryRow(ctx, nextIssueNumber, projectID)
	var number int32
	err := row.Scan(&number)
	return number, err
}

const recordIssueActivity = `-- name: RecordIssueActivity :one
insert into issue_activity (issue_id, actor_user_id, kind, payload)
values ($1, $2, $3, $4)
returning id, issue_id, actor_user_id, actor_agent_id, kind, payload, created_at
`

type RecordIssueActivityParams struct {
	IssueID     pgtype.UUID `json:"issue_id"`
	ActorUserID pgtype.UUID `json:"actor_user_id"`
	Kind        string      `json:"kind"`
	Payload     []byte      `json:"payload"`
}

func (q *Queries) RecordIssueActivity(ctx context.Context, arg RecordIssueActivityParams) (IssueActivity, error) {
	row := q.db.QueryRow(ctx, recordIssueActivity,
		arg.IssueID,
		arg.ActorUserID,
		arg.Kind,
		arg.Payload,
	)
	var i IssueActivity
	err := row.Scan(
		&i.ID,
		&i.IssueID,
		&i.ActorUserID,
		&i.ActorAgentID,
		&i.Kind,
		&i.Payload,
		&i.CreatedAt,
	)
	return i, err
}

const replaceIssueLabelLinks = `-- name: ReplaceIssueLabelLinks :exec
delete from issue_label_links where issue_id = $1
`

func (q *Queries) ReplaceIssueLabelLinks(ctx context.Context, issueID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, replaceIssueLabelLinks, issueID)
	return err
}

const setIssueAssignee = `-- name: SetIssueAssignee :exec
update issues set assignee_id = $1, updated_at = now()
where id = $2
`

type SetIssueAssigneeParams struct {
	AssigneeID pgtype.UUID `json:"assignee_id"`
	ID         pgtype.UUID `json:"id"`
}

func (q *Queries) SetIssueAssignee(ctx context.Context, arg SetIssueAssigneeParams) error {
	_, err := q.db.Exec(ctx, setIssueAssignee, arg.AssigneeID, arg.ID)
	return err
}

const setIssueGitHub = `-- name: SetIssueGitHub :exec
update issues set
    github_repo_id = $1,
    github_number = $2,
    github_node_id = $3,
    updated_at = now()
where id = $4
`

type SetIssueGitHubParams struct {
	GithubRepoID pgtype.UUID `json:"github_repo_id"`
	GithubNumber pgtype.Int4 `json:"github_number"`
	GithubNodeID pgtype.Text `json:"github_node_id"`
	ID           pgtype.UUID `json:"id"`
}

// link a relay issue to its GitHub counterpart (write-back)
func (q *Queries) SetIssueGitHub(ctx context.Context, arg SetIssueGitHubParams) error {
	_, err := q.db.Exec(ctx, setIssueGitHub,
		arg.GithubRepoID,
		arg.GithubNumber,
		arg.GithubNodeID,
		arg.ID,
	)
	return err
}

const touchIssue = `-- name: TouchIssue :exec
update issues set updated_at = now() where id = $1
`

func (q *Queries) TouchIssue(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, touchIssue, id)
	return err
}

const updateIssueFields = `-- name: UpdateIssueFields :one
update issues set
    title = coalesce($1, title),
    description = coalesce($2, description),
    status = coalesce($3, status),
    priority = coalesce($4, priority),
    updated_at = now()
where id = $5
returning id, project_id, number, title, description, status, priority, assignee_id, agent_id, created_by, created_at, updated_at, github_node_id, github_repo_id, github_number, origin, github_kind, github_state, github_url
`

type UpdateIssueFieldsParams struct {
	Title       pgtype.Text `json:"title"`
	Description pgtype.Text `json:"description"`
	Status      pgtype.Text `json:"status"`
	Priority    pgtype.Text `json:"priority"`
	ID          pgtype.UUID `json:"id"`
}

func (q *Queries) UpdateIssueFields(ctx context.Context, arg UpdateIssueFieldsParams) (Issue, error) {
	row := q.db.QueryRow(ctx, updateIssueFields,
		arg.Title,
		arg.Description,
		arg.Status,
		arg.Priority,
		arg.ID,
	)
	var i Issue
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Number,
		&i.Title,
		&i.Description,
		&i.Status,
		&i.Priority,
		&i.AssigneeID,
		&i.AgentID,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.GithubNodeID,
		&i.GithubRepoID,
		&i.GithubNumber,
		&i.Origin,
		&i.GithubKind,
		&i.GithubState,
		&i.GithubUrl,
	)
	return i, err
}

const userInProjectWorkspace = `-- name: UserInProjectWorkspace :one
select exists (
    select 1 from projects p
    join workspace_members wm on wm.workspace_id = p.workspace_id
    where p.id = $1 and wm.user_id = $2
)
`

type UserInProjectWorkspaceParams struct {
	ProjectID pgtype.UUID `json:"project_id"`
	MemberID  pgtype.UUID `json:"member_id"`
}

func (q *Queries) UserInProjectWorkspace(ctx context.Context, arg UserInProjectWorkspaceParams) (bool, error) {
	row := q.db.QueryRow(ctx, userInProjectWorkspace, arg.ProjectID, arg.MemberID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}
