// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: mcp.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const addReactionAgent = `-- name: AddReactionAgent :exec
insert into message_reactions (message_id, agent_id, emoji)
values ($1, $2, $3)
on conflict (message_id, agent_id, emoji) where agent_id is not null do nothing
`

type AddReactionAgentParams struct {
	MessageID pgtype.UUID `json:"message_id"`
	AgentID   pgtype.UUID `json:"agent_id"`
	Emoji     string      `json:"emoji"`
}

func (q *Queries) AddReactionAgent(ctx context.Context, arg AddReactionAgentParams) error {
	_, err := q.db.Exec(ctx, addReactionAgent, arg.MessageID, arg.AgentID, arg.Emoji)
	return err
}

const agentConversationUnread = `-- name: AgentConversationUnread :many
select m.conversation_id, count(*)::int as unread
from messages m
join conversations c on c.id = m.conversation_id
where c.project_id = $1
  and m.deleted_at is null
  and not c.agents_blocked
  and (m.author_agent_id is null or m.author_agent_id <> $2)
  and not exists (
    select 1 from message_reads r
    where r.message_id = m.id and r.agent_id = $2)
group by m.conversation_id
`

type AgentConversationUnreadParams struct {
	ProjectID pgtype.UUID `json:"project_id"`
	AgentID   pgtype.UUID `json:"agent_id"`
}

type AgentConversationUnreadRow struct {
	ConversationID pgtype.UUID `json:"conversation_id"`
	Unread         int32       `json:"unread"`
}

// unread count per conversation for this agent; own posts don't count
func (q *Queries) AgentConversationUnread(ctx context.Context, arg AgentConversationUnreadParams) ([]AgentConversationUnreadRow, error) {
	rows, err := q.db.Query(ctx, agentConversationUnread, arg.ProjectID, arg.AgentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AgentConversationUnreadRow{}
	for rows.Next() {
		var i AgentConversationUnreadRow
		if err := rows.Scan(&i.ConversationID, &i.Unread); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const agentOwnReadMessageIDs = `-- name: AgentOwnReadMessageIDs :many
select r.message_id from message_reads r
where r.agent_id = $1 and r.message_id = any($2::uuid[])
`

type AgentOwnReadMessageIDsParams struct {
	AgentID pgtype.UUID   `json:"agent_id"`
	Ids     []pgtype.UUID `json:"ids"`
}

// which of the given messages this agent already read — lets get_messages
// flag what was new before the fetch marks everything read
func (q *Queries) AgentOwnReadMessageIDs(ctx context.Context, arg AgentOwnReadMessageIDsParams) ([]pgtype.UUID, error) {
	rows, err := q.db.Query(ctx, agentOwnReadMessageIDs, arg.AgentID, arg.Ids)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []pgtype.UUID{}
	for rows.Next() {
		var message_id pgtype.UUID
		if err := rows.Scan(&message_id); err != nil {
			return nil, err
		}
		items = append(items, message_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const agentProjectUnread = `-- name: AgentProjectUnread :many
select c.project_id, count(*)::int as unread
from messages m
join conversations c on c.id = m.conversation_id
where m.deleted_at is null
  and not c.agents_blocked
  and (m.author_agent_id is null or m.author_agent_id <> $1)
  and not exists (
    select 1 from message_reads r
    where r.message_id = m.id and r.agent_id = $1)
group by c.project_id
`

type AgentProjectUnreadRow struct {
	ProjectID pgtype.UUID `json:"project_id"`
	Unread    int32       `json:"unread"`
}

// unread count per project across all its conversations, for this agent
func (q *Queries) AgentProjectUnread(ctx context.Context, agentID pgtype.UUID) ([]AgentProjectUnreadRow, error) {
	rows, err := q.db.Query(ctx, agentProjectUnread, agentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AgentProjectUnreadRow{}
	for rows.Next() {
		var i AgentProjectUnreadRow
		if err := rows.Scan(&i.ProjectID, &i.Unread); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const createAgentMessage = `-- name: CreateAgentMessage :one
insert into messages (conversation_id, author_agent_id, body, parent_id, mentions, forwarded_from, tags, silent)
values ($1, $2, $3, $4, coalesce($5, '[]'::jsonb), $6, coalesce($7, '{}'::text[]), coalesce($8, false))
returning id
`

type CreateAgentMessageParams struct {
	ConversationID pgtype.UUID `json:"conversation_id"`
	AgentID        pgtype.UUID `json:"agent_id"`
	Body           string      `json:"body"`
	ParentID       pgtype.UUID `json:"parent_id"`
	Mentions       interface{} `json:"mentions"`
	ForwardedFrom  pgtype.UUID `json:"forwarded_from"`
	Tags           interface{} `json:"tags"`
	Silent         interface{} `json:"silent"`
}

func (q *Queries) CreateAgentMessage(ctx context.Context, arg CreateAgentMessageParams) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, createAgentMessage,
		arg.ConversationID,
		arg.AgentID,
		arg.Body,
		arg.ParentID,
		arg.Mentions,
		arg.ForwardedFrom,
		arg.Tags,
		arg.Silent,
	)
	var id pgtype.UUID
	err := row.Scan(&id)
	return id, err
}

const createIssueForAgent = `-- name: CreateIssueForAgent :one
insert into issues (project_id, number, title, description, status, priority, assignee_id, created_by, agent_id)
values ($1, $2, $3, $4,
        'todo', $5, null, null, $6)
returning id, project_id, number, title, description, status, priority, assignee_id, agent_id, created_by, created_at, updated_at, github_node_id, github_repo_id, github_number, origin, github_kind, github_state, github_url
`

type CreateIssueForAgentParams struct {
	ProjectID   pgtype.UUID `json:"project_id"`
	Number      int32       `json:"number"`
	Title       string      `json:"title"`
	Description string      `json:"description"`
	Priority    string      `json:"priority"`
	AgentID     pgtype.UUID `json:"agent_id"`
}

func (q *Queries) CreateIssueForAgent(ctx context.Context, arg CreateIssueForAgentParams) (Issue, error) {
	row := q.db.QueryRow(ctx, createIssueForAgent,
		arg.ProjectID,
		arg.Number,
		arg.Title,
		arg.Description,
		arg.Priority,
		arg.AgentID,
	)
	var i Issue
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Number,
		&i.Title,
		&i.Description,
		&i.Status,
		&i.Priority,
		&i.AssigneeID,
		&i.AgentID,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.GithubNodeID,
		&i.GithubRepoID,
		&i.GithubNumber,
		&i.Origin,
		&i.GithubKind,
		&i.GithubState,
		&i.GithubUrl,
	)
	return i, err
}

const getAttachmentByID = `-- name: GetAttachmentByID :one
select id, project_id, uploader_id, storage_key, filename, content_type, size_bytes, status, created_at, uploader_agent_id from attachments where id = $1
`

func (q *Queries) GetAttachmentByID(ctx context.Context, id pgtype.UUID) (Attachment, error) {
	row := q.db.QueryRow(ctx, getAttachmentByID, id)
	var i Attachment
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.UploaderID,
		&i.StorageKey,
		&i.Filename,
		&i.ContentType,
		&i.SizeBytes,
		&i.Status,
		&i.CreatedAt,
		&i.UploaderAgentID,
	)
	return i, err
}

const getIssueForAgent = `-- name: GetIssueForAgent :one
select i.id, i.project_id, i.number, i.title, i.description, i.status, i.priority, i.assignee_id, i.agent_id, i.created_by, i.created_at, i.updated_at, i.github_node_id, i.github_repo_id, i.github_number, i.origin, i.github_kind, i.github_state, i.github_url, u.name as assignee_name, u.avatar_key as assignee_avatar
from issues i
left join users u on u.id = i.assignee_id
where i.id = $1
`

type GetIssueForAgentRow struct {
	ID             pgtype.UUID        `json:"id"`
	ProjectID      pgtype.UUID        `json:"project_id"`
	Number         int32              `json:"number"`
	Title          string             `json:"title"`
	Description    string             `json:"description"`
	Status         string             `json:"status"`
	Priority       string             `json:"priority"`
	AssigneeID     pgtype.UUID        `json:"assignee_id"`
	AgentID        pgtype.UUID        `json:"agent_id"`
	CreatedBy      pgtype.UUID        `json:"created_by"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
	GithubNodeID   pgtype.Text        `json:"github_node_id"`
	GithubRepoID   pgtype.UUID        `json:"github_repo_id"`
	GithubNumber   pgtype.Int4        `json:"github_number"`
	Origin         string             `json:"origin"`
	GithubKind     string             `json:"github_kind"`
	GithubState    pgtype.Text        `json:"github_state"`
	GithubUrl      pgtype.Text        `json:"github_url"`
	AssigneeName   pgtype.Text        `json:"assignee_name"`
	AssigneeAvatar pgtype.Text        `json:"assignee_avatar"`
}

func (q *Queries) GetIssueForAgent(ctx context.Context, id pgtype.UUID) (GetIssueForAgentRow, error) {
	row := q.db.QueryRow(ctx, getIssueForAgent, id)
	var i GetIssueForAgentRow
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Number,
		&i.Title,
		&i.Description,
		&i.Status,
		&i.Priority,
		&i.AssigneeID,
		&i.AgentID,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.GithubNodeID,
		&i.GithubRepoID,
		&i.GithubNumber,
		&i.Origin,
		&i.GithubKind,
		&i.GithubState,
		&i.GithubUrl,
		&i.AssigneeName,
		&i.AssigneeAvatar,
	)
	return i, err
}

const getMessageFull = `-- name: GetMessageFull :one
select m.id, m.conversation_id, m.body, m.mentions, m.tags, m.silent, m.created_at, m.edited_at, m.deleted_at, m.parent_id,
       m.author_user_id, m.author_agent_id, m.author_kind_snapshot,
       coalesce(u.name, a.name, nullif(m.author_name_snapshot, ''), '') as author_name,
       coalesce(u.avatar_key, a.avatar_key) as author_avatar,
       coalesce(pu.name, pa.name, nullif(pm.author_name_snapshot, ''), '') as parent_author_name,
       pm.body as parent_body,
       (pm.id is not null and pm.deleted_at is not null) as parent_deleted,
       t.id as thread_id, t.title as thread_title,
       (select count(*)::int from messages tm
         where tm.conversation_id = t.id and tm.deleted_at is null) as thread_reply_count,
       m.pinned_at, m.forwarded_from,
       f.conversation_id as fwd_conversation_id,
       fcp.project_id as fwd_project_id,
       coalesce(fu.name, fa.name, nullif(f.author_name_snapshot, ''), '') as fwd_author_name
from messages m
left join users u on u.id = m.author_user_id
left join agents a on a.id = m.author_agent_id
left join messages pm on pm.id = m.parent_id
left join users pu on pu.id = pm.author_user_id
left join agents pa on pa.id = pm.author_agent_id
left join conversations t on t.parent_message_id = m.id and t.kind = 'thread'
  and (t.expires_at is null or t.expires_at > now())
left join messages f on f.id = m.forwarded_from
left join conversations fcp on fcp.id = f.conversation_id
left join users fu on fu.id = f.author_user_id
left join agents fa on fa.id = f.author_agent_id
where m.id = $1
`

type GetMessageFullRow struct {
	ID                 pgtype.UUID        `json:"id"`
	ConversationID     pgtype.UUID        `json:"conversation_id"`
	Body               string             `json:"body"`
	Mentions           []byte             `json:"mentions"`
	Tags               []string           `json:"tags"`
	Silent             bool               `json:"silent"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
	EditedAt           pgtype.Timestamptz `json:"edited_at"`
	DeletedAt          pgtype.Timestamptz `json:"deleted_at"`
	ParentID           pgtype.UUID        `json:"parent_id"`
	AuthorUserID       pgtype.UUID        `json:"author_user_id"`
	AuthorAgentID      pgtype.UUID        `json:"author_agent_id"`
	AuthorKindSnapshot string             `json:"author_kind_snapshot"`
	AuthorName         string             `json:"author_name"`
	AuthorAvatar       pgtype.Text        `json:"author_avatar"`
	ParentAuthorName   string             `json:"parent_author_name"`
	ParentBody         pgtype.Text        `json:"parent_body"`
	ParentDeleted      pgtype.Bool        `json:"parent_deleted"`
	ThreadID           pgtype.UUID        `json:"thread_id"`
	ThreadTitle        pgtype.Text        `json:"thread_title"`
	ThreadReplyCount   int32              `json:"thread_reply_count"`
	PinnedAt           pgtype.Timestamptz `json:"pinned_at"`
	ForwardedFrom      pgtype.UUID        `json:"forwarded_from"`
	FwdConversationID  pgtype.UUID        `json:"fwd_conversation_id"`
	FwdProjectID       pgtype.UUID        `json:"fwd_project_id"`
	FwdAuthorName      string             `json:"fwd_author_name"`
}

func (q *Queries) GetMessageFull(ctx context.Context, id pgtype.UUID) (GetMessageFullRow, error) {
	row := q.db.QueryRow(ctx, getMessageFull, id)
	var i GetMessageFullRow
	err := row.Scan(
		&i.ID,
		&i.ConversationID,
		&i.Body,
		&i.Mentions,
		&i.Tags,
		&i.Silent,
		&i.CreatedAt,
		&i.EditedAt,
		&i.DeletedAt,
		&i.ParentID,
		&i.AuthorUserID,
		&i.AuthorAgentID,
		&i.AuthorKindSnapshot,
		&i.AuthorName,
		&i.AuthorAvatar,
		&i.ParentAuthorName,
		&i.ParentBody,
		&i.ParentDeleted,
		&i.ThreadID,
		&i.ThreadTitle,
		&i.ThreadReplyCount,
		&i.PinnedAt,
		&i.ForwardedFrom,
		&i.FwdConversationID,
		&i.FwdProjectID,
		&i.FwdAuthorName,
	)
	return i, err
}

const listProjectConversations = `-- name: ListProjectConversations :many
select id, project_id, kind, issue_id, created_at, brief_id, parent_message_id, title, created_by_user, created_by_agent, creator_name_snapshot, expires_at, agents_blocked from conversations where project_id = $1
  and not agents_blocked
  and (expires_at is null or expires_at > now())
order by created_at
`

// agents never see channels flagged agents_blocked nor expired threads
func (q *Queries) ListProjectConversations(ctx context.Context, projectID pgtype.UUID) ([]Conversation, error) {
	rows, err := q.db.Query(ctx, listProjectConversations, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Conversation{}
	for rows.Next() {
		var i Conversation
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.Kind,
			&i.IssueID,
			&i.CreatedAt,
			&i.BriefID,
			&i.ParentMessageID,
			&i.Title,
			&i.CreatedByUser,
			&i.CreatedByAgent,
			&i.CreatorNameSnapshot,
			&i.ExpiresAt,
			&i.AgentsBlocked,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProjectIssuesForAgent = `-- name: ListProjectIssuesForAgent :many
select i.id, i.project_id, i.number, i.title, i.description, i.status, i.priority, i.assignee_id, i.agent_id, i.created_by, i.created_at, i.updated_at, i.github_node_id, i.github_repo_id, i.github_number, i.origin, i.github_kind, i.github_state, i.github_url, u.name as assignee_name, u.avatar_key as assignee_avatar
from issues i
left join users u on u.id = i.assignee_id
where i.project_id = $1
order by i.number desc
limit $2
`

type ListProjectIssuesForAgentParams struct {
	ProjectID pgtype.UUID `json:"project_id"`
	Lim       int32       `json:"lim"`
}

type ListProjectIssuesForAgentRow struct {
	ID             pgtype.UUID        `json:"id"`
	ProjectID      pgtype.UUID        `json:"project_id"`
	Number         int32              `json:"number"`
	Title          string             `json:"title"`
	Description    string             `json:"description"`
	Status         string             `json:"status"`
	Priority       string             `json:"priority"`
	AssigneeID     pgtype.UUID        `json:"assignee_id"`
	AgentID        pgtype.UUID        `json:"agent_id"`
	CreatedBy      pgtype.UUID        `json:"created_by"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
	GithubNodeID   pgtype.Text        `json:"github_node_id"`
	GithubRepoID   pgtype.UUID        `json:"github_repo_id"`
	GithubNumber   pgtype.Int4        `json:"github_number"`
	Origin         string             `json:"origin"`
	GithubKind     string             `json:"github_kind"`
	GithubState    pgtype.Text        `json:"github_state"`
	GithubUrl      pgtype.Text        `json:"github_url"`
	AssigneeName   pgtype.Text        `json:"assignee_name"`
	AssigneeAvatar pgtype.Text        `json:"assignee_avatar"`
}

func (q *Queries) ListProjectIssuesForAgent(ctx context.Context, arg ListProjectIssuesForAgentParams) ([]ListProjectIssuesForAgentRow, error) {
	rows, err := q.db.Query(ctx, listProjectIssuesForAgent, arg.ProjectID, arg.Lim)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListProjectIssuesForAgentRow{}
	for rows.Next() {
		var i ListProjectIssuesForAgentRow
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.Number,
			&i.Title,
			&i.Description,
			&i.Status,
			&i.Priority,
			&i.AssigneeID,
			&i.AgentID,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.GithubNodeID,
			&i.GithubRepoID,
			&i.GithubNumber,
			&i.Origin,
			&i.GithubKind,
			&i.GithubState,
			&i.GithubUrl,
			&i.AssigneeName,
			&i.AssigneeAvatar,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markMessageReadAgent = `-- name: MarkMessageReadAgent :exec
insert into message_reads (message_id, agent_id)
values ($1, $2)
on conflict (message_id, agent_id) where agent_id is not null do nothing
`

type MarkMessageReadAgentParams struct {
	MessageID pgtype.UUID `json:"message_id"`
	AgentID   pgtype.UUID `json:"agent_id"`
}

func (q *Queries) MarkMessageReadAgent(ctx context.Context, arg MarkMessageReadAgentParams) error {
	_, err := q.db.Exec(ctx, markMessageReadAgent, arg.MessageID, arg.AgentID)
	return err
}

const markMessagesReadAgent = `-- name: MarkMessagesReadAgent :exec
insert into message_reads (message_id, agent_id)
select m.id, $1 from messages m
where m.id = any($2::uuid[]) and m.deleted_at is null
on conflict (message_id, agent_id) where agent_id is not null do nothing
`

type MarkMessagesReadAgentParams struct {
	AgentID pgtype.UUID   `json:"agent_id"`
	Ids     []pgtype.UUID `json:"ids"`
}

// batch read receipt: fetching messages marks them read by this agent
func (q *Queries) MarkMessagesReadAgent(ctx context.Context, arg MarkMessagesReadAgentParams) error {
	_, err := q.db.Exec(ctx, markMessagesReadAgent, arg.AgentID, arg.Ids)
	return err
}

const messageInConversation = `-- name: MessageInConversation :one
select id from messages
where id = $1 and conversation_id = $2
  and deleted_at is null
`

type MessageInConversationParams struct {
	ID             pgtype.UUID `json:"id"`
	ConversationID pgtype.UUID `json:"conversation_id"`
}

func (q *Queries) MessageInConversation(ctx context.Context, arg MessageInConversationParams) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, messageInConversation, arg.ID, arg.ConversationID)
	var id pgtype.UUID
	err := row.Scan(&id)
	return id, err
}

const pinMessageAgent = `-- name: PinMessageAgent :one
update messages set pinned_at = now()
where id = $1 and deleted_at is null
returning id, conversation_id
`

type PinMessageAgentRow struct {
	ID             pgtype.UUID `json:"id"`
	ConversationID pgtype.UUID `json:"conversation_id"`
}

func (q *Queries) PinMessageAgent(ctx context.Context, id pgtype.UUID) (PinMessageAgentRow, error) {
	row := q.db.QueryRow(ctx, pinMessageAgent, id)
	var i PinMessageAgentRow
	err := row.Scan(&i.ID, &i.ConversationID)
	return i, err
}

const recordIssueActivityAgent = `-- name: RecordIssueActivityAgent :exec
insert into issue_activity (issue_id, actor_agent_id, kind, payload)
values ($1, $2, $3, $4)
`

type RecordIssueActivityAgentParams struct {
	IssueID pgtype.UUID `json:"issue_id"`
	AgentID pgtype.UUID `json:"agent_id"`
	Kind    string      `json:"kind"`
	Payload []byte      `json:"payload"`
}

func (q *Queries) RecordIssueActivityAgent(ctx context.Context, arg RecordIssueActivityAgentParams) error {
	_, err := q.db.Exec(ctx, recordIssueActivityAgent,
		arg.IssueID,
		arg.AgentID,
		arg.Kind,
		arg.Payload,
	)
	return err
}

const removeReactionAgent = `-- name: RemoveReactionAgent :execrows
delete from message_reactions
where message_id = $1 and agent_id = $2 and emoji = $3
`

type RemoveReactionAgentParams struct {
	MessageID pgtype.UUID `json:"message_id"`
	AgentID   pgtype.UUID `json:"agent_id"`
	Emoji     string      `json:"emoji"`
}

func (q *Queries) RemoveReactionAgent(ctx context.Context, arg RemoveReactionAgentParams) (int64, error) {
	result, err := q.db.Exec(ctx, removeReactionAgent, arg.MessageID, arg.AgentID, arg.Emoji)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const resolveAttachmentProject = `-- name: ResolveAttachmentProject :one
select project_id from attachments where id = $1
`

func (q *Queries) ResolveAttachmentProject(ctx context.Context, id pgtype.UUID) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, resolveAttachmentProject, id)
	var project_id pgtype.UUID
	err := row.Scan(&project_id)
	return project_id, err
}

const resolveConversationProject = `-- name: ResolveConversationProject :one

select project_id from conversations where id = $1
`

// MCP tool queries. Authorization is scope-based: resolvers map an entity
// to its project, then AgentScopeForProject decides.
func (q *Queries) ResolveConversationProject(ctx context.Context, id pgtype.UUID) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, resolveConversationProject, id)
	var project_id pgtype.UUID
	err := row.Scan(&project_id)
	return project_id, err
}

const resolveIssueProject = `-- name: ResolveIssueProject :one
select project_id from issues where id = $1
`

func (q *Queries) ResolveIssueProject(ctx context.Context, id pgtype.UUID) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, resolveIssueProject, id)
	var project_id pgtype.UUID
	err := row.Scan(&project_id)
	return project_id, err
}

const resolveMessageProject = `-- name: ResolveMessageProject :one
select c.project_id from messages m
join conversations c on c.id = m.conversation_id
where m.id = $1
`

func (q *Queries) ResolveMessageProject(ctx context.Context, id pgtype.UUID) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, resolveMessageProject, id)
	var project_id pgtype.UUID
	err := row.Scan(&project_id)
	return project_id, err
}

const searchMessagesInProject = `-- name: SearchMessagesInProject :many
select m.id, m.conversation_id, m.body, m.tags, m.silent, m.created_at, m.edited_at,
       m.author_user_id, m.author_agent_id, m.author_kind_snapshot,
       coalesce(u.name, a.name, nullif(m.author_name_snapshot, ''), '') as author_name,
       coalesce(u.avatar_key, a.avatar_key) as author_avatar
from messages m
join conversations c on c.id = m.conversation_id
left join users u on u.id = m.author_user_id
left join agents a on a.id = m.author_agent_id
where c.project_id = $1
  and m.deleted_at is null
  and not c.agents_blocked
  and m.body ilike '%' || $2 || '%'
order by m.created_at desc
limit $3
`

type SearchMessagesInProjectParams struct {
	ProjectID pgtype.UUID `json:"project_id"`
	Q         pgtype.Text `json:"q"`
	Lim       int32       `json:"lim"`
}

type SearchMessagesInProjectRow struct {
	ID                 pgtype.UUID        `json:"id"`
	ConversationID     pgtype.UUID        `json:"conversation_id"`
	Body               string             `json:"body"`
	Tags               []string           `json:"tags"`
	Silent             bool               `json:"silent"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
	EditedAt           pgtype.Timestamptz `json:"edited_at"`
	AuthorUserID       pgtype.UUID        `json:"author_user_id"`
	AuthorAgentID      pgtype.UUID        `json:"author_agent_id"`
	AuthorKindSnapshot string             `json:"author_kind_snapshot"`
	AuthorName         string             `json:"author_name"`
	AuthorAvatar       pgtype.Text        `json:"author_avatar"`
}

func (q *Queries) SearchMessagesInProject(ctx context.Context, arg SearchMessagesInProjectParams) ([]SearchMessagesInProjectRow, error) {
	rows, err := q.db.Query(ctx, searchMessagesInProject, arg.ProjectID, arg.Q, arg.Lim)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SearchMessagesInProjectRow{}
	for rows.Next() {
		var i SearchMessagesInProjectRow
		if err := rows.Scan(
			&i.ID,
			&i.ConversationID,
			&i.Body,
			&i.Tags,
			&i.Silent,
			&i.CreatedAt,
			&i.EditedAt,
			&i.AuthorUserID,
			&i.AuthorAgentID,
			&i.AuthorKindSnapshot,
			&i.AuthorName,
			&i.AuthorAvatar,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setMessageTags = `-- name: SetMessageTags :exec
update messages set tags = $1 where id = $2
`

type SetMessageTagsParams struct {
	Tags []string    `json:"tags"`
	ID   pgtype.UUID `json:"id"`
}

func (q *Queries) SetMessageTags(ctx context.Context, arg SetMessageTagsParams) error {
	_, err := q.db.Exec(ctx, setMessageTags, arg.Tags, arg.ID)
	return err
}

const unpinMessageAgent = `-- name: UnpinMessageAgent :one
update messages set pinned_at = null
where id = $1 and deleted_at is null
returning id, conversation_id
`

type UnpinMessageAgentRow struct {
	ID             pgtype.UUID `json:"id"`
	ConversationID pgtype.UUID `json:"conversation_id"`
}

func (q *Queries) UnpinMessageAgent(ctx context.Context, id pgtype.UUID) (UnpinMessageAgentRow, error) {
	row := q.db.QueryRow(ctx, unpinMessageAgent, id)
	var i UnpinMessageAgentRow
	err := row.Scan(&i.ID, &i.ConversationID)
	return i, err
}

const updateMessageBodyAgent = `-- name: UpdateMessageBodyAgent :one
update messages set body = $1, edited_at = now()
where id = $2
  and author_agent_id = $3
  and deleted_at is null
returning id
`

type UpdateMessageBodyAgentParams struct {
	Body          string      `json:"body"`
	ID            pgtype.UUID `json:"id"`
	AuthorAgentID pgtype.UUID `json:"author_agent_id"`
}

// agents may edit their own messages while no agent has read them
func (q *Queries) UpdateMessageBodyAgent(ctx context.Context, arg UpdateMessageBodyAgentParams) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, updateMessageBodyAgent, arg.Body, arg.ID, arg.AuthorAgentID)
	var id pgtype.UUID
	err := row.Scan(&id)
	return id, err
}
