// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: mentions.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const agentBySlug = `-- name: AgentBySlug :one
select id, name, slug
from agents
where workspace_id = $1 and slug = $2
`

type AgentBySlugParams struct {
	WorkspaceID pgtype.UUID `json:"workspace_id"`
	Slug        string      `json:"slug"`
}

type AgentBySlugRow struct {
	ID   pgtype.UUID `json:"id"`
	Name string      `json:"name"`
	Slug string      `json:"slug"`
}

func (q *Queries) AgentBySlug(ctx context.Context, arg AgentBySlugParams) (AgentBySlugRow, error) {
	row := q.db.QueryRow(ctx, agentBySlug, arg.WorkspaceID, arg.Slug)
	var i AgentBySlugRow
	err := row.Scan(&i.ID, &i.Name, &i.Slug)
	return i, err
}

const issueByKeyInProject = `-- name: IssueByKeyInProject :one
select i.id, cast(p.key || '-' || i.number as text) as key, i.title,
       i.github_kind, i.github_url,
       coalesce(cast(r.owner || '/' || r.name as text), '') as repo
from issues i
join projects p on p.id = i.project_id
left join repositories r on r.id = i.github_repo_id
where i.project_id = $1
  and p.key || '-' || i.number = upper($2)
`

type IssueByKeyInProjectParams struct {
	ProjectID pgtype.UUID `json:"project_id"`
	Key       interface{} `json:"key"`
}

type IssueByKeyInProjectRow struct {
	ID         pgtype.UUID `json:"id"`
	Key        string      `json:"key"`
	Title      string      `json:"title"`
	GithubKind string      `json:"github_kind"`
	GithubUrl  pgtype.Text `json:"github_url"`
	Repo       interface{} `json:"repo"`
}

func (q *Queries) IssueByKeyInProject(ctx context.Context, arg IssueByKeyInProjectParams) (IssueByKeyInProjectRow, error) {
	row := q.db.QueryRow(ctx, issueByKeyInProject, arg.ProjectID, arg.Key)
	var i IssueByKeyInProjectRow
	err := row.Scan(
		&i.ID,
		&i.Key,
		&i.Title,
		&i.GithubKind,
		&i.GithubUrl,
		&i.Repo,
	)
	return i, err
}

const listAgentsMentionable = `-- name: ListAgentsMentionable :many
select id, name, slug, description
from agents
where workspace_id = $1
order by name
`

type ListAgentsMentionableRow struct {
	ID          pgtype.UUID `json:"id"`
	Name        string      `json:"name"`
	Slug        string      `json:"slug"`
	Description string      `json:"description"`
}

func (q *Queries) ListAgentsMentionable(ctx context.Context, workspaceID pgtype.UUID) ([]ListAgentsMentionableRow, error) {
	rows, err := q.db.Query(ctx, listAgentsMentionable, workspaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAgentsMentionableRow{}
	for rows.Next() {
		var i ListAgentsMentionableRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Slug,
			&i.Description,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMentionableIssues = `-- name: ListMentionableIssues :many
select i.id, cast(p.key || '-' || i.number as text) as key, i.title, i.status,
       i.github_kind, i.github_url, i.github_number,
       coalesce(cast(r.owner || '/' || r.name as text), '') as repo
from issues i
join projects p on p.id = i.project_id
left join repositories r on r.id = i.github_repo_id
where i.project_id = $1
order by i.updated_at desc
limit 500
`

type ListMentionableIssuesRow struct {
	ID           pgtype.UUID `json:"id"`
	Key          string      `json:"key"`
	Title        string      `json:"title"`
	Status       string      `json:"status"`
	GithubKind   string      `json:"github_kind"`
	GithubUrl    pgtype.Text `json:"github_url"`
	GithubNumber pgtype.Int4 `json:"github_number"`
	Repo         interface{} `json:"repo"`
}

// project issues incl. GitHub mirrors; key is computed, repo name joins for
// owner/repo#N refs
func (q *Queries) ListMentionableIssues(ctx context.Context, projectID pgtype.UUID) ([]ListMentionableIssuesRow, error) {
	rows, err := q.db.Query(ctx, listMentionableIssues, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListMentionableIssuesRow{}
	for rows.Next() {
		var i ListMentionableIssuesRow
		if err := rows.Scan(
			&i.ID,
			&i.Key,
			&i.Title,
			&i.Status,
			&i.GithubKind,
			&i.GithubUrl,
			&i.GithubNumber,
			&i.Repo,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const projectWorkspaceID = `-- name: ProjectWorkspaceID :one
select workspace_id from projects where id = $1
`

func (q *Queries) ProjectWorkspaceID(ctx context.Context, projectID pgtype.UUID) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, projectWorkspaceID, projectID)
	var workspace_id pgtype.UUID
	err := row.Scan(&workspace_id)
	return workspace_id, err
}

const updateMessageMentions = `-- name: UpdateMessageMentions :exec
update messages set mentions = $1 where id = $2
`

type UpdateMessageMentionsParams struct {
	Mentions []byte      `json:"mentions"`
	ID       pgtype.UUID `json:"id"`
}

func (q *Queries) UpdateMessageMentions(ctx context.Context, arg UpdateMessageMentionsParams) error {
	_, err := q.db.Exec(ctx, updateMessageMentions, arg.Mentions, arg.ID)
	return err
}

const userByNameInWorkspace = `-- name: UserByNameInWorkspace :one
select u.id, u.name
from workspace_members wm
join users u on u.id = wm.user_id
where wm.workspace_id = $1
  and (lower(u.name) = lower($2)
       or lower(replace(u.name, ' ', '-')) = lower($2)
       or lower(u.email) = lower($2)
       or lower(split_part(u.email, '@', 1)) = lower($2))
`

type UserByNameInWorkspaceParams struct {
	WorkspaceID pgtype.UUID `json:"workspace_id"`
	Name        string      `json:"name"`
}

type UserByNameInWorkspaceRow struct {
	ID   pgtype.UUID `json:"id"`
	Name string      `json:"name"`
}

func (q *Queries) UserByNameInWorkspace(ctx context.Context, arg UserByNameInWorkspaceParams) (UserByNameInWorkspaceRow, error) {
	row := q.db.QueryRow(ctx, userByNameInWorkspace, arg.WorkspaceID, arg.Name)
	var i UserByNameInWorkspaceRow
	err := row.Scan(&i.ID, &i.Name)
	return i, err
}
