// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Agent struct {
	ID          pgtype.UUID        `json:"id"`
	WorkspaceID pgtype.UUID        `json:"workspace_id"`
	Name        string             `json:"name"`
	Slug        string             `json:"slug"`
	Description string             `json:"description"`
	AvatarKey   pgtype.Text        `json:"avatar_key"`
	CreatedBy   pgtype.UUID        `json:"created_by"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
	ReviewMode  string             `json:"review_mode"`
	GrantAll    bool               `json:"grant_all"`
	GrantScopes []string           `json:"grant_scopes"`
}

type AgentInvite struct {
	ID          pgtype.UUID        `json:"id"`
	WorkspaceID pgtype.UUID        `json:"workspace_id"`
	TokenHash   []byte             `json:"token_hash"`
	ProjectIds  []pgtype.UUID      `json:"project_ids"`
	Scopes      []string           `json:"scopes"`
	ExpiresAt   pgtype.Timestamptz `json:"expires_at"`
	UsedBy      pgtype.UUID        `json:"used_by"`
	CreatedBy   pgtype.UUID        `json:"created_by"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

type AgentProjectPermission struct {
	AgentID   pgtype.UUID        `json:"agent_id"`
	ProjectID pgtype.UUID        `json:"project_id"`
	Scopes    []string           `json:"scopes"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type AgentReview struct {
	ID          pgtype.UUID        `json:"id"`
	ProjectID   pgtype.UUID        `json:"project_id"`
	IssueID     pgtype.UUID        `json:"issue_id"`
	AgentID     pgtype.UUID        `json:"agent_id"`
	Status      string             `json:"status"`
	Title       string             `json:"title"`
	Summary     string             `json:"summary"`
	Files       []byte             `json:"files"`
	Decisions   []byte             `json:"decisions"`
	Actions     []byte             `json:"actions"`
	Links       []byte             `json:"links"`
	Verify      string             `json:"verify"`
	Supersedes  pgtype.UUID        `json:"supersedes"`
	RespondedBy pgtype.UUID        `json:"responded_by"`
	Response    string             `json:"response"`
	RespondedAt pgtype.Timestamptz `json:"responded_at"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

type AgentTodo struct {
	ID                pgtype.UUID        `json:"id"`
	ProjectID         pgtype.UUID        `json:"project_id"`
	AgentID           pgtype.UUID        `json:"agent_id"`
	IssueID           pgtype.UUID        `json:"issue_id"`
	Content           string             `json:"content"`
	Done              bool               `json:"done"`
	Position          int32              `json:"position"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	UpdatedAt         pgtype.Timestamptz `json:"updated_at"`
	AgentNameSnapshot string             `json:"agent_name_snapshot"`
}

type Attachment struct {
	ID          pgtype.UUID        `json:"id"`
	ProjectID   pgtype.UUID        `json:"project_id"`
	UploaderID  pgtype.UUID        `json:"uploader_id"`
	StorageKey  string             `json:"storage_key"`
	Filename    string             `json:"filename"`
	ContentType string             `json:"content_type"`
	SizeBytes   int64              `json:"size_bytes"`
	Status      string             `json:"status"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

type Board struct {
	ID        pgtype.UUID        `json:"id"`
	ProjectID pgtype.UUID        `json:"project_id"`
	Name      string             `json:"name"`
	Filters   []byte             `json:"filters"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type Brief struct {
	ID                  pgtype.UUID        `json:"id"`
	ProjectID           pgtype.UUID        `json:"project_id"`
	IssueID             pgtype.UUID        `json:"issue_id"`
	ConversationID      pgtype.UUID        `json:"conversation_id"`
	Title               string             `json:"title"`
	Summary             string             `json:"summary"`
	Scene               []byte             `json:"scene"`
	Status              string             `json:"status"`
	CreatedByUser       pgtype.UUID        `json:"created_by_user"`
	CreatedByAgent      pgtype.UUID        `json:"created_by_agent"`
	CreatedAt           pgtype.Timestamptz `json:"created_at"`
	UpdatedAt           pgtype.Timestamptz `json:"updated_at"`
	CreatorNameSnapshot string             `json:"creator_name_snapshot"`
}

type Conversation struct {
	ID                  pgtype.UUID        `json:"id"`
	ProjectID           pgtype.UUID        `json:"project_id"`
	Kind                string             `json:"kind"`
	IssueID             pgtype.UUID        `json:"issue_id"`
	CreatedAt           pgtype.Timestamptz `json:"created_at"`
	BriefID             pgtype.UUID        `json:"brief_id"`
	ParentMessageID     pgtype.UUID        `json:"parent_message_id"`
	Title               pgtype.Text        `json:"title"`
	CreatedByUser       pgtype.UUID        `json:"created_by_user"`
	CreatedByAgent      pgtype.UUID        `json:"created_by_agent"`
	CreatorNameSnapshot string             `json:"creator_name_snapshot"`
}

type GithubApp struct {
	ID               bool               `json:"id"`
	AppID            int64              `json:"app_id"`
	Slug             string             `json:"slug"`
	Name             string             `json:"name"`
	ClientID         string             `json:"client_id"`
	ClientSecretEnc  []byte             `json:"client_secret_enc"`
	PrivateKeyEnc    []byte             `json:"private_key_enc"`
	WebhookSecretEnc []byte             `json:"webhook_secret_enc"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
}

type GithubEvent struct {
	DeliveryID  string             `json:"delivery_id"`
	Event       string             `json:"event"`
	ProcessedAt pgtype.Timestamptz `json:"processed_at"`
}

type GithubInstallation struct {
	ID             pgtype.UUID        `json:"id"`
	WorkspaceID    pgtype.UUID        `json:"workspace_id"`
	InstallationID int64              `json:"installation_id"`
	AccountLogin   string             `json:"account_login"`
	AccountType    string             `json:"account_type"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
}

type Issue struct {
	ID           pgtype.UUID        `json:"id"`
	ProjectID    pgtype.UUID        `json:"project_id"`
	Number       int32              `json:"number"`
	Title        string             `json:"title"`
	Description  string             `json:"description"`
	Status       string             `json:"status"`
	Priority     string             `json:"priority"`
	AssigneeID   pgtype.UUID        `json:"assignee_id"`
	AgentID      pgtype.UUID        `json:"agent_id"`
	CreatedBy    pgtype.UUID        `json:"created_by"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
	GithubNodeID pgtype.Text        `json:"github_node_id"`
	GithubRepoID pgtype.UUID        `json:"github_repo_id"`
	GithubNumber pgtype.Int4        `json:"github_number"`
	Origin       string             `json:"origin"`
	GithubKind   string             `json:"github_kind"`
	GithubState  pgtype.Text        `json:"github_state"`
	GithubUrl    pgtype.Text        `json:"github_url"`
}

type IssueActivity struct {
	ID           pgtype.UUID        `json:"id"`
	IssueID      pgtype.UUID        `json:"issue_id"`
	ActorUserID  pgtype.UUID        `json:"actor_user_id"`
	ActorAgentID pgtype.UUID        `json:"actor_agent_id"`
	Kind         string             `json:"kind"`
	Payload      []byte             `json:"payload"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
}

type IssueLabel struct {
	ID        pgtype.UUID        `json:"id"`
	ProjectID pgtype.UUID        `json:"project_id"`
	Name      string             `json:"name"`
	Color     string             `json:"color"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type IssueLabelLink struct {
	IssueID pgtype.UUID `json:"issue_id"`
	LabelID pgtype.UUID `json:"label_id"`
}

type McpToken struct {
	ID         pgtype.UUID        `json:"id"`
	AgentID    pgtype.UUID        `json:"agent_id"`
	TokenHash  []byte             `json:"token_hash"`
	Name       string             `json:"name"`
	LastUsedAt pgtype.Timestamptz `json:"last_used_at"`
	ExpiresAt  pgtype.Timestamptz `json:"expires_at"`
	RevokedAt  pgtype.Timestamptz `json:"revoked_at"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
}

type Message struct {
	ID                 pgtype.UUID        `json:"id"`
	ConversationID     pgtype.UUID        `json:"conversation_id"`
	AuthorUserID       pgtype.UUID        `json:"author_user_id"`
	AuthorAgentID      pgtype.UUID        `json:"author_agent_id"`
	Body               string             `json:"body"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
	EditedAt           pgtype.Timestamptz `json:"edited_at"`
	DeletedAt          pgtype.Timestamptz `json:"deleted_at"`
	ParentID           pgtype.UUID        `json:"parent_id"`
	Mentions           []byte             `json:"mentions"`
	PinnedAt           pgtype.Timestamptz `json:"pinned_at"`
	ForwardedFrom      pgtype.UUID        `json:"forwarded_from"`
	Tags               []string           `json:"tags"`
	AuthorNameSnapshot string             `json:"author_name_snapshot"`
	AuthorKindSnapshot string             `json:"author_kind_snapshot"`
}

type MessageAttachment struct {
	MessageID    pgtype.UUID `json:"message_id"`
	AttachmentID pgtype.UUID `json:"attachment_id"`
	Position     int32       `json:"position"`
}

type MessageReaction struct {
	MessageID pgtype.UUID        `json:"message_id"`
	UserID    pgtype.UUID        `json:"user_id"`
	AgentID   pgtype.UUID        `json:"agent_id"`
	Emoji     string             `json:"emoji"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type MessageRead struct {
	MessageID pgtype.UUID        `json:"message_id"`
	UserID    pgtype.UUID        `json:"user_id"`
	AgentID   pgtype.UUID        `json:"agent_id"`
	ReadAt    pgtype.Timestamptz `json:"read_at"`
}

type PasswordResetToken struct {
	ID        pgtype.UUID        `json:"id"`
	UserID    pgtype.UUID        `json:"user_id"`
	TokenHash string             `json:"token_hash"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
	UsedAt    pgtype.Timestamptz `json:"used_at"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type Project struct {
	ID          pgtype.UUID        `json:"id"`
	WorkspaceID pgtype.UUID        `json:"workspace_id"`
	Key         string             `json:"key"`
	Name        string             `json:"name"`
	Description string             `json:"description"`
	Icon        pgtype.Text        `json:"icon"`
	Color       pgtype.Text        `json:"color"`
	CreatedBy   pgtype.UUID        `json:"created_by"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
	Statuses    []byte             `json:"statuses"`
	LocalPath   pgtype.Text        `json:"local_path"`
	BriefPolicy string             `json:"brief_policy"`
	AvatarKey   pgtype.Text        `json:"avatar_key"`
}

type ProjectCounter struct {
	ProjectID       pgtype.UUID `json:"project_id"`
	NextIssueNumber int32       `json:"next_issue_number"`
}

type ProjectMember struct {
	ProjectID pgtype.UUID        `json:"project_id"`
	UserID    pgtype.UUID        `json:"user_id"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type PushSubscription struct {
	ID        pgtype.UUID        `json:"id"`
	UserID    pgtype.UUID        `json:"user_id"`
	Endpoint  string             `json:"endpoint"`
	Auth      string             `json:"auth"`
	Keys      []byte             `json:"keys"`
	UserAgent pgtype.Text        `json:"user_agent"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	LastSeen  pgtype.Timestamptz `json:"last_seen"`
}

type RateLimit struct {
	Key         string             `json:"key"`
	WindowStart pgtype.Timestamptz `json:"window_start"`
	Count       int32              `json:"count"`
}

type Repository struct {
	ID             pgtype.UUID        `json:"id"`
	ProjectID      pgtype.UUID        `json:"project_id"`
	InstallationID int64              `json:"installation_id"`
	Owner          string             `json:"owner"`
	Name           string             `json:"name"`
	DefaultBranch  string             `json:"default_branch"`
	LinkedBy       pgtype.UUID        `json:"linked_by"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
}

type SavedFilter struct {
	ID        pgtype.UUID        `json:"id"`
	ProjectID pgtype.UUID        `json:"project_id"`
	UserID    pgtype.UUID        `json:"user_id"`
	Name      string             `json:"name"`
	Filters   []byte             `json:"filters"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type Session struct {
	ID         pgtype.UUID        `json:"id"`
	UserID     pgtype.UUID        `json:"user_id"`
	TokenHash  string             `json:"token_hash"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	ExpiresAt  pgtype.Timestamptz `json:"expires_at"`
	LastSeenAt pgtype.Timestamptz `json:"last_seen_at"`
	Ip         string             `json:"ip"`
	UserAgent  string             `json:"user_agent"`
}

type User struct {
	ID           pgtype.UUID        `json:"id"`
	Email        string             `json:"email"`
	PasswordHash string             `json:"password_hash"`
	Name         string             `json:"name"`
	AvatarKey    pgtype.Text        `json:"avatar_key"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
	NameColor    pgtype.Text        `json:"name_color"`
}

type WebhookDelivery struct {
	ID             pgtype.UUID        `json:"id"`
	SubscriptionID pgtype.UUID        `json:"subscription_id"`
	DeliveryID     pgtype.UUID        `json:"delivery_id"`
	EventType      string             `json:"event_type"`
	Payload        []byte             `json:"payload"`
	StatusCode     pgtype.Int4        `json:"status_code"`
	Attempts       int32              `json:"attempts"`
	DurationMs     int32              `json:"duration_ms"`
	Success        bool               `json:"success"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
}

type WebhookSubscription struct {
	ID        pgtype.UUID        `json:"id"`
	ProjectID pgtype.UUID        `json:"project_id"`
	Url       string             `json:"url"`
	Secret    string             `json:"secret"`
	Events    []string           `json:"events"`
	Active    bool               `json:"active"`
	CreatedBy pgtype.UUID        `json:"created_by"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

type Workspace struct {
	ID        pgtype.UUID        `json:"id"`
	Name      string             `json:"name"`
	Slug      string             `json:"slug"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	AvatarKey pgtype.Text        `json:"avatar_key"`
}

type WorkspaceMember struct {
	WorkspaceID pgtype.UUID        `json:"workspace_id"`
	UserID      pgtype.UUID        `json:"user_id"`
	Role        string             `json:"role"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}
