// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Attachment struct {
	ID          pgtype.UUID        `json:"id"`
	ProjectID   pgtype.UUID        `json:"project_id"`
	UploaderID  pgtype.UUID        `json:"uploader_id"`
	StorageKey  string             `json:"storage_key"`
	Filename    string             `json:"filename"`
	ContentType string             `json:"content_type"`
	SizeBytes   int64              `json:"size_bytes"`
	Status      string             `json:"status"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

type Conversation struct {
	ID        pgtype.UUID        `json:"id"`
	ProjectID pgtype.UUID        `json:"project_id"`
	Kind      string             `json:"kind"`
	IssueID   pgtype.UUID        `json:"issue_id"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type Message struct {
	ID             pgtype.UUID        `json:"id"`
	ConversationID pgtype.UUID        `json:"conversation_id"`
	AuthorUserID   pgtype.UUID        `json:"author_user_id"`
	AuthorAgentID  pgtype.UUID        `json:"author_agent_id"`
	Body           string             `json:"body"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	EditedAt       pgtype.Timestamptz `json:"edited_at"`
	DeletedAt      pgtype.Timestamptz `json:"deleted_at"`
}

type MessageAttachment struct {
	MessageID    pgtype.UUID `json:"message_id"`
	AttachmentID pgtype.UUID `json:"attachment_id"`
	Position     int32       `json:"position"`
}

type MessageRead struct {
	MessageID pgtype.UUID        `json:"message_id"`
	UserID    pgtype.UUID        `json:"user_id"`
	AgentID   pgtype.UUID        `json:"agent_id"`
	ReadAt    pgtype.Timestamptz `json:"read_at"`
}

type PasswordResetToken struct {
	ID        pgtype.UUID        `json:"id"`
	UserID    pgtype.UUID        `json:"user_id"`
	TokenHash string             `json:"token_hash"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
	UsedAt    pgtype.Timestamptz `json:"used_at"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type Project struct {
	ID          pgtype.UUID        `json:"id"`
	WorkspaceID pgtype.UUID        `json:"workspace_id"`
	Key         string             `json:"key"`
	Name        string             `json:"name"`
	Description string             `json:"description"`
	Icon        pgtype.Text        `json:"icon"`
	Color       pgtype.Text        `json:"color"`
	CreatedBy   pgtype.UUID        `json:"created_by"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

type ProjectCounter struct {
	ProjectID       pgtype.UUID `json:"project_id"`
	NextIssueNumber int32       `json:"next_issue_number"`
}

type ProjectMember struct {
	ProjectID pgtype.UUID        `json:"project_id"`
	UserID    pgtype.UUID        `json:"user_id"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type RateLimit struct {
	Key         string             `json:"key"`
	WindowStart pgtype.Timestamptz `json:"window_start"`
	Count       int32              `json:"count"`
}

type Session struct {
	ID         pgtype.UUID        `json:"id"`
	UserID     pgtype.UUID        `json:"user_id"`
	TokenHash  string             `json:"token_hash"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	ExpiresAt  pgtype.Timestamptz `json:"expires_at"`
	LastSeenAt pgtype.Timestamptz `json:"last_seen_at"`
	Ip         string             `json:"ip"`
	UserAgent  string             `json:"user_agent"`
}

type User struct {
	ID           pgtype.UUID        `json:"id"`
	Email        string             `json:"email"`
	PasswordHash string             `json:"password_hash"`
	Name         string             `json:"name"`
	AvatarKey    pgtype.Text        `json:"avatar_key"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}

type Workspace struct {
	ID        pgtype.UUID        `json:"id"`
	Name      string             `json:"name"`
	Slug      string             `json:"slug"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type WorkspaceMember struct {
	WorkspaceID pgtype.UUID        `json:"workspace_id"`
	UserID      pgtype.UUID        `json:"user_id"`
	Role        string             `json:"role"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}
