// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: presence.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const listUserProjectIDs = `-- name: ListUserProjectIDs :many
select p.id
from projects p
join workspace_members wm on wm.workspace_id = p.workspace_id
where wm.user_id = $1
`

// every project the user can see: workspace membership implies project
// visibility, same shape GetProjectForUser encodes
func (q *Queries) ListUserProjectIDs(ctx context.Context, userID pgtype.UUID) ([]pgtype.UUID, error) {
	rows, err := q.db.Query(ctx, listUserProjectIDs, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []pgtype.UUID{}
	for rows.Next() {
		var id pgtype.UUID
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listVisibleUserIDs = `-- name: ListVisibleUserIDs :many
select distinct wm2.user_id
from workspace_members wm
join workspace_members wm2 on wm2.workspace_id = wm.workspace_id
where wm.user_id = $1
`

// every user sharing at least one workspace with the caller — the
// visibility envelope for presence data
func (q *Queries) ListVisibleUserIDs(ctx context.Context, userID pgtype.UUID) ([]pgtype.UUID, error) {
	rows, err := q.db.Query(ctx, listVisibleUserIDs, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []pgtype.UUID{}
	for rows.Next() {
		var user_id pgtype.UUID
		if err := rows.Scan(&user_id); err != nil {
			return nil, err
		}
		items = append(items, user_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const stampUserLastSeen = `-- name: StampUserLastSeen :exec
update users set last_seen_at = now() where id = $1
`

func (q *Queries) StampUserLastSeen(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, stampUserLastSeen, id)
	return err
}
