// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: previews.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getLinkPreview = `-- name: GetLinkPreview :one
select url, title, description, image_url, site_name, fetched_at, failed_at from link_previews
where url = $1 and fetched_at > now() - interval '7 days'
`

func (q *Queries) GetLinkPreview(ctx context.Context, url string) (LinkPreview, error) {
	row := q.db.QueryRow(ctx, getLinkPreview, url)
	var i LinkPreview
	err := row.Scan(
		&i.Url,
		&i.Title,
		&i.Description,
		&i.ImageUrl,
		&i.SiteName,
		&i.FetchedAt,
		&i.FailedAt,
	)
	return i, err
}

const upsertLinkPreview = `-- name: UpsertLinkPreview :exec
insert into link_previews (url, title, description, image_url, site_name, failed_at)
values ($1, $2, $3, $4, $5, $6)
on conflict (url) do update set
    title = excluded.title,
    description = excluded.description,
    image_url = excluded.image_url,
    site_name = excluded.site_name,
    failed_at = excluded.failed_at,
    fetched_at = now()
`

type UpsertLinkPreviewParams struct {
	Url         string             `json:"url"`
	Title       string             `json:"title"`
	Description string             `json:"description"`
	ImageUrl    string             `json:"image_url"`
	SiteName    string             `json:"site_name"`
	FailedAt    pgtype.Timestamptz `json:"failed_at"`
}

func (q *Queries) UpsertLinkPreview(ctx context.Context, arg UpsertLinkPreviewParams) error {
	_, err := q.db.Exec(ctx, upsertLinkPreview,
		arg.Url,
		arg.Title,
		arg.Description,
		arg.ImageUrl,
		arg.SiteName,
		arg.FailedAt,
	)
	return err
}
