// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: profile.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const profileAssignedIssues = `-- name: ProfileAssignedIssues :many
select i.id, i.project_id, i.number, i.title, i.status, i.priority, i.updated_at,
       p.key as project_key, p.name as project_name
from issues i
join projects p on p.id = i.project_id
join workspace_members mv on mv.workspace_id = p.workspace_id and mv.user_id = $1
where i.assignee_id = $2
order by i.updated_at desc
limit 10
`

type ProfileAssignedIssuesParams struct {
	UserID     pgtype.UUID `json:"user_id"`
	AssigneeID pgtype.UUID `json:"assignee_id"`
}

type ProfileAssignedIssuesRow struct {
	ID          pgtype.UUID        `json:"id"`
	ProjectID   pgtype.UUID        `json:"project_id"`
	Number      int32              `json:"number"`
	Title       string             `json:"title"`
	Status      string             `json:"status"`
	Priority    string             `json:"priority"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
	ProjectKey  string             `json:"project_key"`
	ProjectName string             `json:"project_name"`
}

// most recently touched issues assigned to the target, in shared workspaces
func (q *Queries) ProfileAssignedIssues(ctx context.Context, arg ProfileAssignedIssuesParams) ([]ProfileAssignedIssuesRow, error) {
	rows, err := q.db.Query(ctx, profileAssignedIssues, arg.UserID, arg.AssigneeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ProfileAssignedIssuesRow{}
	for rows.Next() {
		var i ProfileAssignedIssuesRow
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.Number,
			&i.Title,
			&i.Status,
			&i.Priority,
			&i.UpdatedAt,
			&i.ProjectKey,
			&i.ProjectName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const profileMentionsOf = `-- name: ProfileMentionsOf :many
select m.id, m.body, m.created_at, c.project_id,
       coalesce(u.name, a.name, nullif(m.author_name_snapshot, ''), '') as author_name,
       (m.author_agent_id is not null or m.author_kind_snapshot = 'agent') as author_is_agent
from messages m
join conversations c on c.id = m.conversation_id
join projects p on p.id = c.project_id
join workspace_members mv on mv.workspace_id = p.workspace_id and mv.user_id = $1
join users me on me.id = $2
left join users u on u.id = m.author_user_id
left join agents a on a.id = m.author_agent_id
where m.deleted_at is null
  and position(lower('@' || me.name) in lower(m.body)) > 0
  and (m.author_user_id is null or m.author_user_id <> $2)
order by m.created_at desc
limit 20
`

type ProfileMentionsOfParams struct {
	UserID pgtype.UUID `json:"user_id"`
	ID     pgtype.UUID `json:"id"`
}

type ProfileMentionsOfRow struct {
	ID            pgtype.UUID        `json:"id"`
	Body          string             `json:"body"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	ProjectID     pgtype.UUID        `json:"project_id"`
	AuthorName    string             `json:"author_name"`
	AuthorIsAgent pgtype.Bool        `json:"author_is_agent"`
}

// recent messages @naming the target, visible to the viewer
func (q *Queries) ProfileMentionsOf(ctx context.Context, arg ProfileMentionsOfParams) ([]ProfileMentionsOfRow, error) {
	rows, err := q.db.Query(ctx, profileMentionsOf, arg.UserID, arg.ID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ProfileMentionsOfRow{}
	for rows.Next() {
		var i ProfileMentionsOfRow
		if err := rows.Scan(
			&i.ID,
			&i.Body,
			&i.CreatedAt,
			&i.ProjectID,
			&i.AuthorName,
			&i.AuthorIsAgent,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const profileMessageCount = `-- name: ProfileMessageCount :one
select count(*)::int
from messages m
join conversations c on c.id = m.conversation_id
join projects p on p.id = c.project_id
join workspace_members mv on mv.workspace_id = p.workspace_id and mv.user_id = $1
where m.author_user_id = $2 and m.deleted_at is null
`

type ProfileMessageCountParams struct {
	UserID       pgtype.UUID `json:"user_id"`
	AuthorUserID pgtype.UUID `json:"author_user_id"`
}

func (q *Queries) ProfileMessageCount(ctx context.Context, arg ProfileMessageCountParams) (int32, error) {
	row := q.db.QueryRow(ctx, profileMessageCount, arg.UserID, arg.AuthorUserID)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}

const profileRecentMessages = `-- name: ProfileRecentMessages :many
select m.id, m.body, m.created_at, c.project_id, p.name as project_name
from messages m
join conversations c on c.id = m.conversation_id
join projects p on p.id = c.project_id
join workspace_members mv on mv.workspace_id = p.workspace_id and mv.user_id = $1
where m.author_user_id = $2 and m.deleted_at is null
order by m.created_at desc
limit 10
`

type ProfileRecentMessagesParams struct {
	UserID       pgtype.UUID `json:"user_id"`
	AuthorUserID pgtype.UUID `json:"author_user_id"`
}

type ProfileRecentMessagesRow struct {
	ID          pgtype.UUID        `json:"id"`
	Body        string             `json:"body"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	ProjectID   pgtype.UUID        `json:"project_id"`
	ProjectName string             `json:"project_name"`
}

// target's latest public messages in shared workspaces
func (q *Queries) ProfileRecentMessages(ctx context.Context, arg ProfileRecentMessagesParams) ([]ProfileRecentMessagesRow, error) {
	rows, err := q.db.Query(ctx, profileRecentMessages, arg.UserID, arg.AuthorUserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ProfileRecentMessagesRow{}
	for rows.Next() {
		var i ProfileRecentMessagesRow
		if err := rows.Scan(
			&i.ID,
			&i.Body,
			&i.CreatedAt,
			&i.ProjectID,
			&i.ProjectName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const sharedWorkspaces = `-- name: SharedWorkspaces :many

select w.id, w.name, w.slug, w.avatar_key, mt.role
from workspaces w
join workspace_members mv on mv.workspace_id = w.id and mv.user_id = $1
join workspace_members mt on mt.workspace_id = w.id and mt.user_id = $2
order by w.name
`

type SharedWorkspacesParams struct {
	UserID   pgtype.UUID `json:"user_id"`
	UserID_2 pgtype.UUID `json:"user_id_2"`
}

type SharedWorkspacesRow struct {
	ID        pgtype.UUID `json:"id"`
	Name      string      `json:"name"`
	Slug      string      `json:"slug"`
	AvatarKey pgtype.Text `json:"avatar_key"`
	Role      string      `json:"role"`
}

// Profile surface: what a workspace-mate sees on a user's details page.
// Every query is gated on the VIEWER's membership — a profile only exposes
// activity inside workspaces both parties share.
func (q *Queries) SharedWorkspaces(ctx context.Context, arg SharedWorkspacesParams) ([]SharedWorkspacesRow, error) {
	rows, err := q.db.Query(ctx, sharedWorkspaces, arg.UserID, arg.UserID_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SharedWorkspacesRow{}
	for rows.Next() {
		var i SharedWorkspacesRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Slug,
			&i.AvatarKey,
			&i.Role,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
