// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: projects.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const addProjectMember = `-- name: AddProjectMember :exec
insert into project_members (project_id, user_id)
values ($1, $2)
`

type AddProjectMemberParams struct {
	ProjectID pgtype.UUID `json:"project_id"`
	UserID    pgtype.UUID `json:"user_id"`
}

func (q *Queries) AddProjectMember(ctx context.Context, arg AddProjectMemberParams) error {
	_, err := q.db.Exec(ctx, addProjectMember, arg.ProjectID, arg.UserID)
	return err
}

const createProject = `-- name: CreateProject :one
insert into projects (workspace_id, key, name, description, icon, color, created_by)
values ($1, $2, $3, $4, $5, $6, $7)
returning id, workspace_id, key, name, description, icon, color, created_at
`

type CreateProjectParams struct {
	WorkspaceID pgtype.UUID `json:"workspace_id"`
	Key         string      `json:"key"`
	Name        string      `json:"name"`
	Description string      `json:"description"`
	Icon        pgtype.Text `json:"icon"`
	Color       pgtype.Text `json:"color"`
	CreatedBy   pgtype.UUID `json:"created_by"`
}

type CreateProjectRow struct {
	ID          pgtype.UUID        `json:"id"`
	WorkspaceID pgtype.UUID        `json:"workspace_id"`
	Key         string             `json:"key"`
	Name        string             `json:"name"`
	Description string             `json:"description"`
	Icon        pgtype.Text        `json:"icon"`
	Color       pgtype.Text        `json:"color"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) CreateProject(ctx context.Context, arg CreateProjectParams) (CreateProjectRow, error) {
	row := q.db.QueryRow(ctx, createProject,
		arg.WorkspaceID,
		arg.Key,
		arg.Name,
		arg.Description,
		arg.Icon,
		arg.Color,
		arg.CreatedBy,
	)
	var i CreateProjectRow
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Key,
		&i.Name,
		&i.Description,
		&i.Icon,
		&i.Color,
		&i.CreatedAt,
	)
	return i, err
}

const getProjectByID = `-- name: GetProjectByID :one
select id, workspace_id, key, name, description, icon, color, created_at
from projects
where id = $1
`

type GetProjectByIDRow struct {
	ID          pgtype.UUID        `json:"id"`
	WorkspaceID pgtype.UUID        `json:"workspace_id"`
	Key         string             `json:"key"`
	Name        string             `json:"name"`
	Description string             `json:"description"`
	Icon        pgtype.Text        `json:"icon"`
	Color       pgtype.Text        `json:"color"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) GetProjectByID(ctx context.Context, id pgtype.UUID) (GetProjectByIDRow, error) {
	row := q.db.QueryRow(ctx, getProjectByID, id)
	var i GetProjectByIDRow
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Key,
		&i.Name,
		&i.Description,
		&i.Icon,
		&i.Color,
		&i.CreatedAt,
	)
	return i, err
}

const listProjectsForUser = `-- name: ListProjectsForUser :many
select p.id, p.workspace_id, p.key, p.name, p.description, p.icon, p.color, p.created_at
from projects p
join workspace_members wm on wm.workspace_id = p.workspace_id
where wm.user_id = $1
order by p.name
`

type ListProjectsForUserRow struct {
	ID          pgtype.UUID        `json:"id"`
	WorkspaceID pgtype.UUID        `json:"workspace_id"`
	Key         string             `json:"key"`
	Name        string             `json:"name"`
	Description string             `json:"description"`
	Icon        pgtype.Text        `json:"icon"`
	Color       pgtype.Text        `json:"color"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) ListProjectsForUser(ctx context.Context, userID pgtype.UUID) ([]ListProjectsForUserRow, error) {
	rows, err := q.db.Query(ctx, listProjectsForUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListProjectsForUserRow{}
	for rows.Next() {
		var i ListProjectsForUserRow
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.Key,
			&i.Name,
			&i.Description,
			&i.Icon,
			&i.Color,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const projectCounts = `-- name: ProjectCounts :one
select
  (select count(*) from project_members pm where pm.project_id = $1) as members,
  (select count(*) from messages m
     join conversations c on c.id = m.conversation_id
     where c.project_id = $1 and m.deleted_at is null) as messages,
  (select count(*) from conversations c where c.project_id = $1) as conversations
`

type ProjectCountsRow struct {
	Members       int64 `json:"members"`
	Messages      int64 `json:"messages"`
	Conversations int64 `json:"conversations"`
}

func (q *Queries) ProjectCounts(ctx context.Context, projectID pgtype.UUID) (ProjectCountsRow, error) {
	row := q.db.QueryRow(ctx, projectCounts, projectID)
	var i ProjectCountsRow
	err := row.Scan(&i.Members, &i.Messages, &i.Conversations)
	return i, err
}

const projectWorkspaceRole = `-- name: ProjectWorkspaceRole :one
select cast(coalesce((
    select wm.role from workspace_members wm
    where wm.workspace_id = p.workspace_id and wm.user_id = $2
), '') as text) as role
from projects p
where p.id = $1
`

type ProjectWorkspaceRoleParams struct {
	ID     pgtype.UUID `json:"id"`
	UserID pgtype.UUID `json:"user_id"`
}

// caller's workspace role for the project, empty when not a member
func (q *Queries) ProjectWorkspaceRole(ctx context.Context, arg ProjectWorkspaceRoleParams) (string, error) {
	row := q.db.QueryRow(ctx, projectWorkspaceRole, arg.ID, arg.UserID)
	var role string
	err := row.Scan(&role)
	return role, err
}

const updateProject = `-- name: UpdateProject :one
update projects
set name = coalesce($1, name),
    description = coalesce($2, description),
    icon = coalesce($3, icon),
    color = coalesce($4, color),
    updated_at = now()
where id = $5
returning id, workspace_id, key, name, description, icon, color, created_at
`

type UpdateProjectParams struct {
	Name        pgtype.Text `json:"name"`
	Description pgtype.Text `json:"description"`
	Icon        pgtype.Text `json:"icon"`
	Color       pgtype.Text `json:"color"`
	ID          pgtype.UUID `json:"id"`
}

type UpdateProjectRow struct {
	ID          pgtype.UUID        `json:"id"`
	WorkspaceID pgtype.UUID        `json:"workspace_id"`
	Key         string             `json:"key"`
	Name        string             `json:"name"`
	Description string             `json:"description"`
	Icon        pgtype.Text        `json:"icon"`
	Color       pgtype.Text        `json:"color"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) UpdateProject(ctx context.Context, arg UpdateProjectParams) (UpdateProjectRow, error) {
	row := q.db.QueryRow(ctx, updateProject,
		arg.Name,
		arg.Description,
		arg.Icon,
		arg.Color,
		arg.ID,
	)
	var i UpdateProjectRow
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Key,
		&i.Name,
		&i.Description,
		&i.Icon,
		&i.Color,
		&i.CreatedAt,
	)
	return i, err
}
