// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: reminders.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createReminder = `-- name: CreateReminder :one
insert into reminders (user_id, message_id, project_id, fire_at)
values ($1, $2, $3, $4)
returning id, user_id, message_id, project_id, fire_at, fired_at, created_at
`

type CreateReminderParams struct {
	UserID    pgtype.UUID        `json:"user_id"`
	MessageID pgtype.UUID        `json:"message_id"`
	ProjectID pgtype.UUID        `json:"project_id"`
	FireAt    pgtype.Timestamptz `json:"fire_at"`
}

func (q *Queries) CreateReminder(ctx context.Context, arg CreateReminderParams) (Reminder, error) {
	row := q.db.QueryRow(ctx, createReminder,
		arg.UserID,
		arg.MessageID,
		arg.ProjectID,
		arg.FireAt,
	)
	var i Reminder
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.MessageID,
		&i.ProjectID,
		&i.FireAt,
		&i.FiredAt,
		&i.CreatedAt,
	)
	return i, err
}

const deleteReminder = `-- name: DeleteReminder :exec
delete from reminders
where id = $1 and user_id = $2
`

type DeleteReminderParams struct {
	ID     pgtype.UUID `json:"id"`
	UserID pgtype.UUID `json:"user_id"`
}

func (q *Queries) DeleteReminder(ctx context.Context, arg DeleteReminderParams) error {
	_, err := q.db.Exec(ctx, deleteReminder, arg.ID, arg.UserID)
	return err
}

const listDueReminders = `-- name: ListDueReminders :many
select r.id, r.user_id, r.message_id, r.project_id, r.fire_at, r.fired_at, r.created_at, m.body as message_body, m.conversation_id,
       coalesce(u.name, a.name, nullif(m.author_name_snapshot, ''), '') as author_name
from reminders r
join messages m on m.id = r.message_id
left join users u on u.id = m.author_user_id
left join agents a on a.id = m.author_agent_id
where r.fired_at is null and r.fire_at <= now()
order by r.fire_at
limit 100
`

type ListDueRemindersRow struct {
	ID             pgtype.UUID        `json:"id"`
	UserID         pgtype.UUID        `json:"user_id"`
	MessageID      pgtype.UUID        `json:"message_id"`
	ProjectID      pgtype.UUID        `json:"project_id"`
	FireAt         pgtype.Timestamptz `json:"fire_at"`
	FiredAt        pgtype.Timestamptz `json:"fired_at"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	MessageBody    string             `json:"message_body"`
	ConversationID pgtype.UUID        `json:"conversation_id"`
	AuthorName     string             `json:"author_name"`
}

func (q *Queries) ListDueReminders(ctx context.Context) ([]ListDueRemindersRow, error) {
	rows, err := q.db.Query(ctx, listDueReminders)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListDueRemindersRow{}
	for rows.Next() {
		var i ListDueRemindersRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.MessageID,
			&i.ProjectID,
			&i.FireAt,
			&i.FiredAt,
			&i.CreatedAt,
			&i.MessageBody,
			&i.ConversationID,
			&i.AuthorName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listReminders = `-- name: ListReminders :many
select r.id, r.user_id, r.message_id, r.project_id, r.fire_at, r.fired_at, r.created_at, m.body as message_body, m.conversation_id,
       coalesce(u.name, a.name, nullif(m.author_name_snapshot, ''), '') as author_name
from reminders r
join messages m on m.id = r.message_id
left join users u on u.id = m.author_user_id
left join agents a on a.id = m.author_agent_id
where r.user_id = $1
  and (r.fired_at is null or r.fired_at > now() - interval '24 hours')
  and m.deleted_at is null
order by r.fired_at is null desc, r.fire_at
limit 100
`

type ListRemindersRow struct {
	ID             pgtype.UUID        `json:"id"`
	UserID         pgtype.UUID        `json:"user_id"`
	MessageID      pgtype.UUID        `json:"message_id"`
	ProjectID      pgtype.UUID        `json:"project_id"`
	FireAt         pgtype.Timestamptz `json:"fire_at"`
	FiredAt        pgtype.Timestamptz `json:"fired_at"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	MessageBody    string             `json:"message_body"`
	ConversationID pgtype.UUID        `json:"conversation_id"`
	AuthorName     string             `json:"author_name"`
}

// pending plus recently-fired (24h) so the Reminders view can show what
// just went off; message join carries the snippet to display
func (q *Queries) ListReminders(ctx context.Context, userID pgtype.UUID) ([]ListRemindersRow, error) {
	rows, err := q.db.Query(ctx, listReminders, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListRemindersRow{}
	for rows.Next() {
		var i ListRemindersRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.MessageID,
			&i.ProjectID,
			&i.FireAt,
			&i.FiredAt,
			&i.CreatedAt,
			&i.MessageBody,
			&i.ConversationID,
			&i.AuthorName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markReminderFired = `-- name: MarkReminderFired :exec
update reminders set fired_at = now() where id = $1
`

func (q *Queries) MarkReminderFired(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, markReminderFired, id)
	return err
}
