// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: reviews.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createReview = `-- name: CreateReview :one
insert into agent_reviews (project_id, issue_id, agent_id, title, summary,
                           files, decisions, actions, links, verify, supersedes,
                           scenes)
values ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12)
returning id, project_id, issue_id, agent_id, status, title, summary, files, decisions, actions, links, verify, supersedes, responded_by, response, responded_at, created_at, updated_at, scenes
`

type CreateReviewParams struct {
	ProjectID  pgtype.UUID `json:"project_id"`
	IssueID    pgtype.UUID `json:"issue_id"`
	AgentID    pgtype.UUID `json:"agent_id"`
	Title      string      `json:"title"`
	Summary    string      `json:"summary"`
	Files      []byte      `json:"files"`
	Decisions  []byte      `json:"decisions"`
	Actions    []byte      `json:"actions"`
	Links      []byte      `json:"links"`
	Verify     string      `json:"verify"`
	Supersedes pgtype.UUID `json:"supersedes"`
	Scenes     []byte      `json:"scenes"`
}

func (q *Queries) CreateReview(ctx context.Context, arg CreateReviewParams) (AgentReview, error) {
	row := q.db.QueryRow(ctx, createReview,
		arg.ProjectID,
		arg.IssueID,
		arg.AgentID,
		arg.Title,
		arg.Summary,
		arg.Files,
		arg.Decisions,
		arg.Actions,
		arg.Links,
		arg.Verify,
		arg.Supersedes,
		arg.Scenes,
	)
	var i AgentReview
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.IssueID,
		&i.AgentID,
		&i.Status,
		&i.Title,
		&i.Summary,
		&i.Files,
		&i.Decisions,
		&i.Actions,
		&i.Links,
		&i.Verify,
		&i.Supersedes,
		&i.RespondedBy,
		&i.Response,
		&i.RespondedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Scenes,
	)
	return i, err
}

const getAgentReviewMode = `-- name: GetAgentReviewMode :one
select review_mode from agents where id = $1
`

func (q *Queries) GetAgentReviewMode(ctx context.Context, id pgtype.UUID) (string, error) {
	row := q.db.QueryRow(ctx, getAgentReviewMode, id)
	var review_mode string
	err := row.Scan(&review_mode)
	return review_mode, err
}

const getReview = `-- name: GetReview :one
select r.id, r.project_id, r.issue_id, r.agent_id, r.status, r.title, r.summary, r.files, r.decisions, r.actions, r.links, r.verify, r.supersedes, r.responded_by, r.response, r.responded_at, r.created_at, r.updated_at, r.scenes, a.name as agent_name, a.slug as agent_slug, a.avatar_key as agent_avatar,
       p.key as project_key, i.number as issue_number,
       u.name as responder_name, u.avatar_key as responder_avatar
from agent_reviews r
join agents a on a.id = r.agent_id
join projects p on p.id = r.project_id
left join issues i on i.id = r.issue_id
left join users u on u.id = r.responded_by
where r.id = $1
`

type GetReviewRow struct {
	ID              pgtype.UUID        `json:"id"`
	ProjectID       pgtype.UUID        `json:"project_id"`
	IssueID         pgtype.UUID        `json:"issue_id"`
	AgentID         pgtype.UUID        `json:"agent_id"`
	Status          string             `json:"status"`
	Title           string             `json:"title"`
	Summary         string             `json:"summary"`
	Files           []byte             `json:"files"`
	Decisions       []byte             `json:"decisions"`
	Actions         []byte             `json:"actions"`
	Links           []byte             `json:"links"`
	Verify          string             `json:"verify"`
	Supersedes      pgtype.UUID        `json:"supersedes"`
	RespondedBy     pgtype.UUID        `json:"responded_by"`
	Response        string             `json:"response"`
	RespondedAt     pgtype.Timestamptz `json:"responded_at"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
	Scenes          []byte             `json:"scenes"`
	AgentName       string             `json:"agent_name"`
	AgentSlug       string             `json:"agent_slug"`
	AgentAvatar     pgtype.Text        `json:"agent_avatar"`
	ProjectKey      string             `json:"project_key"`
	IssueNumber     pgtype.Int4        `json:"issue_number"`
	ResponderName   pgtype.Text        `json:"responder_name"`
	ResponderAvatar pgtype.Text        `json:"responder_avatar"`
}

func (q *Queries) GetReview(ctx context.Context, id pgtype.UUID) (GetReviewRow, error) {
	row := q.db.QueryRow(ctx, getReview, id)
	var i GetReviewRow
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.IssueID,
		&i.AgentID,
		&i.Status,
		&i.Title,
		&i.Summary,
		&i.Files,
		&i.Decisions,
		&i.Actions,
		&i.Links,
		&i.Verify,
		&i.Supersedes,
		&i.RespondedBy,
		&i.Response,
		&i.RespondedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Scenes,
		&i.AgentName,
		&i.AgentSlug,
		&i.AgentAvatar,
		&i.ProjectKey,
		&i.IssueNumber,
		&i.ResponderName,
		&i.ResponderAvatar,
	)
	return i, err
}

const listIssueReviews = `-- name: ListIssueReviews :many
select r.id, r.project_id, r.issue_id, r.agent_id, r.status, r.title, r.summary, r.files, r.decisions, r.actions, r.links, r.verify, r.supersedes, r.responded_by, r.response, r.responded_at, r.created_at, r.updated_at, r.scenes, a.name as agent_name, a.slug as agent_slug, a.avatar_key as agent_avatar,
       p.key as project_key, i.number as issue_number,
       u.name as responder_name, u.avatar_key as responder_avatar
from agent_reviews r
join agents a on a.id = r.agent_id
join projects p on p.id = r.project_id
left join issues i on i.id = r.issue_id
left join users u on u.id = r.responded_by
where r.issue_id = $1
order by r.created_at desc
`

type ListIssueReviewsRow struct {
	ID              pgtype.UUID        `json:"id"`
	ProjectID       pgtype.UUID        `json:"project_id"`
	IssueID         pgtype.UUID        `json:"issue_id"`
	AgentID         pgtype.UUID        `json:"agent_id"`
	Status          string             `json:"status"`
	Title           string             `json:"title"`
	Summary         string             `json:"summary"`
	Files           []byte             `json:"files"`
	Decisions       []byte             `json:"decisions"`
	Actions         []byte             `json:"actions"`
	Links           []byte             `json:"links"`
	Verify          string             `json:"verify"`
	Supersedes      pgtype.UUID        `json:"supersedes"`
	RespondedBy     pgtype.UUID        `json:"responded_by"`
	Response        string             `json:"response"`
	RespondedAt     pgtype.Timestamptz `json:"responded_at"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
	Scenes          []byte             `json:"scenes"`
	AgentName       string             `json:"agent_name"`
	AgentSlug       string             `json:"agent_slug"`
	AgentAvatar     pgtype.Text        `json:"agent_avatar"`
	ProjectKey      string             `json:"project_key"`
	IssueNumber     pgtype.Int4        `json:"issue_number"`
	ResponderName   pgtype.Text        `json:"responder_name"`
	ResponderAvatar pgtype.Text        `json:"responder_avatar"`
}

func (q *Queries) ListIssueReviews(ctx context.Context, issueID pgtype.UUID) ([]ListIssueReviewsRow, error) {
	rows, err := q.db.Query(ctx, listIssueReviews, issueID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListIssueReviewsRow{}
	for rows.Next() {
		var i ListIssueReviewsRow
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.IssueID,
			&i.AgentID,
			&i.Status,
			&i.Title,
			&i.Summary,
			&i.Files,
			&i.Decisions,
			&i.Actions,
			&i.Links,
			&i.Verify,
			&i.Supersedes,
			&i.RespondedBy,
			&i.Response,
			&i.RespondedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Scenes,
			&i.AgentName,
			&i.AgentSlug,
			&i.AgentAvatar,
			&i.ProjectKey,
			&i.IssueNumber,
			&i.ResponderName,
			&i.ResponderAvatar,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMyPendingReviews = `-- name: ListMyPendingReviews :many
select r.id, r.project_id, r.title, r.created_at,
       a.id as agent_id, a.name as agent_name, a.slug as agent_slug, a.avatar_key as agent_avatar,
       p.key as project_key, p.name as project_name
from agent_reviews r
join agents a on a.id = r.agent_id
join projects p on p.id = r.project_id
join workspace_members wm on wm.workspace_id = p.workspace_id and wm.user_id = $1
where r.status = 'pending'
order by r.created_at desc
limit 50
`

type ListMyPendingReviewsRow struct {
	ID          pgtype.UUID        `json:"id"`
	ProjectID   pgtype.UUID        `json:"project_id"`
	Title       string             `json:"title"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	AgentID     pgtype.UUID        `json:"agent_id"`
	AgentName   string             `json:"agent_name"`
	AgentSlug   string             `json:"agent_slug"`
	AgentAvatar pgtype.Text        `json:"agent_avatar"`
	ProjectKey  string             `json:"project_key"`
	ProjectName string             `json:"project_name"`
}

// reviews awaiting a human verdict across every workspace the user belongs to
func (q *Queries) ListMyPendingReviews(ctx context.Context, userID pgtype.UUID) ([]ListMyPendingReviewsRow, error) {
	rows, err := q.db.Query(ctx, listMyPendingReviews, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListMyPendingReviewsRow{}
	for rows.Next() {
		var i ListMyPendingReviewsRow
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.Title,
			&i.CreatedAt,
			&i.AgentID,
			&i.AgentName,
			&i.AgentSlug,
			&i.AgentAvatar,
			&i.ProjectKey,
			&i.ProjectName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProjectReviews = `-- name: ListProjectReviews :many
select r.id, r.project_id, r.issue_id, r.agent_id, r.status, r.title, r.summary, r.files, r.decisions, r.actions, r.links, r.verify, r.supersedes, r.responded_by, r.response, r.responded_at, r.created_at, r.updated_at, r.scenes, a.name as agent_name, a.slug as agent_slug, a.avatar_key as agent_avatar,
       p.key as project_key, i.number as issue_number,
       u.name as responder_name, u.avatar_key as responder_avatar
from agent_reviews r
join agents a on a.id = r.agent_id
join projects p on p.id = r.project_id
left join issues i on i.id = r.issue_id
left join users u on u.id = r.responded_by
where r.project_id = $1
  and r.status = coalesce($2::text, r.status)
order by r.created_at desc
limit $3
`

type ListProjectReviewsParams struct {
	ProjectID pgtype.UUID `json:"project_id"`
	Status    pgtype.Text `json:"status"`
	Lim       int32       `json:"lim"`
}

type ListProjectReviewsRow struct {
	ID              pgtype.UUID        `json:"id"`
	ProjectID       pgtype.UUID        `json:"project_id"`
	IssueID         pgtype.UUID        `json:"issue_id"`
	AgentID         pgtype.UUID        `json:"agent_id"`
	Status          string             `json:"status"`
	Title           string             `json:"title"`
	Summary         string             `json:"summary"`
	Files           []byte             `json:"files"`
	Decisions       []byte             `json:"decisions"`
	Actions         []byte             `json:"actions"`
	Links           []byte             `json:"links"`
	Verify          string             `json:"verify"`
	Supersedes      pgtype.UUID        `json:"supersedes"`
	RespondedBy     pgtype.UUID        `json:"responded_by"`
	Response        string             `json:"response"`
	RespondedAt     pgtype.Timestamptz `json:"responded_at"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
	Scenes          []byte             `json:"scenes"`
	AgentName       string             `json:"agent_name"`
	AgentSlug       string             `json:"agent_slug"`
	AgentAvatar     pgtype.Text        `json:"agent_avatar"`
	ProjectKey      string             `json:"project_key"`
	IssueNumber     pgtype.Int4        `json:"issue_number"`
	ResponderName   pgtype.Text        `json:"responder_name"`
	ResponderAvatar pgtype.Text        `json:"responder_avatar"`
}

func (q *Queries) ListProjectReviews(ctx context.Context, arg ListProjectReviewsParams) ([]ListProjectReviewsRow, error) {
	rows, err := q.db.Query(ctx, listProjectReviews, arg.ProjectID, arg.Status, arg.Lim)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListProjectReviewsRow{}
	for rows.Next() {
		var i ListProjectReviewsRow
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.IssueID,
			&i.AgentID,
			&i.Status,
			&i.Title,
			&i.Summary,
			&i.Files,
			&i.Decisions,
			&i.Actions,
			&i.Links,
			&i.Verify,
			&i.Supersedes,
			&i.RespondedBy,
			&i.Response,
			&i.RespondedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Scenes,
			&i.AgentName,
			&i.AgentSlug,
			&i.AgentAvatar,
			&i.ProjectKey,
			&i.IssueNumber,
			&i.ResponderName,
			&i.ResponderAvatar,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const pendingReviewCount = `-- name: PendingReviewCount :one
select count(*)::int from agent_reviews
where project_id = $1 and status = 'pending'
`

func (q *Queries) PendingReviewCount(ctx context.Context, projectID pgtype.UUID) (int32, error) {
	row := q.db.QueryRow(ctx, pendingReviewCount, projectID)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}

const pendingReviewCounts = `-- name: PendingReviewCounts :many
select p.id as project_id, count(r.id)::int as pending
from projects p
join workspace_members wm on wm.workspace_id = p.workspace_id
  and wm.user_id = $1
join agent_reviews r on r.project_id = p.id and r.status = 'pending'
group by p.id
`

type PendingReviewCountsRow struct {
	ProjectID pgtype.UUID `json:"project_id"`
	Pending   int32       `json:"pending"`
}

// per-project count of reviews awaiting a human verdict
func (q *Queries) PendingReviewCounts(ctx context.Context, userID pgtype.UUID) ([]PendingReviewCountsRow, error) {
	rows, err := q.db.Query(ctx, pendingReviewCounts, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PendingReviewCountsRow{}
	for rows.Next() {
		var i PendingReviewCountsRow
		if err := rows.Scan(&i.ProjectID, &i.Pending); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const respondToReview = `-- name: RespondToReview :one
update agent_reviews
set status = $2, responded_by = $3, response = $4,
    responded_at = now(), updated_at = now()
where id = $1 and status = 'pending'
returning id, project_id, issue_id, agent_id, status, title, summary, files, decisions, actions, links, verify, supersedes, responded_by, response, responded_at, created_at, updated_at, scenes
`

type RespondToReviewParams struct {
	ID          pgtype.UUID `json:"id"`
	Status      string      `json:"status"`
	RespondedBy pgtype.UUID `json:"responded_by"`
	Response    string      `json:"response"`
}

// human verdict. Only pending reviews can be answered.
func (q *Queries) RespondToReview(ctx context.Context, arg RespondToReviewParams) (AgentReview, error) {
	row := q.db.QueryRow(ctx, respondToReview,
		arg.ID,
		arg.Status,
		arg.RespondedBy,
		arg.Response,
	)
	var i AgentReview
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.IssueID,
		&i.AgentID,
		&i.Status,
		&i.Title,
		&i.Summary,
		&i.Files,
		&i.Decisions,
		&i.Actions,
		&i.Links,
		&i.Verify,
		&i.Supersedes,
		&i.RespondedBy,
		&i.Response,
		&i.RespondedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Scenes,
	)
	return i, err
}

const reviewAgentProject = `-- name: ReviewAgentProject :one
select r.project_id, a.review_mode
from agent_reviews r
join agents a on a.id = r.agent_id
where r.id = $1
`

type ReviewAgentProjectRow struct {
	ProjectID  pgtype.UUID `json:"project_id"`
	ReviewMode string      `json:"review_mode"`
}

// the review's project + the agent's review_mode, for MCP auth + gating
func (q *Queries) ReviewAgentProject(ctx context.Context, id pgtype.UUID) (ReviewAgentProjectRow, error) {
	row := q.db.QueryRow(ctx, reviewAgentProject, id)
	var i ReviewAgentProjectRow
	err := row.Scan(&i.ProjectID, &i.ReviewMode)
	return i, err
}

const reviewProjectMembership = `-- name: ReviewProjectMembership :one
select wm.role
from agent_reviews r
join projects p on p.id = r.project_id
join workspace_members wm on wm.workspace_id = p.workspace_id and wm.user_id = $2
where r.id = $1
`

type ReviewProjectMembershipParams struct {
	ID     pgtype.UUID `json:"id"`
	UserID pgtype.UUID `json:"user_id"`
}

// does user X belong to the workspace owning review Y's project?
func (q *Queries) ReviewProjectMembership(ctx context.Context, arg ReviewProjectMembershipParams) (string, error) {
	row := q.db.QueryRow(ctx, reviewProjectMembership, arg.ID, arg.UserID)
	var role string
	err := row.Scan(&role)
	return role, err
}

const supersedeReview = `-- name: SupersedeReview :exec
update agent_reviews
set status = 'superseded', updated_at = now()
where id = $1 and status = 'pending'
`

// a resubmission retires the previous pending review
func (q *Queries) SupersedeReview(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, supersedeReview, id)
	return err
}
