// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: saved.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const isMessageSaved = `-- name: IsMessageSaved :one
select exists(
    select 1 from saved_messages
    where user_id = $1 and message_id = $2
) as saved
`

type IsMessageSavedParams struct {
	UserID    pgtype.UUID `json:"user_id"`
	MessageID pgtype.UUID `json:"message_id"`
}

func (q *Queries) IsMessageSaved(ctx context.Context, arg IsMessageSavedParams) (bool, error) {
	row := q.db.QueryRow(ctx, isMessageSaved, arg.UserID, arg.MessageID)
	var saved bool
	err := row.Scan(&saved)
	return saved, err
}

const listSavedMessageIDs = `-- name: ListSavedMessageIDs :many
select message_id from saved_messages where user_id = $1
`

func (q *Queries) ListSavedMessageIDs(ctx context.Context, userID pgtype.UUID) ([]pgtype.UUID, error) {
	rows, err := q.db.Query(ctx, listSavedMessageIDs, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []pgtype.UUID{}
	for rows.Next() {
		var message_id pgtype.UUID
		if err := rows.Scan(&message_id); err != nil {
			return nil, err
		}
		items = append(items, message_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSavedMessages = `-- name: ListSavedMessages :many
select m.id, m.conversation_id, m.body, m.mentions, m.tags, m.silent, m.created_at, m.edited_at, m.deleted_at, m.parent_id,
       m.author_user_id, m.author_agent_id, m.author_kind_snapshot,
       coalesce(u.name, a.name, nullif(m.author_name_snapshot, ''), '') as author_name,
       coalesce(u.avatar_key, a.avatar_key) as author_avatar,
       coalesce(pu.name, pa.name, nullif(pm.author_name_snapshot, ''), '') as parent_author_name,
       pm.body as parent_body,
       (pm.id is not null and pm.deleted_at is not null) as parent_deleted,
       t.id as thread_id, t.title as thread_title,
       (select count(*)::int from messages tm
         where tm.conversation_id = t.id and tm.deleted_at is null) as thread_reply_count,
       m.pinned_at, m.forwarded_from,
       f.conversation_id as fwd_conversation_id,
       fcp.project_id as fwd_project_id,
       coalesce(fu.name, fa.name, nullif(f.author_name_snapshot, ''), '') as fwd_author_name,
       c.project_id, p.name as project_name, s.created_at as saved_at
from saved_messages s
join messages m on m.id = s.message_id
join conversations c on c.id = m.conversation_id
join projects p on p.id = c.project_id
left join users u on u.id = m.author_user_id
left join agents a on a.id = m.author_agent_id
left join messages pm on pm.id = m.parent_id
left join users pu on pu.id = pm.author_user_id
left join agents pa on pa.id = pm.author_agent_id
left join conversations t on t.parent_message_id = m.id and t.kind = 'thread'
  and (t.expires_at is null or t.expires_at > now())
left join messages f on f.id = m.forwarded_from
left join conversations fcp on fcp.id = f.conversation_id
left join users fu on fu.id = f.author_user_id
left join agents fa on fa.id = f.author_agent_id
where s.user_id = $1 and m.deleted_at is null
order by s.created_at desc
limit 200
`

type ListSavedMessagesRow struct {
	ID                 pgtype.UUID        `json:"id"`
	ConversationID     pgtype.UUID        `json:"conversation_id"`
	Body               string             `json:"body"`
	Mentions           []byte             `json:"mentions"`
	Tags               []string           `json:"tags"`
	Silent             bool               `json:"silent"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
	EditedAt           pgtype.Timestamptz `json:"edited_at"`
	DeletedAt          pgtype.Timestamptz `json:"deleted_at"`
	ParentID           pgtype.UUID        `json:"parent_id"`
	AuthorUserID       pgtype.UUID        `json:"author_user_id"`
	AuthorAgentID      pgtype.UUID        `json:"author_agent_id"`
	AuthorKindSnapshot string             `json:"author_kind_snapshot"`
	AuthorName         string             `json:"author_name"`
	AuthorAvatar       pgtype.Text        `json:"author_avatar"`
	ParentAuthorName   string             `json:"parent_author_name"`
	ParentBody         pgtype.Text        `json:"parent_body"`
	ParentDeleted      pgtype.Bool        `json:"parent_deleted"`
	ThreadID           pgtype.UUID        `json:"thread_id"`
	ThreadTitle        pgtype.Text        `json:"thread_title"`
	ThreadReplyCount   int32              `json:"thread_reply_count"`
	PinnedAt           pgtype.Timestamptz `json:"pinned_at"`
	ForwardedFrom      pgtype.UUID        `json:"forwarded_from"`
	FwdConversationID  pgtype.UUID        `json:"fwd_conversation_id"`
	FwdProjectID       pgtype.UUID        `json:"fwd_project_id"`
	FwdAuthorName      string             `json:"fwd_author_name"`
	ProjectID          pgtype.UUID        `json:"project_id"`
	ProjectName        string             `json:"project_name"`
	SavedAt            pgtype.Timestamptz `json:"saved_at"`
}

// newest-saved-first; joins mirror GetMessageByID so the client can render
// a normal message plus enough context to deep-link back to it
func (q *Queries) ListSavedMessages(ctx context.Context, userID pgtype.UUID) ([]ListSavedMessagesRow, error) {
	rows, err := q.db.Query(ctx, listSavedMessages, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListSavedMessagesRow{}
	for rows.Next() {
		var i ListSavedMessagesRow
		if err := rows.Scan(
			&i.ID,
			&i.ConversationID,
			&i.Body,
			&i.Mentions,
			&i.Tags,
			&i.Silent,
			&i.CreatedAt,
			&i.EditedAt,
			&i.DeletedAt,
			&i.ParentID,
			&i.AuthorUserID,
			&i.AuthorAgentID,
			&i.AuthorKindSnapshot,
			&i.AuthorName,
			&i.AuthorAvatar,
			&i.ParentAuthorName,
			&i.ParentBody,
			&i.ParentDeleted,
			&i.ThreadID,
			&i.ThreadTitle,
			&i.ThreadReplyCount,
			&i.PinnedAt,
			&i.ForwardedFrom,
			&i.FwdConversationID,
			&i.FwdProjectID,
			&i.FwdAuthorName,
			&i.ProjectID,
			&i.ProjectName,
			&i.SavedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const saveMessage = `-- name: SaveMessage :exec
insert into saved_messages (user_id, message_id)
values ($1, $2)
on conflict do nothing
`

type SaveMessageParams struct {
	UserID    pgtype.UUID `json:"user_id"`
	MessageID pgtype.UUID `json:"message_id"`
}

func (q *Queries) SaveMessage(ctx context.Context, arg SaveMessageParams) error {
	_, err := q.db.Exec(ctx, saveMessage, arg.UserID, arg.MessageID)
	return err
}

const unsaveMessage = `-- name: UnsaveMessage :exec
delete from saved_messages
where user_id = $1 and message_id = $2
`

type UnsaveMessageParams struct {
	UserID    pgtype.UUID `json:"user_id"`
	MessageID pgtype.UUID `json:"message_id"`
}

func (q *Queries) UnsaveMessage(ctx context.Context, arg UnsaveMessageParams) error {
	_, err := q.db.Exec(ctx, unsaveMessage, arg.UserID, arg.MessageID)
	return err
}
