// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: scheduled.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createScheduledMessage = `-- name: CreateScheduledMessage :one
insert into scheduled_messages (user_id, conversation_id, project_id, body, parent_id, tags, send_at)
values ($1, $2, $3,
        $4, $5,
        coalesce($6, '[]'::jsonb), $7)
returning id, user_id, conversation_id, project_id, body, parent_id, tags, send_at, sent_at, created_at
`

type CreateScheduledMessageParams struct {
	UserID         pgtype.UUID        `json:"user_id"`
	ConversationID pgtype.UUID        `json:"conversation_id"`
	ProjectID      pgtype.UUID        `json:"project_id"`
	Body           string             `json:"body"`
	ParentID       pgtype.UUID        `json:"parent_id"`
	Tags           interface{}        `json:"tags"`
	SendAt         pgtype.Timestamptz `json:"send_at"`
}

func (q *Queries) CreateScheduledMessage(ctx context.Context, arg CreateScheduledMessageParams) (ScheduledMessage, error) {
	row := q.db.QueryRow(ctx, createScheduledMessage,
		arg.UserID,
		arg.ConversationID,
		arg.ProjectID,
		arg.Body,
		arg.ParentID,
		arg.Tags,
		arg.SendAt,
	)
	var i ScheduledMessage
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ConversationID,
		&i.ProjectID,
		&i.Body,
		&i.ParentID,
		&i.Tags,
		&i.SendAt,
		&i.SentAt,
		&i.CreatedAt,
	)
	return i, err
}

const deleteScheduledMessage = `-- name: DeleteScheduledMessage :exec
delete from scheduled_messages
where id = $1 and user_id = $2 and sent_at is null
`

type DeleteScheduledMessageParams struct {
	ID     pgtype.UUID `json:"id"`
	UserID pgtype.UUID `json:"user_id"`
}

func (q *Queries) DeleteScheduledMessage(ctx context.Context, arg DeleteScheduledMessageParams) error {
	_, err := q.db.Exec(ctx, deleteScheduledMessage, arg.ID, arg.UserID)
	return err
}

const listDueScheduledMessages = `-- name: ListDueScheduledMessages :many
select id, user_id, conversation_id, project_id, body, parent_id, tags, send_at, sent_at, created_at from scheduled_messages
where sent_at is null and send_at <= now()
order by send_at asc
`

// sweep input: everything past due, still unsent
func (q *Queries) ListDueScheduledMessages(ctx context.Context) ([]ScheduledMessage, error) {
	rows, err := q.db.Query(ctx, listDueScheduledMessages)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ScheduledMessage{}
	for rows.Next() {
		var i ScheduledMessage
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.ConversationID,
			&i.ProjectID,
			&i.Body,
			&i.ParentID,
			&i.Tags,
			&i.SendAt,
			&i.SentAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listScheduledMessages = `-- name: ListScheduledMessages :many
select id, user_id, conversation_id, project_id, body, parent_id, tags, send_at, sent_at, created_at from scheduled_messages
where user_id = $1 and sent_at is null
order by send_at asc
`

// the user's pending queue, soonest first
func (q *Queries) ListScheduledMessages(ctx context.Context, userID pgtype.UUID) ([]ScheduledMessage, error) {
	rows, err := q.db.Query(ctx, listScheduledMessages, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ScheduledMessage{}
	for rows.Next() {
		var i ScheduledMessage
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.ConversationID,
			&i.ProjectID,
			&i.Body,
			&i.ParentID,
			&i.Tags,
			&i.SendAt,
			&i.SentAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markScheduledMessageSent = `-- name: MarkScheduledMessageSent :exec
update scheduled_messages set sent_at = now()
where id = $1 and sent_at is null
`

func (q *Queries) MarkScheduledMessageSent(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, markScheduledMessageSent, id)
	return err
}
