// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: search.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const searchIssues = `-- name: SearchIssues :many
select i.id, i.number, i.title, i.status, i.priority, i.project_id,
       p.key as project_key,
       ts_rank(
         to_tsvector('english', i.title || ' ' || i.description)
         || to_tsvector('simple', p.key || '-' || i.number || ' ' || p.key || i.number),
         websearch_to_tsquery('english', $2)) as rank
from issues i
join projects p on p.id = i.project_id
join workspace_members wm on wm.workspace_id = p.workspace_id and wm.user_id = $1
where (to_tsvector('english', i.title || ' ' || i.description)
       || to_tsvector('simple', p.key || '-' || i.number || ' ' || p.key || i.number))
      @@ websearch_to_tsquery('english', $2)
      or upper(p.key || '-' || i.number) = upper($2)
order by rank desc, i.updated_at desc
limit 20
`

type SearchIssuesParams struct {
	UserID             pgtype.UUID `json:"user_id"`
	WebsearchToTsquery string      `json:"websearch_to_tsquery"`
}

type SearchIssuesRow struct {
	ID         pgtype.UUID `json:"id"`
	Number     int32       `json:"number"`
	Title      string      `json:"title"`
	Status     string      `json:"status"`
	Priority   string      `json:"priority"`
	ProjectID  pgtype.UUID `json:"project_id"`
	ProjectKey string      `json:"project_key"`
	Rank       float32     `json:"rank"`
}

func (q *Queries) SearchIssues(ctx context.Context, arg SearchIssuesParams) ([]SearchIssuesRow, error) {
	rows, err := q.db.Query(ctx, searchIssues, arg.UserID, arg.WebsearchToTsquery)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SearchIssuesRow{}
	for rows.Next() {
		var i SearchIssuesRow
		if err := rows.Scan(
			&i.ID,
			&i.Number,
			&i.Title,
			&i.Status,
			&i.Priority,
			&i.ProjectID,
			&i.ProjectKey,
			&i.Rank,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchMessages = `-- name: SearchMessages :many
select m.id, m.body, m.created_at, c.project_id,
       coalesce(u.name, a.name, nullif(m.author_name_snapshot, ''), '') as author_name,
       coalesce(ts_rank(to_tsvector('english', m.body),
               websearch_to_tsquery('english', nullif($2, ''))), 0) as rank
from messages m
join conversations c on c.id = m.conversation_id
join projects p on p.id = c.project_id
join workspace_members wm on wm.workspace_id = p.workspace_id and wm.user_id = $1
left join users u on u.id = m.author_user_id
left join agents a on a.id = m.author_agent_id
where m.deleted_at is null
  and ($2 = '' or to_tsvector('english', m.body) @@ websearch_to_tsquery('english', $2))
  and ($3 = '' or coalesce(u.name, a.name, nullif(m.author_name_snapshot, ''), '') ilike $3)
  and ($4 = '' or upper(p.key) = upper($4))
  and ($5::bool is not true or exists (
        select 1 from message_attachments ma
        join attachments att on att.id = ma.attachment_id
        where ma.message_id = m.id and att.content_type like 'image/%'))
  and ($6::bool is not true or exists (
        select 1 from message_attachments ma where ma.message_id = m.id))
  and ($7::timestamptz is null or m.created_at < $7::timestamptz)
  and ($8::timestamptz is null or m.created_at >= $8::timestamptz)
order by rank desc, m.created_at desc
limit 20
`

type SearchMessagesParams struct {
	UserID     pgtype.UUID        `json:"user_id"`
	Q          interface{}        `json:"q"`
	Author     interface{}        `json:"author"`
	ProjectKey interface{}        `json:"project_key"`
	HasImage   pgtype.Bool        `json:"has_image"`
	HasFile    pgtype.Bool        `json:"has_file"`
	Before     pgtype.Timestamptz `json:"before"`
	After      pgtype.Timestamptz `json:"after"`
}

type SearchMessagesRow struct {
	ID         pgtype.UUID        `json:"id"`
	Body       string             `json:"body"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	ProjectID  pgtype.UUID        `json:"project_id"`
	AuthorName string             `json:"author_name"`
	Rank       interface{}        `json:"rank"`
}

// global message FTS across the user's workspaces, ranked.
// Optional qualifiers parsed by the handler: author ilike, project key,
// has-image/has-file attachment filters, created_at bounds.
func (q *Queries) SearchMessages(ctx context.Context, arg SearchMessagesParams) ([]SearchMessagesRow, error) {
	rows, err := q.db.Query(ctx, searchMessages,
		arg.UserID,
		arg.Q,
		arg.Author,
		arg.ProjectKey,
		arg.HasImage,
		arg.HasFile,
		arg.Before,
		arg.After,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SearchMessagesRow{}
	for rows.Next() {
		var i SearchMessagesRow
		if err := rows.Scan(
			&i.ID,
			&i.Body,
			&i.CreatedAt,
			&i.ProjectID,
			&i.AuthorName,
			&i.Rank,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchProjects = `-- name: SearchProjects :many
select p.id, p.key, p.name, p.description, p.icon, p.color,
       ts_rank(to_tsvector('english', p.name || ' ' || p.description),
               websearch_to_tsquery('english', $2)) as rank
from projects p
join workspace_members wm on wm.workspace_id = p.workspace_id and wm.user_id = $1
where to_tsvector('english', p.name || ' ' || p.description)
      @@ websearch_to_tsquery('english', $2)
order by rank desc
limit 10
`

type SearchProjectsParams struct {
	UserID             pgtype.UUID `json:"user_id"`
	WebsearchToTsquery string      `json:"websearch_to_tsquery"`
}

type SearchProjectsRow struct {
	ID          pgtype.UUID `json:"id"`
	Key         string      `json:"key"`
	Name        string      `json:"name"`
	Description string      `json:"description"`
	Icon        pgtype.Text `json:"icon"`
	Color       pgtype.Text `json:"color"`
	Rank        float32     `json:"rank"`
}

func (q *Queries) SearchProjects(ctx context.Context, arg SearchProjectsParams) ([]SearchProjectsRow, error) {
	rows, err := q.db.Query(ctx, searchProjects, arg.UserID, arg.WebsearchToTsquery)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SearchProjectsRow{}
	for rows.Next() {
		var i SearchProjectsRow
		if err := rows.Scan(
			&i.ID,
			&i.Key,
			&i.Name,
			&i.Description,
			&i.Icon,
			&i.Color,
			&i.Rank,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchTodos = `-- name: SearchTodos :many
select t.id, t.content, t.done, t.project_id,
       ts_rank(to_tsvector('english', t.content), websearch_to_tsquery('english', $2)) as rank
from agent_todos t
join projects p on p.id = t.project_id
join workspace_members wm on wm.workspace_id = p.workspace_id and wm.user_id = $1
where to_tsvector('english', t.content) @@ websearch_to_tsquery('english', $2)
order by rank desc, t.created_at desc
limit 20
`

type SearchTodosParams struct {
	UserID             pgtype.UUID `json:"user_id"`
	WebsearchToTsquery string      `json:"websearch_to_tsquery"`
}

type SearchTodosRow struct {
	ID        pgtype.UUID `json:"id"`
	Content   string      `json:"content"`
	Done      bool        `json:"done"`
	ProjectID pgtype.UUID `json:"project_id"`
	Rank      float32     `json:"rank"`
}

func (q *Queries) SearchTodos(ctx context.Context, arg SearchTodosParams) ([]SearchTodosRow, error) {
	rows, err := q.db.Query(ctx, searchTodos, arg.UserID, arg.WebsearchToTsquery)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SearchTodosRow{}
	for rows.Next() {
		var i SearchTodosRow
		if err := rows.Scan(
			&i.ID,
			&i.Content,
			&i.Done,
			&i.ProjectID,
			&i.Rank,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
