// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: sessions.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createSession = `-- name: CreateSession :one
insert into sessions (user_id, token_hash, expires_at, ip, user_agent)
values ($1, $2, $3, $4, $5)
returning id
`

type CreateSessionParams struct {
	UserID    pgtype.UUID        `json:"user_id"`
	TokenHash string             `json:"token_hash"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
	Ip        string             `json:"ip"`
	UserAgent string             `json:"user_agent"`
}

func (q *Queries) CreateSession(ctx context.Context, arg CreateSessionParams) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, createSession,
		arg.UserID,
		arg.TokenHash,
		arg.ExpiresAt,
		arg.Ip,
		arg.UserAgent,
	)
	var id pgtype.UUID
	err := row.Scan(&id)
	return id, err
}

const deleteOtherSessions = `-- name: DeleteOtherSessions :exec
delete from sessions where user_id = $1 and token_hash <> $2
`

type DeleteOtherSessionsParams struct {
	UserID    pgtype.UUID `json:"user_id"`
	TokenHash string      `json:"token_hash"`
}

func (q *Queries) DeleteOtherSessions(ctx context.Context, arg DeleteOtherSessionsParams) error {
	_, err := q.db.Exec(ctx, deleteOtherSessions, arg.UserID, arg.TokenHash)
	return err
}

const deleteSession = `-- name: DeleteSession :exec
delete from sessions where token_hash = $1
`

func (q *Queries) DeleteSession(ctx context.Context, tokenHash string) error {
	_, err := q.db.Exec(ctx, deleteSession, tokenHash)
	return err
}

const getSessionUser = `-- name: GetSessionUser :one
select s.id as session_id, s.expires_at, s.last_seen_at,
       u.id, u.email, u.name, u.avatar_key, u.created_at
from sessions s
join users u on u.id = s.user_id
where s.token_hash = $1 and s.expires_at > now()
`

type GetSessionUserRow struct {
	SessionID  pgtype.UUID        `json:"session_id"`
	ExpiresAt  pgtype.Timestamptz `json:"expires_at"`
	LastSeenAt pgtype.Timestamptz `json:"last_seen_at"`
	ID         pgtype.UUID        `json:"id"`
	Email      string             `json:"email"`
	Name       string             `json:"name"`
	AvatarKey  pgtype.Text        `json:"avatar_key"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) GetSessionUser(ctx context.Context, tokenHash string) (GetSessionUserRow, error) {
	row := q.db.QueryRow(ctx, getSessionUser, tokenHash)
	var i GetSessionUserRow
	err := row.Scan(
		&i.SessionID,
		&i.ExpiresAt,
		&i.LastSeenAt,
		&i.ID,
		&i.Email,
		&i.Name,
		&i.AvatarKey,
		&i.CreatedAt,
	)
	return i, err
}

const touchSession = `-- name: TouchSession :exec
update sessions
set last_seen_at = now(), expires_at = now() + make_interval(secs => $2::int)
where token_hash = $1
`

type TouchSessionParams struct {
	TokenHash string `json:"token_hash"`
	TtlSecs   int32  `json:"ttl_secs"`
}

func (q *Queries) TouchSession(ctx context.Context, arg TouchSessionParams) error {
	_, err := q.db.Exec(ctx, touchSession, arg.TokenHash, arg.TtlSecs)
	return err
}
