// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: todos.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createTodo = `-- name: CreateTodo :one
insert into agent_todos (project_id, agent_id, issue_id, content, position)
values ($1, $2, $3,
        $4,
        coalesce((select max(position) + 1 from agent_todos where project_id = $1), 0))
returning id, project_id, agent_id, issue_id, content, done, position, created_at, updated_at, agent_name_snapshot
`

type CreateTodoParams struct {
	ProjectID pgtype.UUID `json:"project_id"`
	AgentID   pgtype.UUID `json:"agent_id"`
	IssueID   pgtype.UUID `json:"issue_id"`
	Content   string      `json:"content"`
}

func (q *Queries) CreateTodo(ctx context.Context, arg CreateTodoParams) (AgentTodo, error) {
	row := q.db.QueryRow(ctx, createTodo,
		arg.ProjectID,
		arg.AgentID,
		arg.IssueID,
		arg.Content,
	)
	var i AgentTodo
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.AgentID,
		&i.IssueID,
		&i.Content,
		&i.Done,
		&i.Position,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.AgentNameSnapshot,
	)
	return i, err
}

const deleteTodo = `-- name: DeleteTodo :exec
delete from agent_todos where id = $1
`

func (q *Queries) DeleteTodo(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteTodo, id)
	return err
}

const getIssueByKey = `-- name: GetIssueByKey :one
select i.id, i.number, i.project_id, p.key as project_key
from issues i join projects p on p.id = i.project_id
where p.id = $1 and i.number = $2
`

type GetIssueByKeyParams struct {
	ProjectID pgtype.UUID `json:"project_id"`
	Number    int32       `json:"number"`
}

type GetIssueByKeyRow struct {
	ID         pgtype.UUID `json:"id"`
	Number     int32       `json:"number"`
	ProjectID  pgtype.UUID `json:"project_id"`
	ProjectKey string      `json:"project_key"`
}

func (q *Queries) GetIssueByKey(ctx context.Context, arg GetIssueByKeyParams) (GetIssueByKeyRow, error) {
	row := q.db.QueryRow(ctx, getIssueByKey, arg.ProjectID, arg.Number)
	var i GetIssueByKeyRow
	err := row.Scan(
		&i.ID,
		&i.Number,
		&i.ProjectID,
		&i.ProjectKey,
	)
	return i, err
}

const getTodo = `-- name: GetTodo :one
select id, project_id, agent_id, issue_id, content, done, position, created_at, updated_at, agent_name_snapshot from agent_todos where id = $1
`

func (q *Queries) GetTodo(ctx context.Context, id pgtype.UUID) (AgentTodo, error) {
	row := q.db.QueryRow(ctx, getTodo, id)
	var i AgentTodo
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.AgentID,
		&i.IssueID,
		&i.Content,
		&i.Done,
		&i.Position,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.AgentNameSnapshot,
	)
	return i, err
}

const getTodoJoined = `-- name: GetTodoJoined :one
select t.id, t.project_id, t.agent_id, t.issue_id, t.content, t.done, t.position, t.created_at, t.updated_at, t.agent_name_snapshot, coalesce(a.name, nullif(t.agent_name_snapshot, '')) as agent_name, i.number as issue_number, p.key as issue_key
from agent_todos t
left join agents a on a.id = t.agent_id
left join issues i on i.id = t.issue_id
left join projects p on p.id = i.project_id
where t.id = $1
`

type GetTodoJoinedRow struct {
	ID                pgtype.UUID        `json:"id"`
	ProjectID         pgtype.UUID        `json:"project_id"`
	AgentID           pgtype.UUID        `json:"agent_id"`
	IssueID           pgtype.UUID        `json:"issue_id"`
	Content           string             `json:"content"`
	Done              bool               `json:"done"`
	Position          int32              `json:"position"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	UpdatedAt         pgtype.Timestamptz `json:"updated_at"`
	AgentNameSnapshot string             `json:"agent_name_snapshot"`
	AgentName         string             `json:"agent_name"`
	IssueNumber       pgtype.Int4        `json:"issue_number"`
	IssueKey          pgtype.Text        `json:"issue_key"`
}

func (q *Queries) GetTodoJoined(ctx context.Context, id pgtype.UUID) (GetTodoJoinedRow, error) {
	row := q.db.QueryRow(ctx, getTodoJoined, id)
	var i GetTodoJoinedRow
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.AgentID,
		&i.IssueID,
		&i.Content,
		&i.Done,
		&i.Position,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.AgentNameSnapshot,
		&i.AgentName,
		&i.IssueNumber,
		&i.IssueKey,
	)
	return i, err
}

const listTodos = `-- name: ListTodos :many
select t.id, t.project_id, t.agent_id, t.issue_id, t.content, t.done, t.position, t.created_at, t.updated_at, t.agent_name_snapshot, coalesce(a.name, nullif(t.agent_name_snapshot, '')) as agent_name, i.number as issue_number, p.key as issue_key
from agent_todos t
left join agents a on a.id = t.agent_id
left join issues i on i.id = t.issue_id
left join projects p on p.id = i.project_id
where t.project_id = $1
order by t.done, t.position, t.created_at
`

type ListTodosRow struct {
	ID                pgtype.UUID        `json:"id"`
	ProjectID         pgtype.UUID        `json:"project_id"`
	AgentID           pgtype.UUID        `json:"agent_id"`
	IssueID           pgtype.UUID        `json:"issue_id"`
	Content           string             `json:"content"`
	Done              bool               `json:"done"`
	Position          int32              `json:"position"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	UpdatedAt         pgtype.Timestamptz `json:"updated_at"`
	AgentNameSnapshot string             `json:"agent_name_snapshot"`
	AgentName         string             `json:"agent_name"`
	IssueNumber       pgtype.Int4        `json:"issue_number"`
	IssueKey          pgtype.Text        `json:"issue_key"`
}

func (q *Queries) ListTodos(ctx context.Context, projectID pgtype.UUID) ([]ListTodosRow, error) {
	rows, err := q.db.Query(ctx, listTodos, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListTodosRow{}
	for rows.Next() {
		var i ListTodosRow
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.AgentID,
			&i.IssueID,
			&i.Content,
			&i.Done,
			&i.Position,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.AgentNameSnapshot,
			&i.AgentName,
			&i.IssueNumber,
			&i.IssueKey,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const todoProject = `-- name: TodoProject :one
select project_id from agent_todos where id = $1
`

func (q *Queries) TodoProject(ctx context.Context, id pgtype.UUID) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, todoProject, id)
	var project_id pgtype.UUID
	err := row.Scan(&project_id)
	return project_id, err
}

const updateTodo = `-- name: UpdateTodo :one
update agent_todos set
    content = coalesce($1::text, content),
    done = coalesce($2::boolean, done),
    issue_id = coalesce($3::uuid, issue_id),
    updated_at = now()
where id = $4
returning id, project_id, agent_id, issue_id, content, done, position, created_at, updated_at, agent_name_snapshot
`

type UpdateTodoParams struct {
	Content pgtype.Text `json:"content"`
	Done    pgtype.Bool `json:"done"`
	IssueID pgtype.UUID `json:"issue_id"`
	ID      pgtype.UUID `json:"id"`
}

func (q *Queries) UpdateTodo(ctx context.Context, arg UpdateTodoParams) (AgentTodo, error) {
	row := q.db.QueryRow(ctx, updateTodo,
		arg.Content,
		arg.Done,
		arg.IssueID,
		arg.ID,
	)
	var i AgentTodo
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.AgentID,
		&i.IssueID,
		&i.Content,
		&i.Done,
		&i.Position,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.AgentNameSnapshot,
	)
	return i, err
}
