// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: webhooks.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const activeWebhooksForProject = `-- name: ActiveWebhooksForProject :many
select id, project_id, url, secret, events, active, created_by, created_at, updated_at from webhook_subscriptions where project_id = $1 and active
`

func (q *Queries) ActiveWebhooksForProject(ctx context.Context, projectID pgtype.UUID) ([]WebhookSubscription, error) {
	rows, err := q.db.Query(ctx, activeWebhooksForProject, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []WebhookSubscription{}
	for rows.Next() {
		var i WebhookSubscription
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.Url,
			&i.Secret,
			&i.Events,
			&i.Active,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const createWebhookSubscription = `-- name: CreateWebhookSubscription :one
insert into webhook_subscriptions (project_id, url, secret, events, active, created_by)
values ($1, $2, $3, $4::text[], $5, $6)
returning id, project_id, url, secret, events, active, created_by, created_at, updated_at
`

type CreateWebhookSubscriptionParams struct {
	ProjectID pgtype.UUID `json:"project_id"`
	Url       string      `json:"url"`
	Secret    string      `json:"secret"`
	Events    []string    `json:"events"`
	Active    bool        `json:"active"`
	CreatedBy pgtype.UUID `json:"created_by"`
}

func (q *Queries) CreateWebhookSubscription(ctx context.Context, arg CreateWebhookSubscriptionParams) (WebhookSubscription, error) {
	row := q.db.QueryRow(ctx, createWebhookSubscription,
		arg.ProjectID,
		arg.Url,
		arg.Secret,
		arg.Events,
		arg.Active,
		arg.CreatedBy,
	)
	var i WebhookSubscription
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Url,
		&i.Secret,
		&i.Events,
		&i.Active,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteWebhook = `-- name: DeleteWebhook :exec
delete from webhook_subscriptions where id = $1
`

func (q *Queries) DeleteWebhook(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteWebhook, id)
	return err
}

const getWebhookByID = `-- name: GetWebhookByID :one
select s.id, s.project_id, s.url, s.secret, s.events, s.active, s.created_by, s.created_at, s.updated_at, p.workspace_id
from webhook_subscriptions s
join projects p on p.id = s.project_id
where s.id = $1
`

type GetWebhookByIDRow struct {
	ID          pgtype.UUID        `json:"id"`
	ProjectID   pgtype.UUID        `json:"project_id"`
	Url         string             `json:"url"`
	Secret      string             `json:"secret"`
	Events      []string           `json:"events"`
	Active      bool               `json:"active"`
	CreatedBy   pgtype.UUID        `json:"created_by"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
	WorkspaceID pgtype.UUID        `json:"workspace_id"`
}

func (q *Queries) GetWebhookByID(ctx context.Context, id pgtype.UUID) (GetWebhookByIDRow, error) {
	row := q.db.QueryRow(ctx, getWebhookByID, id)
	var i GetWebhookByIDRow
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Url,
		&i.Secret,
		&i.Events,
		&i.Active,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.WorkspaceID,
	)
	return i, err
}

const getWebhookForUser = `-- name: GetWebhookForUser :one
select s.id, s.project_id, s.url, s.secret, s.events, s.active, s.created_by, s.created_at, s.updated_at, p.workspace_id
from webhook_subscriptions s
join projects p on p.id = s.project_id
join workspace_members wm on wm.workspace_id = p.workspace_id and wm.user_id = $1
where s.id = $2
`

type GetWebhookForUserParams struct {
	UserID pgtype.UUID `json:"user_id"`
	ID     pgtype.UUID `json:"id"`
}

type GetWebhookForUserRow struct {
	ID          pgtype.UUID        `json:"id"`
	ProjectID   pgtype.UUID        `json:"project_id"`
	Url         string             `json:"url"`
	Secret      string             `json:"secret"`
	Events      []string           `json:"events"`
	Active      bool               `json:"active"`
	CreatedBy   pgtype.UUID        `json:"created_by"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
	WorkspaceID pgtype.UUID        `json:"workspace_id"`
}

// subscription + owning project, only when the caller is a workspace member
func (q *Queries) GetWebhookForUser(ctx context.Context, arg GetWebhookForUserParams) (GetWebhookForUserRow, error) {
	row := q.db.QueryRow(ctx, getWebhookForUser, arg.UserID, arg.ID)
	var i GetWebhookForUserRow
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Url,
		&i.Secret,
		&i.Events,
		&i.Active,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.WorkspaceID,
	)
	return i, err
}

const listProjectWebhooks = `-- name: ListProjectWebhooks :many
select id, project_id, url, secret, events, active, created_by, created_at, updated_at from webhook_subscriptions where project_id = $1 order by created_at desc
`

func (q *Queries) ListProjectWebhooks(ctx context.Context, projectID pgtype.UUID) ([]WebhookSubscription, error) {
	rows, err := q.db.Query(ctx, listProjectWebhooks, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []WebhookSubscription{}
	for rows.Next() {
		var i WebhookSubscription
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.Url,
			&i.Secret,
			&i.Events,
			&i.Active,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWebhookDeliveries = `-- name: ListWebhookDeliveries :many
select id, subscription_id, delivery_id, event_type, payload, status_code, attempts, duration_ms, success, created_at from webhook_deliveries where subscription_id = $1
order by created_at desc limit 50
`

func (q *Queries) ListWebhookDeliveries(ctx context.Context, subscriptionID pgtype.UUID) ([]WebhookDelivery, error) {
	rows, err := q.db.Query(ctx, listWebhookDeliveries, subscriptionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []WebhookDelivery{}
	for rows.Next() {
		var i WebhookDelivery
		if err := rows.Scan(
			&i.ID,
			&i.SubscriptionID,
			&i.DeliveryID,
			&i.EventType,
			&i.Payload,
			&i.StatusCode,
			&i.Attempts,
			&i.DurationMs,
			&i.Success,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const recordWebhookDelivery = `-- name: RecordWebhookDelivery :one
insert into webhook_deliveries (subscription_id, event_type, payload, status_code, attempts, duration_ms, success)
values ($1, $2, $3::jsonb, $4, $5, $6, $7)
returning id, subscription_id, delivery_id, event_type, payload, status_code, attempts, duration_ms, success, created_at
`

type RecordWebhookDeliveryParams struct {
	SubscriptionID pgtype.UUID `json:"subscription_id"`
	EventType      string      `json:"event_type"`
	Payload        []byte      `json:"payload"`
	StatusCode     pgtype.Int4 `json:"status_code"`
	Attempts       int32       `json:"attempts"`
	DurationMs     int32       `json:"duration_ms"`
	Success        bool        `json:"success"`
}

func (q *Queries) RecordWebhookDelivery(ctx context.Context, arg RecordWebhookDeliveryParams) (WebhookDelivery, error) {
	row := q.db.QueryRow(ctx, recordWebhookDelivery,
		arg.SubscriptionID,
		arg.EventType,
		arg.Payload,
		arg.StatusCode,
		arg.Attempts,
		arg.DurationMs,
		arg.Success,
	)
	var i WebhookDelivery
	err := row.Scan(
		&i.ID,
		&i.SubscriptionID,
		&i.DeliveryID,
		&i.EventType,
		&i.Payload,
		&i.StatusCode,
		&i.Attempts,
		&i.DurationMs,
		&i.Success,
		&i.CreatedAt,
	)
	return i, err
}

const trimWebhookDeliveries = `-- name: TrimWebhookDeliveries :exec
delete from webhook_deliveries d
where d.subscription_id = $1
  and d.id not in (
    select id from webhook_deliveries
    where subscription_id = $1
    order by created_at desc limit 200
  )
`

// keep the newest 200 rows per subscription
func (q *Queries) TrimWebhookDeliveries(ctx context.Context, subscriptionID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, trimWebhookDeliveries, subscriptionID)
	return err
}

const updateWebhook = `-- name: UpdateWebhook :one
update webhook_subscriptions set
    url = coalesce($1, url),
    events = coalesce($2::text[], events),
    active = coalesce($3, active),
    updated_at = now()
where id = $4
returning id, project_id, url, secret, events, active, created_by, created_at, updated_at
`

type UpdateWebhookParams struct {
	Url    pgtype.Text `json:"url"`
	Events []string    `json:"events"`
	Active pgtype.Bool `json:"active"`
	ID     pgtype.UUID `json:"id"`
}

func (q *Queries) UpdateWebhook(ctx context.Context, arg UpdateWebhookParams) (WebhookSubscription, error) {
	row := q.db.QueryRow(ctx, updateWebhook,
		arg.Url,
		arg.Events,
		arg.Active,
		arg.ID,
	)
	var i WebhookSubscription
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Url,
		&i.Secret,
		&i.Events,
		&i.Active,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
