// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: workspaces.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const addWorkspaceMember = `-- name: AddWorkspaceMember :exec
insert into workspace_members (workspace_id, user_id, role)
values ($1, $2, $3)
`

type AddWorkspaceMemberParams struct {
	WorkspaceID pgtype.UUID `json:"workspace_id"`
	UserID      pgtype.UUID `json:"user_id"`
	Role        string      `json:"role"`
}

func (q *Queries) AddWorkspaceMember(ctx context.Context, arg AddWorkspaceMemberParams) error {
	_, err := q.db.Exec(ctx, addWorkspaceMember, arg.WorkspaceID, arg.UserID, arg.Role)
	return err
}

const createWorkspace = `-- name: CreateWorkspace :one
insert into workspaces (name, slug)
values ($1, $2)
returning id, name, slug, created_at
`

type CreateWorkspaceParams struct {
	Name string `json:"name"`
	Slug string `json:"slug"`
}

type CreateWorkspaceRow struct {
	ID        pgtype.UUID        `json:"id"`
	Name      string             `json:"name"`
	Slug      string             `json:"slug"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) CreateWorkspace(ctx context.Context, arg CreateWorkspaceParams) (CreateWorkspaceRow, error) {
	row := q.db.QueryRow(ctx, createWorkspace, arg.Name, arg.Slug)
	var i CreateWorkspaceRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.CreatedAt,
	)
	return i, err
}

const getWorkspaceByID = `-- name: GetWorkspaceByID :one
select id, name, slug, avatar_key, created_at
from workspaces
where id = $1
`

type GetWorkspaceByIDRow struct {
	ID        pgtype.UUID        `json:"id"`
	Name      string             `json:"name"`
	Slug      string             `json:"slug"`
	AvatarKey pgtype.Text        `json:"avatar_key"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) GetWorkspaceByID(ctx context.Context, id pgtype.UUID) (GetWorkspaceByIDRow, error) {
	row := q.db.QueryRow(ctx, getWorkspaceByID, id)
	var i GetWorkspaceByIDRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.AvatarKey,
		&i.CreatedAt,
	)
	return i, err
}

const getWorkspaceRole = `-- name: GetWorkspaceRole :one
select role
from workspace_members
where workspace_id = $1 and user_id = $2
`

type GetWorkspaceRoleParams struct {
	WorkspaceID pgtype.UUID `json:"workspace_id"`
	UserID      pgtype.UUID `json:"user_id"`
}

func (q *Queries) GetWorkspaceRole(ctx context.Context, arg GetWorkspaceRoleParams) (string, error) {
	row := q.db.QueryRow(ctx, getWorkspaceRole, arg.WorkspaceID, arg.UserID)
	var role string
	err := row.Scan(&role)
	return role, err
}

const listWorkspaceMembers = `-- name: ListWorkspaceMembers :many
select u.id, u.email, u.name, u.avatar_key, u.created_at, wm.role
from workspace_members wm
join users u on u.id = wm.user_id
where wm.workspace_id = $1
order by wm.created_at
`

type ListWorkspaceMembersRow struct {
	ID        pgtype.UUID        `json:"id"`
	Email     string             `json:"email"`
	Name      string             `json:"name"`
	AvatarKey pgtype.Text        `json:"avatar_key"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	Role      string             `json:"role"`
}

func (q *Queries) ListWorkspaceMembers(ctx context.Context, workspaceID pgtype.UUID) ([]ListWorkspaceMembersRow, error) {
	rows, err := q.db.Query(ctx, listWorkspaceMembers, workspaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListWorkspaceMembersRow{}
	for rows.Next() {
		var i ListWorkspaceMembersRow
		if err := rows.Scan(
			&i.ID,
			&i.Email,
			&i.Name,
			&i.AvatarKey,
			&i.CreatedAt,
			&i.Role,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWorkspacesForUser = `-- name: ListWorkspacesForUser :many
select w.id, w.name, w.slug, w.avatar_key, w.created_at, wm.role
from workspaces w
join workspace_members wm on wm.workspace_id = w.id
where wm.user_id = $1
order by w.name
`

type ListWorkspacesForUserRow struct {
	ID        pgtype.UUID        `json:"id"`
	Name      string             `json:"name"`
	Slug      string             `json:"slug"`
	AvatarKey pgtype.Text        `json:"avatar_key"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	Role      string             `json:"role"`
}

func (q *Queries) ListWorkspacesForUser(ctx context.Context, userID pgtype.UUID) ([]ListWorkspacesForUserRow, error) {
	rows, err := q.db.Query(ctx, listWorkspacesForUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListWorkspacesForUserRow{}
	for rows.Next() {
		var i ListWorkspacesForUserRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Slug,
			&i.AvatarKey,
			&i.CreatedAt,
			&i.Role,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setWorkspaceAvatarKey = `-- name: SetWorkspaceAvatarKey :one
update workspaces set avatar_key = $1
where id = $2
returning id
`

type SetWorkspaceAvatarKeyParams struct {
	AvatarKey pgtype.Text `json:"avatar_key"`
	ID        pgtype.UUID `json:"id"`
}

func (q *Queries) SetWorkspaceAvatarKey(ctx context.Context, arg SetWorkspaceAvatarKeyParams) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, setWorkspaceAvatarKey, arg.AvatarKey, arg.ID)
	var id pgtype.UUID
	err := row.Scan(&id)
	return id, err
}

const workspaceSlugExists = `-- name: WorkspaceSlugExists :one
select exists(select 1 from workspaces where slug = $1) as exists
`

func (q *Queries) WorkspaceSlugExists(ctx context.Context, slug string) (bool, error) {
	row := q.db.QueryRow(ctx, workspaceSlugExists, slug)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}
