// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: workspaces.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const addWorkspaceMember = `-- name: AddWorkspaceMember :exec
insert into workspace_members (workspace_id, user_id, role)
values ($1, $2, $3)
`

type AddWorkspaceMemberParams struct {
	WorkspaceID pgtype.UUID `json:"workspace_id"`
	UserID      pgtype.UUID `json:"user_id"`
	Role        string      `json:"role"`
}

func (q *Queries) AddWorkspaceMember(ctx context.Context, arg AddWorkspaceMemberParams) error {
	_, err := q.db.Exec(ctx, addWorkspaceMember, arg.WorkspaceID, arg.UserID, arg.Role)
	return err
}

const createWorkspace = `-- name: CreateWorkspace :one
insert into workspaces (name, slug)
values ($1, $2)
returning id, name, slug, created_at
`

type CreateWorkspaceParams struct {
	Name string `json:"name"`
	Slug string `json:"slug"`
}

func (q *Queries) CreateWorkspace(ctx context.Context, arg CreateWorkspaceParams) (Workspace, error) {
	row := q.db.QueryRow(ctx, createWorkspace, arg.Name, arg.Slug)
	var i Workspace
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.CreatedAt,
	)
	return i, err
}

const getWorkspaceRole = `-- name: GetWorkspaceRole :one
select role
from workspace_members
where workspace_id = $1 and user_id = $2
`

type GetWorkspaceRoleParams struct {
	WorkspaceID pgtype.UUID `json:"workspace_id"`
	UserID      pgtype.UUID `json:"user_id"`
}

func (q *Queries) GetWorkspaceRole(ctx context.Context, arg GetWorkspaceRoleParams) (string, error) {
	row := q.db.QueryRow(ctx, getWorkspaceRole, arg.WorkspaceID, arg.UserID)
	var role string
	err := row.Scan(&role)
	return role, err
}

const listWorkspacesForUser = `-- name: ListWorkspacesForUser :many
select w.id, w.name, w.slug, wm.role
from workspaces w
join workspace_members wm on wm.workspace_id = w.id
where wm.user_id = $1
order by w.name
`

type ListWorkspacesForUserRow struct {
	ID   pgtype.UUID `json:"id"`
	Name string      `json:"name"`
	Slug string      `json:"slug"`
	Role string      `json:"role"`
}

func (q *Queries) ListWorkspacesForUser(ctx context.Context, userID pgtype.UUID) ([]ListWorkspacesForUserRow, error) {
	rows, err := q.db.Query(ctx, listWorkspacesForUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListWorkspacesForUserRow{}
	for rows.Next() {
		var i ListWorkspacesForUserRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Slug,
			&i.Role,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
